### ISSUE TITLE
Add component name to the generated class name 

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#100]
To not force people switch between react dev tools and dom inspector. Reported by @rob2d

**Comment by kof** [comment]
This should wait for JSS 8 comming out soon, because theere will be a breaking change of generateClassName option.

**Comment by iamstarkov** [comment]
are we ready?

**Comment by kof** [comment]
yep, lets do this)

**Comment by rob2d** [comment]
Awesome. Since I'm the one who brought it up/requested this, would you need any help on it?

**Comment by iamstarkov** [comment]
@rob2d if you can add tests, that would be nice

**Comment by iamstarkov** [comment]
@rob2d what do you think about it?

**Comment by rob2d** [comment]
Sorry about the delay. I can try to get that in early this weekend. 🙂

**Comment by iamstarkov** [comment]
thanks

**Comment by iamstarkov** [comment]
that would be cool

**Comment by rob2d** [comment]
Added a test for generated classnames to contain the Component's `name` property 😃 

Please let me know if there's any issues with that.

**Comment by kof** [comment]
next jss version will support classNamePrefix option

**Comment by rob2d** [comment]
awesome! 😁 looking forward to it. thanks for adding this feature.

**Comment by kof** [comment]
Released v8
