### ISSUE TITLE
Reverse order of sheet mounting

### ISSUE THREAD

**Issue by AlastairTaft** [cssinjs/react-jss#103]
I don't know how to solve this one but presenting a use-case... the order the sheets are mounted in the document follows the React mount order but it's counter intuitive.

Let's say I have a `<Button />` component that mounts its own sheet to give it styling. I then have a `<SecondaryButton />` component that wishes to override the height and colour of the `<Button />`.

That component may look something like this.

```js
import React, { Component } from 'react'
import { create } from 'jss'
import preset from 'jss-preset-default'
import injectSheet from 'react-jss'
import Button from 'my-third-party-lib'

const jss = create(preset())
const sheet = jss.createStyleSheet({
  customButtonStyling: {
    height: 30,
    backgroundColor: 'red',
  },
})

class SecondaryButton extends Component {
  render = () => {
    var { classes, children } = this.props
      return <Button 
        className={classes.customButtonStyling} 
      >
        {children}
      </Button>
  }
}

export default injectSheet(sheet)(SecondaryButton)
```

The problem is my styles never apply because the `<SecondaryButtons />`'s stylesheet gets added to the document before the `<Button />`'s stylesheet gets added. So the `<Button />`'s `height` and `backgroundColor` always take precedence.

I'd want the imported `<Button />`'s stylesheet to be added to the DOM first and then my custom styles for the `<SecondaryButton />` to be added afterwards so that they override the styling.

Any thoughts?

**Comment by iamstarkov** [comment]
i like it

**Comment by iamstarkov** [comment]
and faced the same problems before

**Comment by kof** [comment]
> the order the sheets are mounted in the document follows the React mount order

Nope, thats not how it works. Will add it to the docs.

**Comment by kof** [comment]
Secondary, your example shows a mix of react-jss and jss. Thats a separate case, lets document it too.

**Comment by kof** [comment]
Order is defined by the moment of time you call `injectSheet` within the same `insertionPoint` option.

There are at least 3 ways to solve it: 
1. Don't use jss directly, use react-jss.
1. Call injectSheet first, then call .attach on your jss sheet.
1. Split them up in different insertionPoints. Use one for direct jss styles and one for react-jss, put first one first in the head, so react-jss will always override.

**Comment by kof** [comment]
@AlastairTaft can you contribute with documentation to the next branch? 

I would like 2 things documented: how the order is defined with `injectSheet` call [see](https://github.com/cssinjs/react-jss/blob/next/src/injectSheet.js) and an example of how to use jss and react-jss together using insertion points.

**Comment by AlastairTaft** [comment]
I don't mind updating the docs but I'd like to understand how it works a bit more before hand. A good step would be for me to solve this use case first.

• Method 2 - Won't fit my use case, as it defeats the point of me using react-jss, I want the sheet to only mount when the component mounts.

• Method 3 - I don't think this is a long term solution, I now have to manage insertion points, what if I go three levels deep on overrides, I have to manage three different insertion points.

• Method 1 - That leaves method 1 which I tried but it does not seem to work. The order is still the wrong way around.

Here's how my method 1 `<SecondaryButton />` class now looks

```js
import React, { Component } from 'react'
import injectSheet, {jss} from 'react-jss'
import Button from 'my-third-party-lib'

const sheet = jss.createStyleSheet({
  customButtonStyling: {
    height: 30,
    backgroundColor: 'red',
  },
})

class SecondaryButton extends Component {
  render = () => {
    var { classes, children } = this.props
      return <Button 
        className={classes.customButtonStyling} 
      >
        {children}
      </Button>
  }
}

export default injectSheet(sheet)(SecondaryButton)
```

I updated my `<Button />` class to also use the jss instance from react-jss.

**Comment by kof** [comment]
> • Method 2 - Won't fit my use case, as it defeats the point of me using react-jss, I want the sheet to only be mounted when the component is mounted.

Who said this is not the case? The order is decided when you call injectSheet(), but the injection itself happens when component will mount.

**Comment by kof** [comment]
> Method 3 - I don't think this is a long term solution, I now have to manage insertion points

I think you miss the point of insertion point. They are not defined per sheet, they are defined per Jss instance. There is not much to manage, you got only 2 of them from what I can see.

**Comment by AlastairTaft** [comment]
> but the injection itself happens when component will mount
I further investigated this. Turns out this is my cock up / misunderstanding. I had three components mounting in this order, each component reused it's own sheet.

• `<Button />`
• `<SecondaryButton />`
• `<Button />`

So when the last button mounts it would re-attach the `<Button />`'s sheet thus overriding the `<SecondaryButton />`'s styles. The way to solve this is to not re-use sheets and just use the standard method of a style object (not sheet).

The least I can do now is help out with the docs.

**Comment by kof** [comment]
>  it would re-attach the

Why do you say so? It if it is already attached it should do nothing.

> solve this is to not re-use sheets 

What exactly do you mean by reuse?

**Comment by AlastairTaft** [comment]
So instead of doing

```js
import injectSheet, { jss } from 'react-jss'
const sheet = jss.createStyleSheet({
  // ...
})
injectSheet(sheet)(MyComponent)
```
to solve my issue I did

```js
import injectStyles from 'react-jss'
const styles = {
  // ...
}
injectStyles(styles)(MyComponent)
```
I guessed this is because the first method re-uses the sheet object, whereas the second one creates a new sheet everytime?

**Comment by kof** [comment]
I guessed this is because the first method re-uses the sheet object, whereas the second one creates a new sheet everytime?

No, static sheets are reused in both cases. Thats why I don't get what you do.

**Comment by kof** [comment]
I think you got source order specificity issue because you attached your sheet you created manually first, so the sheet from react-jss got higher source  order specificity.

**Comment by kof** [comment]
3 suggestions I wrote you before still apply.

**Comment by AlastairTaft** [comment]
I'm not sure why the second method worked for me then. I'll see if I can put an example together.

**Comment by kof** [comment]
Second method is not using jss directly, it is using react-jss, right? It manages the correct source order.

**Comment by AlastairTaft** [comment]
Yeah that's correct

**Comment by iamstarkov** [comment]
i think this issue in current wording didnt exist in the first place. what about rewording it or creating new one?

**Comment by kof** [comment]
Btw. @AlastairTaft have you made a progress?

**Comment by robhung** [comment]
Hi @kof, I'm having a similar issue which relates to the order of sheet mounting. The problem occurs where I'm importing a third-party library of components that also uses injectSheet from `react-jss`, and because it's imported, gets mounted at the very end of `<head>` and overwriting my configured styles.

MyComponent.js
```javascript
import injectSheet from 'react-jss';

import { Button } from 'third-party-library';

const styles = {
  button: {
    color: '#333'
  }
};

function MyComponent({classes}) {
  return (
    <Button className={classes.button}</Button>
  )
};

export default injectSheet(styles)(MyComponent);
```

Button.js
```javascript
import injectSheet from 'react-jss';

const styles = {
  button: {
    color: '#FFF'
  }
};

function Button({classes}) {
  return (
    <div className={classes.button}</div>
  )
};

export default injectSheet(styles)(Button);
```

I've attempted to create an insertion point in my `public.html`

```html
<head>
  ...
  <!-- custom insertion point -->
</head>
```

And attempted to setup an insertion point, although I don't think I'm quite understanding how it works (if `react-jss` is any different to how `jss` sets up a StyleSheet?)

index.js
```javascript
import React from 'react';
import { jss } from 'react-jss'

import './index.css';
import App from './App';

jss.setup({insertionPoint: 'custom-insertion-point'})

render(<App />, document.getElementById('root'));
```

Sorry to revive an old thread!

**Comment by kof** [comment]
If both are using react-jss you don't need insertion points, because they are managed from the same place. 

Your problem is that you are using 2 different react-jss versions.

**Comment by robhung** [comment]
How can I combine the 2 different `react-jss` versions into the same one?
