### ISSUE TITLE
Same className

### ISSUE THREAD

**Issue by kserjey** [cssinjs/react-jss#105]
Is it normal behavior? In this screenshot I have DateTimeInput component, which have root class ```dateTimeInput``` and rendered two times on the page.

![image](https://user-images.githubusercontent.com/19753880/27643899-04380a4e-5c2b-11e7-874b-ad232a2150dd.png)

**Comment by kof** [comment]
If you are rendering the same component multiple times on the page, it reuses the same style sheet. Thats the expected behavior. 

Why are you asking? Do you have an issue?

**Comment by kserjey** [comment]
Sorry, I was confused by dynamic styles, 'cause they have diffrenet classNames. Thank u for quick response, close this issue.
