### ISSUE TITLE
getDynamicStyles

### ISSUE THREAD

**Issue by kserjey** [cssinjs/react-jss#106]
Can u add ability to import ```getDynamicStyles``` from react-jss module?

**Comment by kof** [comment]
Why?

**Comment by kserjey** [comment]
We can import getDynamicStyles from jss module, but not from react-jss module and when i want to test functinal values i should add one more dependency to package.json and one more import statement just for one function.

**Comment by kof** [comment]
No, why do you need getDynamicStyles function?

**Comment by kserjey** [comment]
I want to create the function which will create the styles from functional values and after that i will test the result.

**Comment by kof** [comment]
So basically you want to test  a css generated by a react component, right?

**Comment by kserjey** [comment]
Yep

**Comment by kof** [comment]
Then what you want is a function that returns a final CSS generate by a component in particular state. You want to render a component and get the snapshot of its CSS. Thats why I created #93. Lets continue this conversation over there.

**Comment by kof** [comment]
I added an example over there. In case you are wondering why dynamic sheets are not there - its a bug. Try the 7.0.0-pre version, it has it fixed.
