### ISSUE TITLE
variables in JS styles

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/react-jss#109]
I've noticed that some frameworks like [emotion](https://medium.com/@tkh44/emotion-ad1c45c6d28b) support dynamic css styles controlled by props.  I'm not 100% sure if I think it's a good idea though (I tend to use inline styles for anything dynamic).  Out of curiosity though, do you have any plans to support dynamic styles in `react-jss`?

**Comment by kof** [comment]
what do I need to support? those are just css props.

**Comment by jedwards1211** [comment]
@kof what I mean is something akin to
```js
injectSheet(props => ({
  root: {
    borderRadius: 4,
    backgroundColor: props.color,
  }
})(MyButton)
```
That will automatically update `root`'s `background-color` rule whenever `props.color` changes.

**Comment by jedwards1211** [comment]
@kof ...nevermind, I had never seen the way to do this in the README, maybe it's new :)

**Comment by kof** [comment]
Custom props are supported per se. What emotion seems to do is to allow extract a fully static css file  and use custom variables to support dynamic values. https://github.com/tkh44/emotion/blob/master/docs/extract-mode.md

**Comment by kof** [comment]
As IE11 doesn't support custom props, I am not sure of usefulness of this.

**Comment by kof** [comment]
Also it is quite opinionated to assume that all dynamic props should be converted to css variables. What if I want to mix css variables and function values?

**Comment by kof** [comment]
I think its just a half backed experiment.

**Comment by jedwards1211** [comment]
I see, I hadn't looked into the details but I wasn't jumping to the conclusion that I should use emotion.  I didn't realize that `backgroundColor: props => props.color` was possible in `react-jss` though, so I'm glad it is!

**Comment by jedwards1211** [comment]
I also find JS objects more convenient to work with than string templates.  Some of these frameworks do make me wonder whether some kind of compile-time performance enhancement is possible with JSS.

**Comment by kof** [comment]
totally, we are working on it https://github.com/cssinjs/istf-spec

**Comment by jedwards1211** [comment]
@kof wow, that's awesome!

**Comment by jedwards1211** [comment]
@kof are there plans to support variable or function interpolation in it though?  I ask because it seems like some of these frameworks like emotion compile down to some format that's efficient but still dynamic.

**Comment by kof** [comment]
yes, also emotion will use istf in the future.
