### ISSUE TITLE
Props and state available to rule function

### ISSUE THREAD

**Issue by damianobarbati** [cssinjs/react-jss#112]
In the example in the README we're accessing the props: is it possible to access component state too?

```
import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';
import injectSheet from 'react-jss'

const styles = {
    root: {
        background: props => props.background //can I access state too somehow?
    },
}

@injectSheet(styles)
export default class Component extends React.Component {
    static propTypes = {
        classes: PropTypes.object.isRequired,
    }

    render() {
        const { classes } = this.props;

        return (
            <div>
                <h1 className={classNames(classes.root)}>Admin!</h1>
            </div>
        )
    }
}
```

**Comment by kof** [comment]
Seems like a valid enhancement.

**Comment by kof** [comment]
The only implication here is that fn values will be that on each setState react-jss will need to update the dynamic sheet and call all the function values. Depending how much of them are defined it may be an overhead.

**Comment by iamstarkov** [comment]
@damianobarbati what is your use case for this feature request?

**Comment by iamstarkov** [comment]
it will be breaking change btw

**Comment by damianobarbati** [comment]
@iamstarkov I'm strictly using redux so I will always find anything in `props` anyway: but in case a component is using locale component state for rendering it may be useful though.
In my quick test case I was binding an `input` value to background color just for fun and I noticed... I couldn't xD.

@kof just tried the 7.x and it seems to work flawlessly: this was fast!

**Comment by iamstarkov** [comment]
@damianobarbati nice =)

**Comment by iamstarkov** [comment]
one things to do is use Component's state to as props to its children component, and use those props in jss

**Comment by iamstarkov** [comment]
we can access state on `Component` instance, but in order to react on it we need either `componentWillUpdate` or `componentDidUpdate`, or maybe even `render`. but that would involve callback being passed from `injectSheet` to `Component` which in turn is supposed to be invoked in Component's lifecycle methods. I guess its quite an error prone way

**Comment by iamstarkov** [comment]
@kof what do you think?

**Comment by kof** [comment]
Right now using parent component state and passing it as props to the child where styles will be used is possible. It requires though that one needs to create a separate component and pass the state over props. Accessing state directly would simplify the logic. I am not sure though about the cost. There is another issue with that. As of right now all other libraries pass props only as far as I know. This change would remove compatibility and add another obstacle for ISTF.

**Comment by rob2d** [comment]
I am also running into some bloat while trying to do animation sequences. In some cases where you have an outside controller component and then another inside component with its own state, it requires 2 levels of indirection. It can be quite a bit of overhead 😐

**Comment by rob2d** [comment]
(this is somewhat avoidable, but in many cases it can lead to less cohesive component designs)

**Comment by kof** [comment]
@damianobarbati @rob2d can you create a demo on webpackbin of a use case which was the reason originally for this issue. Maybe I can think of other ways to allow it without passing state.

**Comment by damianobarbati** [comment]
@kof I have no quick snippet right now to serve as example, my use-case when I posted this was for two scenarios I was dealing with:
- an input value changes a css-prop realtime (background color? input => state)
- I have a horizontal scrollable container and I have to set its width properly once loaded what menu entries the user did enable (database => state)

Since I'm using redux both looks solved since I'll have everything as props but I still have to try again: I'll face the latter soon.

**Comment by kof** [comment]
I think we a

**Comment by damianobarbati** [comment]
Got it.
It's funny, I was looking for this right yesterday 😂
Use case: setting the height of an element dynamically fitting the rest of the viewport, `componentDidMount` run the logic on the root DOM element and a state variable with the height.

**Comment by kof** [comment]
you can move that to a child component, so that your components state can be passed down to it over props, right?

**Comment by damianobarbati** [comment]
Definitely, I'm already using this approach elsewhere but sometimes it's better stick to classic state+style to not bloat the codebase in vain.
Thanks @kof!
