### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#118]
- [ ] Reset by deleting require.cache is ugly, we need to remove that.
- [x] We need to split the file. Right now tests are mostly integration. I think it makes sense to create a tests dir and split the index based on use cases.
- [ ] If we can avoid the need for DOM tests, we can switch to jest and remove karma completely.

**Comment by iamstarkov** [comment]
We can avoid DOM manipulations completely if in tests we would use SheetsManager without DOM interactions

**Comment by kof** [comment]
Restructured tests, now they are much more readable, because in separate files. Other points still need to be done.

**Comment by HenriBeck** [comment]
Will be tracked here: cssinjs/jss#745
