### ISSUE TITLE
Maximum call stack size exceeded at cloneStyle

### ISSUE THREAD

**Issue by totocap** [cssinjs/react-jss#120]
Hi !
I'm trying to have dynamic style by using React-jss. The idea is to have a default style that can be changed by calling a method.

I simplify my code to get this code :
```jsx
import React from 'react';
import injectSheet from 'react-jss';
import {jss} from 'react-jss';

const globalSheet = jss.createStyleSheet({
    paragraphClass: {
        color: 'blue'
    }
});

const updateColor = (c) => {
    globalSheet.addRule('paragraphClass', {color: c});
};

const BlueParagraph = injectSheet(globalSheet)(
    ({classes}) => (
        <p className={classes.paragraphClass}>I'm a paragraph.</p>
    )
);

const App = () => (
    <div className="App">
        <BlueParagraph/>
        <div onClick={() => updateColor('green')}>Green</div>
        <div onClick={() => updateColor('blue')}>Blue</div>
    </div>
);

export default App;
```

When I execute it, I get an error : Maximum call stack size exceeded at cloneStyle.
![error](https://user-images.githubusercontent.com/10602197/28310302-59935e90-6bac-11e7-903e-22c8fe99d2f8.png)

Do you have a clue of what I did wrong ?

Thanks,
Thomas.

**Comment by kof** [comment]
What version of react-jss are u using? We removed from the version 7 the ability to accept StyleSheet instance in injectSheet() function. It has caused too many issues. You can use function values to update the CSS values dynamically http://cssinjs.org/json-api?v=v8.1.0#function-values
