### ISSUE TITLE
Add styles to html and body

### ISSUE THREAD

**Issue by patrickml** [cssinjs/react-jss#127]
How would I add styles to html and body?

**Comment by iamstarkov** [comment]
What do you mean? React-jss takes care of that and adds style sheets into `<head>`

**Comment by kof** [comment]
You can specify a custom Jss instance and use an [insertionPoint](http://cssinjs.org/setup?v=v8.1.0#specify-dom-insertion-point)

**Comment by typical000** [comment]
Maybe author mean how to apply styles to html or body tags? :)
You need to use jss-global - http://cssinjs.org/jss-global?v=v2.0.0

**Comment by kof** [comment]
maybe)

**Comment by iamstarkov** [comment]
ouch, maybe

**Comment by iamstarkov** [comment]
then yes, jss-global is a way to go

**Comment by patrickml** [comment]
Lols sorry I really should have been more detailed. @typical000 is correct I was asking about how to style the body and HTML tag. Thank you guys. I believe that global plugin is what I am looking for.

**Comment by kof** [comment]
jfyi its already part of default preset and react-jss and styled-jss
