### ISSUE TITLE
JssProvider: wrong rerender logic

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#128]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

I think that the `JssProvider` should only be calling `createGenerateClassName()` if the jss instance is different.
The current logic is calling it at each render of the `JssProvider`.
I have noticed that behavior with https://github.com/callemall/material-ui/issues/7538.
The issue can only be seen in production as we map directly the internal index to a class name, it do no longer work with x internal index.

**Comment by kof** [comment]
We need to reset counters for each request, right? This is what JssProvider is doing. Jss instance is shared across requests, but class names are fresh.

**Comment by oliviertassinari** [comment]
We are no using `JssProvider` for server side consideration, but for customizing the jss instance.

**Comment by kof** [comment]
Ah so you are talking about client-side usage. You are rendering JssProvider more than once?

**Comment by kof** [comment]
I agree, on the client, it should be called just once.

**Comment by oliviertassinari** [comment]
Yes, I have noticed the issue in a situation where the `JssProvider` was rendering more than once: [here](https://github.com/zeit/next.js/blob/051ee314e9169c503b7031aaa720ac93fa493598/examples/with-material-ui-next/pages/index.js) (App render JssProvider internally)

**Comment by kof** [comment]
This issue should be fixed in v8
