### ISSUE TITLE
sheetsManager: option to inject a custom sheetsManager

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#129]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

Material-UI went with a different implementation of the `sheetsManager` in order
to better support nested theme (a WeakMap).
I wish we were able to provide the `sheetsManager` through the `JssProvider`.
Right now, Material-UI is providing through the `MuiThemeProvider`. I don't think that it should be the theme provider responsibility.

**Comment by kof** [comment]
I think sheet manager in mui and the one from jss package are very different. Lets use very specific use cases as a way to communicate the need. Its much easier to think in this perspective.

**Comment by oliviertassinari** [comment]
The main difference between the Material-UI `sheetManager` and the react-jss is the following "inversion".
react-jss create a `sheetManager` per sheet and then handle each `theme`

**Comment by oliviertassinari** [comment]
That's the most important difference between react-jss and Material-UI.
Material-UI is using a single SheetManager, that's already one important difference with react-jss that use many when it's not provided by the context.
I have to admit that my original motivation for writing a new one was around not understanding the original code, I would like, "does that work by chance?" So I wanted to write something simple, that I could understand and make sure it had no leak.

**Comment by kof** [comment]
What can be done in such cases: 

- request for inline documentation in specific places
- add tests

**Comment by kof** [comment]
I think we have an issue on ssr with the current approach, the first point https://github.com/cssinjs/react-jss/issues/133 describes it. I think you simple want to have it fixed instead of an option for a custom sheets manager.
