### ISSUE TITLE
injectStylesheet: detach static sheet from the sheet registry when needed

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#131]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

Right now, a static sheet is never removed from the sheet registry.
I have been using that feature for testing and demo purposes on Material-UI.

**Comment by kof** [comment]
Sheets registry remains forever on the client, but on the server user passes a new registry for each request.

Are you talking about the client side rendering? Why is that a problem?

**Comment by oliviertassinari** [comment]
Here is an example of demo application of the detach on the client: [sheet-registry](https://material-ui-1dab0.firebaseapp.com/customization/css-in-js#sheet-registry). If you switch the ligh/dark mode you will see the counter change.

**Comment by oliviertassinari** [comment]
I think that it's just a matter of safety, things need to be cleanup in case.

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#808
