### ISSUE TITLE
injectStylesheet: merge user classes property

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#132]
This issue is part of a series of feedbacks. [I been upgrading the Material-UI solution](https://github.com/callemall/material-ui/pull/7461).
Unfortunately, I had to fork the package in order to reach my goal.
Now, it's time to reconciliation.

### The issue

Regarding that issue, I don't know if that fit with the vision of the project. I'm opening it in the doubt.
So, I'm suggesting to implement the `classes` property logic of Material-UI in react-jss.

**Comment by kof** [comment]
@oliviertassinari can you please elaborate with more detail?

**Comment by oliviertassinari** [comment]
Here is the [Material-UI case](https://material-ui-1dab0.firebaseapp.com/customization/overrides#overriding-with-classes) for the classes property.
That's always something that Material-UI could build on top of createHOC.js

**Comment by kof** [comment]
Can't see whats special in mui in this regard. Does it simply allow to override classes object by user props? If so we already support this.

**Comment by oliviertassinari** [comment]
@kof, it's not a simple override. Instead, we merge the keys.

**Comment by kof** [comment]
Q: the merge you do in mui, would it override user component class names if they match? or it acts like a `defaults` function?

**Comment by oliviertassinari** [comment]
We merge them. We don't override it.

**Comment by kof** [comment]
Yes, but what direction does merge goes: merge(HocClasses, ChildClasses) or the other way around?

**Comment by oliviertassinari** [comment]
Does it matter? We concatenate the classe names.

**Comment by kof** [comment]
Oh so you merge not just the objects, you merge the class names strings!

**Comment by oliviertassinari** [comment]
Yes indeed :).

**Comment by kof** [comment]
1. Create a classes object and put it into instance
2. Merge in classes strings from the dynamicSheet | sheet
3. Merge in classes strings from props.classes

**Comment by jedwards1211** [comment]
@kof how would this behave if `defaultProps.classes` are copied from the wrapped component though?  Wouldn't the classes strings from `defaultProps.classes` still end up overwriting the strings from the `dynamicSheet | sheet` (assuming I don't specifically pass `classes={{...}}` when I create an instance of the wrapper?)

**Comment by kof** [comment]
Actually I was going to merge classes always. So it would be always consistently merged.

What bad can happen if `props.classes` will be merged with your default classes where you wanted them to be used only if JSS HOC was not used?

```javascript
classes = {
  button: 'default-class-name generated-class-name'
}
```

**Comment by kof** [comment]
Can't think of anything bad if we merge UserComponent.defaultProps.classes same way we merge classes passed to the hoc. 

If user uses default classes, he will also be able to remove those default styles from the CSSOM if it is a problem, class name which has no css rules doesn't do anything.

**Comment by kof** [comment]
After some consideration I decided to not merge class strings for now. The reason mui merges them is because the components are useless otherwise. Here, it might be an unexpected and unwanted behaviour since react-jss component might be a lower level one and user might want to fully override class names.

@jedwards1211 default classes merge works as you expected

Released v8

**Comment by jedwards1211** [comment]
@kof I forget where else we discussed this, but I wanted the inner component's `defaultProps.classes` **not to ever get merged by `injectSheet`**.  Are you saying they do get mereged in some case?
