### ISSUE TITLE
JssProvider enhancements

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#133]
-  [x] 1. Do NOT save manager in the scope. Async requests will use it because injectSheet() is called just once.
- [x] 2. Warn when JssProvider is used inside of JssProvider (use context). Update: no need, see https://github.com/cssinjs/react-jss/issues/157#issuecomment-333576671
- [x] 3. No JssProvider - no styles. For this we can pass jss from Provider, no jss no styles. This can be used legally in order to render components without styles for e.g. in order to resolve some async  deps on the server. Warn on the client if no JssProvider is used.
- [x] 4. Use registry object instead of random providerId to identify the same request
- [x] 5. Add a bold hint in readme to NOT use 2 JssProviders in parallel for one request in separate contexts, because it will result in conflicting class names???? We need to research if there are use cases for a strong need of multiple parallel JssProviders. If there are, we need to think of something to support it. Update: we just found a [valid use case](https://github.com/callemall/material-ui/issues/8223#issuecomment-331081785)

    - [x] add generateClassName prop 
    - [x] add classNamePrefix prop

**Comment by oliviertassinari** [comment]
2. 💯 
5. I have noticed a similar issue on the Material-UI side, where people have conflicting class names. I haven't had the opportunity to dig into it. My point is just that counter base solution is more challenging to get right 😬 .

**Comment by tiagoroldao** [comment]
Regarding 5 - I'm running into an issue where multiple contexts are unavoidable and break stuff: Atom view development (in particular for use in panels - i.e. specific file type editing)

When opening/closing everything is fine, but when multiple tabs are open they are essentially separate apps with separate contexts within them, and the manager breaks.

**Comment by tiagoroldao** [comment]
A couple of questions to see if I understand this project better and can propose solutions:
- why does JssProvider provide a providerId to the context, but not a manager?
- using providerId, could the "static" var `manager` in `createHoc` become a map of providerId's to managers?

**Comment by kof** [comment]
For SSR, we need to identify a new http request. Provider is rendered only once at each request, thats how we identify requests.

Manager is responsible for handling sheets of one component. It makes sure a static sheet is reused across all component instances. Also it is used to ensure that components which use the same theme use the same sheets, but not different themes.

**Comment by tiagoroldao** [comment]
Two possible solutions to 5:

**Comment by tiagoroldao** [comment]
Two possible solutions:
- have JssProvider supply a manager in context. A component defines a manager if it doesn't have a contextual one, and if it is within a context with a manager, uses that.
  - Possible issues: there are possible interactions between components that I am overlooking, possibly due to not understanding what they are supposed to do
  - Findings - all tests pass with current code changes, might PR for you to look at
- have Components keep an array of managers, rather than a single one, and create a manager per context
  - Possible issues: possibly memory leaks? Would need to make sure they get disposed of properly, as they would continue to exist in the array after context is destroyed/changed

**Comment by kof** [comment]
generateClassName prop released with 7.2.0

**Comment by kof** [comment]
I am going to enforce using JssProvider on the server and the client for consistency. cc @oliviertassinari @iamstarkov

**Comment by oliviertassinari** [comment]
> Warn when JssProvider is used inside of JssProvider (use context).

I have found a use case for using two nested JssProvider. One to collect the styles on the server and another one to configure jss (next.js) 

> I am going to enforce using JssProvider on the server and the client for consistency. 

I also have a use case for only using JssProvider on the server (next.js)

**Comment by kof** [comment]
> I have found a use case for using two nested JssProvider. One to collect the styles on the server and another one to configure jss. You only want to collect the server side generated style (next.js).

Can it be one and the same provider?

**Comment by kof** [comment]
> I also have a use case for only using JssProvider on the server (next.js)

Would it be a problem if you have JssProvider on the client as well?

**Comment by oliviertassinari** [comment]
> Can it be one and the same provider?

No, it's a next.js contrainte.

> Would it be a problem if you have JssProvider on the client as well?

Having one on the client mean having two on the server. Unless you add most logic to handle it with next.js

**Comment by kof** [comment]
Released v8
