### ISSUE TITLE
Allow themeListener with custom channel

### ISSUE THREAD

**Issue by catalin-enache** [cssinjs/react-jss#135]
Hello react-jss team,

I have the following Scenario:

Lib A uses ```react-jss``` for its UI components.
Lib B uses ```react-jss``` for its UI components.
Dev X wants to use a component from lib A and a component from lib B using different ```ThemeProviders```.

As react-jss currently uses ```themeListener``` straight from ```theming``` (which channel defaults to ```__THEMING__ ```) is not possible
for lib A and lib B to choose their custom channel.

If this would be possible we could have something like:

```
<ThemeProviderA>
  <ThemeProviderB>
    <LibAComponent/>
    <LibBComponent/>
  </ThemeProviderB>
</ThemeProviderA>
```

What do you think of allowing ```injectSheet``` to have as a third param the ```themeListener``` which should default to ```themeListener``` from ```theming``` ? Then ```injectSheet``` passes down ```themeListener``` to ```createHOC```.

This way lib A and lib B could setup their ```ThemeProviders``` and ```themeListeners``` with custom channels by using ```createTheming('__LIB_A_THEMING__')```, ```createTheming('__LIB_B_THEMING__')``` from ```theming``` package, then they can pass inside ```injectSheet``` the custom ```themeListener``` resulted from calling ```createTheming``` function.

Thank you.

**Comment by kof** [comment]
Yeah, sounds like a reasonable request.

**Comment by catalin-enache** [comment]
Hello @kof, thank you for feedback.
I created a branch on my local machine for this feature ( + unit-test)
The changes are as suggested in my comment.
I'd like to push it for review somehow.
How can I do it without pasting the diff here
which would make this thread super long and unreadable ?
Thank you.

**Comment by kof** [comment]
How about a pr?

**Comment by catalin-enache** [comment]
Hi @kof,
I forked react-jss and created a PR from the fork:
https://github.com/cssinjs/react-jss/pull/136

For whatever reasons the build failed:
"No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)"

However, before pushing the PR I ran "lint" and "test" and they were successful.

**Comment by iamstarkov** [comment]
@catalin-enache we dont have configured travis right now, so no worries

**Comment by kof** [comment]
this has been published

**Comment by catalin-enache** [comment]
Already using it. Thank you.
