### ISSUE TITLE
Better rehydration for server-side renders

### ISSUE THREAD

**Issue by TiddoLangerak** [cssinjs/react-jss#137]
The current recommended approach for rendering server-side is to inject the server-side generated styles into the template, and remove that after mounting the app. However, removal of a stylesheet causes browser to re-calculate the style of the entire page.

This can be avoided if react-jss would be able to detect pre-loaded styles, and only inject missing sheets (which ideally is no sheet at all).

For an artistic impression, what I would want is something like this:

```js
//server-side
return res.send(renderToString(
<html>
  <head>
    { sheets.asStyleTags() }
  </head>
</html>
```
which renders to:
```html
<html>
  <head>
    <style type="text/css" data-jss="" data-meta="Jss(MyComponent)">/* snip */ </style>
    <style type="text/css" data-jss="" data-meta="Jss(MyOtherComponent)">/* snip */ </style>
  </head>
</html>
```
and then react-jss could detect such existing tags on startup and re-use them.

**Comment by kof** [comment]
> However, removal of a stylesheet causes browser to re-calculate the style of the entire page.

Not if you remove them after you mounted the app as the docs says. I know what you are suggesting, but this has lots of complications.
