### ISSUE TITLE
Duplicate Sheets Injected - Memory Leak

### ISSUE THREAD

**Issue by bhuffman** [cssinjs/react-jss#139]
I'm seeing the same style sheet definitions getting injected over and over into the DOM, which is causing a pretty serious memory leak. I'm not even worried about cleanup on component unload, just want to avoid having thousands of repeated css sheets.

I'm using a few different variations of withTheme, but nothing seems to be doing a duplicate check before injecting. 

<img width="588" alt="screen shot 2017-08-09 at 6 31 33 pm" src="https://user-images.githubusercontent.com/183801/29150788-9f8ace42-7d31-11e7-8220-05cda1ef1f47.png">
<img width="588" alt="screen shot 2017-08-09 at 6 31 12 pm" src="https://user-images.githubusercontent.com/183801/29150789-9f8b1550-7d31-11e7-83c3-b4cfb7176e2d.png">
<img width="925" alt="screen shot 2017-08-09 at 6 39 16 pm" src="https://user-images.githubusercontent.com/183801/29150869-3a3efd0a-7d32-11e7-9693-d1d092461add.png">

**Comment by iamstarkov** [comment]
duplicate check is happening in `SheetsManager` https://github.com/cssinjs/jss/blob/master/src/SheetsManager.js#L37.

**Comment by iamstarkov** [comment]
and btw, you dont need to use withTheme, you can define your styles with `stylesCreator` notation, where your `styles` are the function with `theme` as an first and only argument

**Comment by iamstarkov** [comment]
pls rewrite it this way and share results

**Comment by iamstarkov** [comment]
also pls note that sheetsManager and themed styles creator is available since react-jss 7+

**Comment by bhuffman** [comment]
This approach fixed the duplicate issue. Sadly, is a huge change to our application, but worth it for the performance boost.
