### ISSUE TITLE
Passing in an instance of jss

### ISSUE THREAD

**Issue by avivash** [cssinjs/react-jss#141]
Hi,

I'm wondering if there is any way in version `7` to still pass in your own instance of `jss`.

I'd like to upgrade, but my project is still using version `6` and I'm using the `create` method, which no longer exists.

This is my current code:
```
import { create as createJss } from 'jss';
import { create as createInjectSheet } from 'react-jss';

const jss = createJss(preset());

jss.use(isolate({
  isolate: true,
}));

const injectSheet = createInjectSheet(jss);
```

I'd like to incorporate the features of version `7` to namespace my classes, but I'm not sure how to do that and still use my own instance of `jss`.

Thanks

**Comment by kof** [comment]
https://github.com/cssinjs/react-jss#custom-setup

**Comment by avivash** [comment]
@kof thanks for the quick reply. I'm currently using a custom theming solution that doesn't work with the implementation you linked to, but I think it's time I refactor my solution.

**Comment by kof** [comment]
Yeah, we got theming now. As a hot fix you could use jss instance from the context within your theming, you need to grab the namespace used on the context from react-jss package namespaces module.

**Comment by kof** [comment]
https://github.com/cssinjs/react-jss/blob/master/src/ns.js

**Comment by avivash** [comment]
ahh nice! I'll look into that. thanks
