### ISSUE TITLE
If attribute value is a function returning `!important` it transforms to `false`

### ISSUE THREAD

**Issue by mistadikay** [cssinjs/react-jss#142]
Hey,

Before describing the issue let me tell you a bit of a background, so it will be clear why `!important` is used in the first place.

We're working on embeddable widgets that can be included into our clients websites. Every client has a unique configuration where we specify various options including theming. Some websites use `!important` in their css and it affects our widget styles. The only way to override `!important` is by using another `!important` (I'm writing and crying now), but we don't want to put it on every attribute value by default because we will go to hell for that. So what we did is made a possibility to override certain values in theming configuration on a case-to-case basis.

For example (oversimplified case): the input in our widgets, has `color: ({ theme }) => theme.color`. Our default `theme` looks like this `{ color: '#f00' }`.

The website we're putting our widgets on has `input: { color: '#000 !important' }` in their css. So they will override our amazing red color. In order to solve this we override `theme` in configuration to `{ color: '#f00 !important' }`. But when stylesheets are appended instead of `#f00 !important` there is... `false`. 😐 Which is awkward.

Here is reproducible isolated case:
https://www.webpackbin.com/bins/-KrlDTFL8FtibtlIfHc4

I understand that it might be a rare and specific use-case, but maybe I'm doing something wrong or there is an explanation for such behavior. Thanks.

**Comment by kof** [comment]
Its a pretty common case for embeddable widgets. I would write a plugin to auto add !important to each value.

**Comment by kof** [comment]
So an actual bug is that if using function values and value has !important it renders a false. It is actually not related to react-jss nor is the story why you use important is relevant here as far as I can see.

**Comment by kof** [comment]
Issue moved to [cssinjs/jss #565](https://github.com/cssinjs/jss/issues/565) via [**ZenHub**](https://www.zenhub.com/)
