### ISSUE TITLE
computed theme [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [cssinjs/react-jss#143]
Right now the theme is just a container object: would it be possible to add jss capabilities to it as well?

```
const headerHeight = '30px';

const theme = {
    scrollableBody: {
        height: `calc(100vh - ${headerHeight}`,
        overflowX: 'auto',
        overflowScrolling: 'touch',
        '&::-webkit-scrollbar': {
            display: 'none',
        },
    }
}

const styles = theme => ({
    root: {
        extend: theme.scrollableBody,
    }
})
```

I know this can be easily achieved through spread-operator but this was a simplified case: I have far more complex rules I could put in the theme and use everywhere and having theme all in the theme object seem more appropriate then manually importing tons of jss files on top of every component and manually merge theme. 
What do you think @kof? 🤔

**Comment by iamstarkov** [comment]
theming itself doesn't prohibit this stuff, and in my opinion react-jss, shouldnt prohibit you to do so. lets ask @kof.

one immediate though is that its bad approach, as far it is very close to global styles. have you tried to keep those style helpers separately and import and use them directly wo/ theming?

**Comment by kof** [comment]
Theme is not styles, theme is constants you can use to build styles.

**Comment by kof** [comment]
Despite its a bad idea, I don't see why what exactly is the problem here. It should work already.

**Comment by damianobarbati** [comment]
Wait: there's no global styles here. Nothing is attached because of theme.
If you have a computed rule in theme you always have to either:
1. extend: [theme.rule] 
2. myRule: ...theme.rule //rule is a set of key:values
3. myRule: { key: theme.rule } //rule is a value

**Comment by kof** [comment]
It is not global in the sense CSS classnames are global, but it is global because you can use them in any component. So how will you know what is used where? And what will break if you change it?

**Comment by damianobarbati** [comment]
@kof I see: better avoid this kinda approach 👍🏻
Even the most used and constant classes/rules should be computed in every single component using it

**Comment by kof** [comment]
You can avoid unnecessary computation by proper caching.
