### ISSUE TITLE
Using props results in multiple duplicate classes.

### ISSUE THREAD

**Issue by MikeBarnhardt** [cssinjs/react-jss#144]
Assuming that I'm doing it wrong or this is expected behavior.

When I use a callback for a property:

```
export default theme => ({
  button: {
    backgroundColor: props => props.color,
  },
});
```

I get multiple classes for button `console.log(props.classes)`:
```
{
  button: "button-0-31 button-0-22",
}
```

But when the page renders only a single of the classes is available such as "button-0-22".

Everything *works* fine, I just find it odd that there are multiple classes which are unused or rendered to the page.

**Comment by kof** [comment]
You seem to be doing all right, but what does this mean?

> But when the page renders only a single of the classes is available such as "button-0-22".

**Comment by MikeBarnhardt** [comment]
You would expect to find `.button-0-31` and `.button-0-22` in either the inspector's styles or in the document `<head>`, but only `.button-0-22` exists. Here are some screenshots doing the same thing (`Column` instead of `Button`):

----

You can see multiple classes are rendered:

![screen shot 2017-08-25 at 12 17 21 pm](https://user-images.githubusercontent.com/2816413/29722710-cf5cfa04-898f-11e7-8fb9-542d6aba70f0.png)

----

But the inspector only sees one of them:

![screen shot 2017-08-25 at 12 17 30 pm](https://user-images.githubusercontent.com/2816413/29722712-d46801ec-898f-11e7-9f82-3109501abf3b.png)

----

It's missing from any of the relevant `<style>` tags:

![screen shot 2017-08-25 at 12 19 19 pm](https://user-images.githubusercontent.com/2816413/29722717-d664eb90-898f-11e7-8a72-f8fd40f97b43.png)

**Comment by kof** [comment]
So the problem is that you don't see that css rule in the style tag, right?

**Comment by MikeBarnhardt** [comment]
I'm really asking if this is a problem, I guess. I just find it strange to have multiple classes generated and then it doesn't use them 😅 .

**Comment by kof** [comment]
If it doesn't use them, why is it working as expected? 

It think you just got trapped into the fact that insertRule CSSOM API which is used for dynamic styles is not visible in style tag text content representation, you need to go into style.sheet.rules to see it or to see it applied on the element in the styles panel.

**Comment by MikeBarnhardt** [comment]
Thank you

Keep up the good work 👍

**Comment by Mati365** [comment]
@kof But that duplication sucks in SSR mode. For example if we want to create Grid.Column class using dynamic props doing something like it:
`baseClass: props => ({width: `$(props.size * 100)%`})`

and calling it like it:
```
<Grid size={1/10} />
<Grid size={1/10} />
<Grid size={1/10} />
<Grid size={1/10} />
<Grid size={1/10} />
```
react-jss will produce 5 classes with the same style, yes?

**Comment by HenriBeck** [comment]
Yes, that's correct.

**Comment by kof** [comment]
yeah, that can be optimized potentially https://github.com/cssinjs/jss/issues/501
for now you could generate the class in a parent component and pass it to all children

**Comment by Mati365** [comment]
@kof wow, thx for fast reponse! So for now it will be faster to not use dynamic classes in heavly exploated components. When do you want to introduce suggested feature?
