### ISSUE TITLE
JssProvider broken when it updates from setState

### ISSUE THREAD

**Issue by SerjoPepper** [cssinjs/react-jss#147]
For example
```
class MyComponent {

  onClick() {
    setState({ ... })
  }

  render() {
    return <JssProvider></JssProvider>

  }
}
```

The reason is that you create `providerId` and `createClassName` any time when context is requested.

![image](https://user-images.githubusercontent.com/191823/30090051-8480a052-92b9-11e7-8dbd-c0a43252843e.png)

I think it would be better when JssProvider caches this instances inside.

```
export default class JssProvider extends Component {

  ...

  getChildContext() {
    let createGenerateClassName = createGenerateClassNameDefault
    const {jss: localJss} = this.props
    if (localJss && localJss.options.createGenerateClassName) {
      createGenerateClassName = localJss.options.createGenerateClassName
    }
    if (!this.generateClassName)
      this.generateClassName = createGenerateClassName()
    if (!this.providerId)
      this.providerId = Math.random()
    return {
      [ns.sheetOptions]: {
        generateClassName: this.generateClassName
      },
      [ns.providerId]: this.providerId,
      [ns.jss]: this.props.jss,
      [ns.sheetsRegistry]: this.props.registry
    }
  }

  render() {
    return Children.only(this.props.children)
  }
}
```

**Comment by kof** [comment]
It is designed to be used no a very top level and actually never update. Pease send me a documentation pr to make it more clear.

**Comment by kof** [comment]
So the reason we can't cache it is that we use update of this component as an indication of server side rerender. Basically when a new request comes in.

**Comment by SerjoPepper** [comment]
As I know, you suggest to create JssProvider for each new request
```
renderToString(
    <JssProvider registry={sheets}>
      <MyApp />
    </JssProvider>
  )
```
Sorry for my stupidity, but I can't understand how it deals with server side `rerender`.
Also the reason is JSS can cache providerId, that developers can create standalone components packed with own JSS (for example Datepicker).

**Comment by kof** [comment]
Is there a RErender on the server? or just render?

**Comment by SerjoPepper** [comment]
I render on server and then rerender on client (creating new instance of JSS provider).

**Comment by kof** [comment]
Can you provide a reproducible example on a playground?
