### ISSUE TITLE
Generate single style.css in production

### ISSUE THREAD

**Issue by williammanco** [cssinjs/react-jss#150]
It's possible to generate **single static css file** of all css-in-js component?

I don't understand if is possible, on the [Michele Bertoli repo's](https://github.com/MicheleBertoli/css-in-js), the react-jss is flagged on **_"Extract CSS File"_** but it's possible only running application on server like a SSR app? 
or exist a trick to generate static css file?

Thanks to all and sorry for confiusion
W

**Comment by kof** [comment]
You can do that right now if you put styles in separate files. For the case where you put them into the file with component, I created a separate issue https://github.com/cssinjs/jss/issues/579

**Comment by kof** [comment]
Converting from separate files is as simple as walking/finding the files on the file system and using jss.createStyleSheet(style).toString() to get the CSS string.
