### ISSUE TITLE
Please provide type definition file for typescript.

### ISSUE THREAD

**Issue by kishoreiiitn** [cssinjs/react-jss#151]
Cannot find definitions at types/react-jss

**Comment by kof** [comment]
I am happy if someone does this.

**Comment by WillLuce** [comment]
Now that Material-UI v1 is out and leans on cssinjs, this request is going to come up more and more.

**Comment by codler** [comment]
Yes please, VS Code is nagging.
```
[js] Cannot invoke an expression whose type lacks a call signature. Type 'typeof "./node_modules/react-jss/lib/index"' has no compatible call signatures.
```

**Comment by kof** [comment]
I am going to close this, since typings for type script is a separate project and should go directly to the definitely typed repo.

**Comment by estaub** [comment]
@kof, fwiw, ignore if annoying...
Type definitions are often maintained as part of the source project; having them separate in DefinitelyTyped is a bit of a pain and has scale issues at this point IMHO, given the 4000+ packages there.  

Obviously typescript isn't your cuppa, you're not going to write the defs, but regardless of where located, consider reopening and inviting collaboration on it.  Anyone who does it will probably need some review help; closing it out like this tends to discourage folks.

**Comment by kof** [comment]
I don't know how an open issue would  encourage people writing ts definitions and submit them to definitely typed.  People who need typings and know how to create them already know how to submit it to definitely typed or can also learn it over there. If they have questions we have gitter, twitter, stackoverflow, separate specific issues. I am following everyrthing. 

The way I see issues tracker is a list of things which will be fixed as a part of this repository.

**Comment by kof** [comment]
Btw. I did reviews on definitely typed repo. This is the right place to ask for help by mentioning me, even though I can only answer JSS specific questions, not ts specific.

**Comment by atrauzzi** [comment]
Chiming in as another pro-TS voice.  I'm having to get my hands into JSS for MUI and not having definitions available is forcing me to `any` the library.  Not because I don't want types but because I'm not intimately familiar with it.  That's actually why way nicer to have maintainer/contributors authoring the files.

Ideally typing information is included as part of a package, `@types` packages are the last-ditch, but still require that the library user know the library's internals before the definitions end up being any good.

I'll repeat my usual lame advantages here as I do in other places: It isn't just TS that uses these definition files.  Other strongly typed languages that target JS are starting to leverage the header format.  That and, I mean -- TS is climbing in popularity.  As @estaub mentioned, it may not be your cuppa, but I only see the requests for `.d.ts` files across github increasing.

**Comment by kof** [comment]
We will do it only if we have contributors who are willing to maintain those typings in a timely fashion. We already added flow typings, which means every change requires also updating the typings. If we add ts, as a maintainer or contributor, for every change I will also have to add typings for TS.

Basically you are asking for a feature, but are you ready to maintain it? I am not. In fact I need help with maintenance of many packages in cssinjs org and I am not getting done enough, not even close.

**Comment by marcosanfilippo** [comment]
I din't solve it yet. Which project it is? Is ready or not?

Thx 👍

**Comment by HenriBeck** [comment]
@marcosanfilippo what haven't you solved???

**Comment by marcosanfilippo** [comment]
**Cannot find definitions at types/react-jss**
I'm using typescript with Material UI for React and I need React JSS but no types have been found.

**Comment by HenriBeck** [comment]
Yeah, we haven't found anyone to create those typings. 
Feel free to add them yourself. If you need assistance, mention me or @kof for reviewing the types.

We currently don't have the time nor the experience with TypeScript to supply those.

**Comment by estaub** [comment]
@marcosanfilippo  - If you're using Material-UI v1.*, it has some pretty good types built in that, at least for me, made it unnecessary to use any jss types.  The doc is quite complete; see especially https://material-ui.com/guides/typescript/  .

**Comment by marcosanfilippo** [comment]
@estaub Thanks Ed for your reply. Unfortunately, does not work for me. For example, the
https://material-ui.com/guides/server-rendering/#handling-the-request 

uses the two imports:

```
import { SheetsRegistry } from 'react-jss/lib/jss';
import JssProvider from 'react-jss/lib/JssProvider';
```

And these lack of type definitions. That's my issue.

**Comment by HenriBeck** [comment]
We currently have noone which is willing to maintain the typings (preferably in this repo), but feel free to create a PR to DefenitelyTyped to add the react-jss typings there.

**Comment by estaub** [comment]
@marcosanfilippo Ah, yes, sorry.  I've no help there other than the obvious but unhelpful: add your own def or noImplicitAny:false.
