### ISSUE TITLE
If innerComponent has `defaultProps.classes`, they override `classes` injected by HOC

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/react-jss#152]
I don't really understand why the HOC copies over so much stuff like `defaultProps` and `contextTypes` from the wrapped component instead of just creating a standalone component that renders the wrapped one.  If I have

```js
class MyComp extends React.Component {
  static defaultProps = {
    classes: {
      root: 'MyComp-root',
    }
  }
}

const styles = {
  root: {},
}

export default injectSheet(styles)(MyComp)
```

The created HOC doesn't work because it takes on the `defaultProps` from `MyComp`, so the rendered `classes.root` is always `'MyComp-root'`. 💥 💣

**Comment by kof** [comment]
Current behavior is that if you define your own classes prop, it will override the one passed from the HOC. 

I believe it is a regular behavior that a HOC doesn't overrides anything on the child component.

Though in this particular case with classes we should probably merge them, as there is also another request for this https://github.com/cssinjs/react-jss/issues/132

**Comment by jedwards1211** [comment]
> Current behavior is that if you define your own classes prop, it will override the one passed from the HOC.

I don't think of passing `classes` into an HOC wrapper and declaring `defaultProps` on the wrapped component as the same thing, and neither does `react-redux`:

> I believe this is the regular behavior: a HOC doesn't override anything on the child component.

`react-redux`' `connect`, the mother of all HOCs, doesn't copy `defaultProps` up to the wrapper: https://github.com/reactjs/react-redux/issues/111

I think if anything follows the regular HOC behavior it's `react-redux`.

Here's how I think about this case:
1. `defaultProps` provide values for any props that aren't passed to a component
2. `injectSheet` passes a `classes` prop to its wrapped component
3. therefore a component's `defaultProps.classes` should be ignored when the component is wrapped by `injectSheet`

Is there a *specific problem* that occurs when `defaultProps` aren't copied up to the `injectSheet` wrapper?

**Comment by kof** [comment]
I don't recall EXACTLY what was the reason. I believe it is just convenience, especially when using decorators you want to describe default props within the class itself, not on a HOC.

```javascript
@injectSheet(styles)
class Button extends Component {
  defaultProps = {
    ...
  }
}
```

It might be conceptually not 100% pure. The question is if this causes any serious issues.

Compared to redux connect, injectSheet is used on each component, millions of times, such things start matter at this scale.

**Comment by jedwards1211** [comment]
Without class names getting merged it is a serious issue because the injected classes get completely overridden by `classes.defaultProps`; I work around it by deleting `defaultProps` from the HOC.

With class names getting merged it's not such a serious problem.  But given what a big surprise it was with the current behavior (seeing my default class names on the HOC in the react dev tools made me think "how on earth did they get there?") I'm wary of the smaller surprise of "why are my default class names getting merged with the injected ones?" as well...I know I'm being pretty OCD about this though.

**Comment by jedwards1211** [comment]
I know what you mean about convenience and scale.  A compromise could be `@injectSheet(styles, {copyDefaultProps: true})` and I wouldn't argue about whether that defaults to `true` or `false`.
