### ISSUE TITLE
Refs with JSS components

### ISSUE THREAD

**Issue by sergeyzwezdin** [cssinjs/react-jss#156]
I'm trying to migrate some piece of code to JSS. I have base components library. To style components I use `injectStyles()` as proposed by JSS authors.

The problem is `injectStyles` is just a HOC and I'm unable to use refs with it. Take a look on this snippet:

#### Component1.jsx:

```
class Component1 extends React.Component {
	testMethod() {
		// ...
	}

	render() {
		// ...
	}
}

export default injectStyles(styles)(Component1);
// export default Component1;
```

#### App.jsx

```
class App extends React.Caomponent {
	render() {
		<div>
			<Component1 ref={element => this.component1 = element} 
			/>
			<Button onClick={this.onClick} />
		</div>
	}

	onClick = () => {
		this.component1.testMethod();
	}
}
```

Without `injectStyles` I can do that, but with JSS I can't.

Any suggestions for this case? Should I wrap whole component with `injectStyles()` or there is another true way?

**Comment by kof** [comment]
You can extract the render component and wrap it with injectStyles.

**Comment by sergeyzwezdin** [comment]
@kof Not sure what you mean. Could you give some example?

**Comment by kof** [comment]
```js
const Render = ({classes}) => <div className={classes.something}></div>
const StyledRender = injectSheet(styles)(Render)

export defatult class PublicComponent extends Component {
  youPublicMethod() {

  }
  render() {
     return <StyledRender />
  }
}
```

**Comment by sergeyzwezdin** [comment]
So we need two definitions (`Render` and `PublicComponent`) instead of one? Just to solve styling task?

IMHO it  adds lot of mess into the code.

**Comment by sergeyzwezdin** [comment]
In case someone will face the same problem, I ended up with following solution.

#### Somewhere in common files:

```
import theme from '...';

export const attach = (styleDefinition) => {
	const styles = styleDefinition(theme);
	const sheet = jss.createStyleSheet(styles).attach();

	return sheet.classes;
};
```

#### component1.styles.js

```
import { attach } from '...';

export default attach(theme => ({
	text: {
		// styles here
	},

	// ...
}));
```

#### component1.js

```
import styles from './component1.styles';

class Component1 extends React.Component {
	testMethod() {
		// ...
	}

	render() {
		<div className={styles.text}>...</div>
	}
}

export default Component1;
```

**Comment by MikeBarnhardt** [comment]
Did you try using the [`innerComponent`](https://github.com/cssinjs/react-jss#the-inner-component)?

`injectStyles` is a HoC so your public method would probably be attached to the `innerComponent`.

Your original code should probably have been `this.component1.InnerComponent.testMethod();`
