### ISSUE TITLE
Allow nesting of JssProvider

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#157]
The current implementation of the JssProvider makes it impossible to gradually provide configuration options in the render tree.
https://github.com/cssinjs/react-jss/blob/cda37731dad5e1ecdea61ec6eabb62500a169383/src/JssProvider.js#L32-L39

I have a use case with next.js where
- I'm using the `sheetsRegistry` option to collect the server side generated side:
https://github.com/callemall/material-ui/blob/v1-beta/pages/_document.js#L104-L106
- On the client side, I want to provide a `jss` instance to customize the injection point https://github.com/callemall/material-ui/blob/v1-beta/docs/src/modules/components/AppWrapper.js#L13-L22

**Comment by oliviertassinari** [comment]
Actually, I think that I have a workaround where a single `JssProvider` is enough. I will post the commit here once it's confirmed.

**Comment by oliviertassinari** [comment]
Here is my workaround: https://github.com/callemall/material-ui/pull/8497. Not bad. As far I'm concerned it's no longer an issue, but extra flexibility won't harm. Your call.

**Comment by oliviertassinari** [comment]
Oh no, damn, it's not working 🔧

**Comment by oliviertassinari** [comment]
Ok, I have been making a stupid mistake, we are back on track.

**Comment by kof** [comment]
You could use one JssProvider on the server and a different one on the client, right?

**Comment by kof** [comment]
Supporting nesting providers will lead to a lot of complexities and indirection.

**Comment by kof** [comment]
Ok I got a plan:
1. On the client, JssProvider should not  reset the managers when rerendered
2. It should forward context props defined by the parent JssProvider if no specific new prop has been defined. In this case it works like a proxy.

**Comment by oliviertassinari** [comment]
I like the option of being able to incrementally add key into the context. Regarding overriding one that is already present. You could warn if it's simpler or extend. Your plan seem to go into this direction 👍 .

**Comment by kof** [comment]
I think if user wants to override some setting for e.g. use a different Jss instance for a subtree, we should let him do  that.

**Comment by kof** [comment]
Released v8
