### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by hburrows** [cssinjs/react-jss#162]
This package is dependent on `theming ` which doesn't (currently) support React 16. When trying to use with React 16 this results in 2 versions of React getting bundled which is a no go.  What are the plans for this package supporting React 16?  (I know... I know... I thought this was limited to `styled-jss`)

**Comment by kof** [comment]
The plans are to support react 16.  Would you like to help out?

**Comment by hburrows** [comment]
@kof Sure -- I'd be happy to help out.  I'm seeing a lot of open PRs in `theming`.  Your plan is to continue using this package?

**Comment by kof** [comment]
yes, definitely

**Comment by kof** [comment]
@iamstarkov do you like to give @hburrows commit rights so that he can review and merge the PRs?

**Comment by kof** [comment]
Or mb there is another way to let him help?

**Comment by hburrows** [comment]
I created a new branch in `theming`, updated all the dependencies, and added the necessary `enzyme` adapter to support React 16.  All tests are passing.  There are a couple issues that probably need discussion but it's a good first step.  I don't have permission to push a PR and there's no mention of how to contribute so I'll wait for further guidance.

**Comment by pcardune** [comment]
@hburrows would you mind linking to your branch? I'd like to give it a try.

**Comment by hburrows** [comment]
@pcardune Sure.  I need to fork this project and react-jss first and then re-apply my changes.

**Comment by kof** [comment]
@hburrows quick update: we are going to move theming repository to cssinjs org, I need help with maintaining. Would you like to take care of it?

**Comment by hburrows** [comment]
@kof Sure.  I haven't done this before but I'm willing to give it a try.

**Comment by kof** [comment]
updated theming

**Comment by kof** [comment]
Released v8
