### ISSUE TITLE
v8.0.0 is not published to NPM/Yarn

### ISSUE THREAD

**Issue by EugeneZ** [cssinjs/react-jss#163]
Hello and thank you for the hard work! I noticed you released 8.0.0 several days ago, but I don't see it on NPM/Yarn.

https://www.npmjs.com/package/react-jss

https://yarnpkg.com/en/package/react-jss

Figured I'd open an issue in case it was an accidental oversight. If not, ignore! 👍

**Comment by kof** [comment]
i have only merged to master, it i s not released.

**Comment by wzrdzl** [comment]
what is the plan about publishing it?

**Comment by kof** [comment]
When I finish some issues.
