### ISSUE TITLE
Dependency prop-types should be peerDependency

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#164]
Just asking myself why react is  a peerDependency but prop-types is a dependency.

**Comment by oliviertassinari** [comment]
prop-types should be a dependency. At least, it's what @gaearon suggested early on. You don't risk any conflict. For instance [react-redux](https://github.com/reactjs/react-redux/blob/4c2670dc11cc067ef106f6c527e6e8b9d47f8af8/package.json#L109).

**Comment by kof** [comment]
Why is then react a peerDependency?

**Comment by oliviertassinari** [comment]
Because you can't have two versions at the same time and because the dependency size is not negligeable.

**Comment by oliviertassinari** [comment]
But peerDependencies are more paintfull to handle on userland.

**Comment by kof** [comment]
>  the user doesn't have to use them

That makes sense!
