### ISSUE TITLE
Computed keys in sheet passed to injectSheet()?

### ISSUE THREAD

**Issue by sdotson** [cssinjs/react-jss#166]
Hello, I am trying to get computed keys to work with the stylesheet.

Here is my style:
```
const sheet = {
  container: {
    background: props => props.theme.header.backgroundColor,
    '& .header-logo': {
      backgroundImage: props => `url(${props.theme.header.logo.url})`,
      height: props => props.theme.header.logo.height,
      width: props => props.theme.header.logo.width,
      backgroundRepeat: 'no-repeat',
      backgroundPosition: '50% 50%',

      [props => props.theme.breakpoints.mediumUp]: {
        backgroundImage: props => `url(${props.theme.header.logoLg.url})`,
        height: props => props.theme.header.logoLg.height,
        width: props => props.theme.header.logoLg.width
      }
    }
  }
}
```
I inject it at the bottom of the component file like so: ```export default injectSheet(sheet)(Header);```

All the computed keys simply become the string representations of the functions, rather than their values (e.g. `"function (props) {↵ return props.theme.breakpoints.mediumUp;↵ }"`). 

I wonder if there is some way to do computed style properties? Perhaps one way to do it is to permit functions/factories passed as an argument to `injectSheet()`?

**Comment by kof** [comment]
I am not sure
1. what you are trying to achieve
2. what you actually do when you say "trying to get computed keys"

**Comment by sdotson** [comment]
Thank you for responding so quickly.

My intention is that `[props => props.theme.breakpoints.mediumUp]` return a css media query. 

Let's say for example that `props.theme.breakpoints.mediumUp` equals `@media screen and (min-width: 30em)`. I'd like the rules I have there for `backgroundImage`, `height`, and `width` to take effect for that media query breakpoint.

Looking at the output source, I don't see any kind of media queries. It looks like the rule is ignored altogether.

My goal is to get that media-query to work.

**Comment by kof** [comment]
to access theme during styles declaration use function: `const styles = (theme) => ({...styles}) `
