### ISSUE TITLE
Another benefit to add in docs "Critical-css / prerender"

### ISSUE THREAD

**Issue by damianobarbati** [cssinjs/react-jss#169]
@kof another benefit I just noticed using jss is that prerendered pages automatically do have critical-css (and actually more than that) inlined thus there's no need for additional tooling: isn't this an epic win for jss to mention in the benefits? :|

**Comment by kof** [comment]
it def. is, would u like to submit a pr?

**Comment by iamstarkov** [comment]
it definitely should be considered as big win

**Comment by kof** [comment]
added
