### ISSUE TITLE
Jss dependency on npm registry doesn't match what's in the repo for version 7.2.0

### ISSUE THREAD

**Issue by jcheroske** [cssinjs/react-jss#170]
I'm seeing this strange output from `yarn list jss`:
```
├─ jss@9.0.0
├─ material-ui@1.0.0-beta.18
│  └─ jss@8.1.0
└─ react-jss@7.2.0
   └─ jss@8.1.0
```
Snooping around, I discovered that the `package.json` coming from the npm registry looks like this:
```
{
  *** snip ***
  "dependencies": {
    "hoist-non-react-statics": "^1.2.0",
    "jss": "^8.1.0", // <-- old version!
    "jss-preset-default": "^3.0.0",
    "prop-types": "^15.5.8",
    "theming": "^1.1.0"
  },
*** snip ***
}
```
That doesn't match the current code in the repo. Have I found an issue, or am I missing something?

**Comment by jcheroske** [comment]
Ok, I just saw that you upgraded to jss 9 after the last release. My bad. Any idea when you're going to publish the latest changes?

**Comment by kof** [comment]
asap

**Comment by kof** [comment]
next week probably

**Comment by jcheroske** [comment]
Thank you. Don't mean to nag.

**Comment by kof** [comment]
updates are always announced in related issues and twitter, if nothing happens, means maintainer has a real life, you need it faster - fork it and wait.

**Comment by kof** [comment]
But thank you for asking.
