### ISSUE TITLE
Why styling required on server side.

### ISSUE THREAD

**Issue by abdulwahid-360training** [cssinjs/react-jss#173]
I got an example of react-jss isomophic implementation.

**On server side**
we are using `{JssProvider, SheetsRegistry}` to get styling content and add it into `sytle` tag.
```
<style type="text/css" class='jss-sheet' >
          {sheets.toString()}
        </style>
```

**On client side**
we are removing same style tag.
```
const jssServerSide = document.querySelector('.jss-sheet'')
jssServerSide.parentNode.removeChild(jssServerSide)
```
**Question**
If have to remove it on client side then why we are using it? There would be definitely a valid reason of using styling on server side but don't have any idea. If it is required for SEO then please explain why for SEO.

**Comment by ValentinH** [comment]
It is used if you want to do server-side rendering.

If you don't inject the styles on server side, then when your page is loaded, your styles are not present at the very beginning until they are injected by the JSS instance in the browser. Thus, you can see some elements moving or not being styled at all on init.
