### ISSUE TITLE
Classes does not work for Components with special chars in display name

### ISSUE THREAD

**Issue by luiz290788** [cssinjs/react-jss#176]
The new prefix for the generated classes that use the display name of the decorated components are not being sanitized.

For example:
Decorated class display name "SomeOtherDecorator(Test)"
Generated classes ".SomeOtherDecorator(Test)-root-0-1"
The parenthesis in the classes is causing the problems here.

Suggested solution: Parse the display name of the component to remove the special characters.

**Comment by kof** [comment]
Or escape the chars.

**Comment by luiz290788** [comment]
I was checking the code and thinking about the issue, it seems to be a jss issue instead of a react-jss issue. What do you think?

**Comment by kof** [comment]
Also the escaping needs to be done in dev mode only, because in production we build short class names.

**Comment by kof** [comment]
Issue moved to [cssinjs/jss #624](https://github.com/cssinjs/jss/issues/624) via [**ZenHub**](https://www.zenhub.com/)
