### ISSUE TITLE
Support for overwriting styles

### ISSUE THREAD

**Issue by romelperez** [cssinjs/react-jss#179]
Hi! Is there a way to overwrite/extend the styles of a component of a similar way [Material UI v1](https://material-ui-next.com) does with its approach [overwrite with classes](https://material-ui-next.com/customization/overrides/#overriding-with-classes)?

I am building a simple UI framework and I would like to support that in the components, something like this:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import withStyles, { ThemeProvider } from 'react-jss';

const buttonStyles = (theme) => ({
  root: {
    border: '1px solid ' + theme.color,
    color: theme.color,
    backgroundColor: theme.backgroundColor,
  }
});

// This component would have the styles:
// root {
//   color: #f40b85;
//   border: 1px solid #f40b85;
//   background-color: #ffffff;
// }
const Button = withStyles(buttonStyles)(({ classes, children }) => {
  return (
    <button className={classes.root}>{children}</button>
  );
});

const customButtonStyles = (theme) => ({
  root: {
    color: '#ff0000',
    fontWeight: 'bold',
  }
});

// This component would have the styles:
// root {
//   color: #ff0000;
//   border: 1px solid #f40b85;
//   background-color: #ffffff;
//   fontWeight: 'bold',
// }
const CustomButton = withStyles(customButtonStyles)(Button);

const App = () => {
  return (
    <div>
      <Button>Default Button</Button>
      {' '}
      <CustomButton>Custom Button</CustomButton>
    </div>
  );
};

const theme = {
  color: '#f40b85',
  backgroundColor: '#ffffff',
};

ReactDOM.render(
  <ThemeProvider theme={theme}>
    <App />
  </ThemeProvider>,
  document.querySelector('#root')
);
```

Which would render something like this:

![support-for-overwrite-styles](https://user-images.githubusercontent.com/1393135/32763209-57b5ff10-c8cc-11e7-82d2-acb71cc14eda.png)

Is there a future plan release with this support or a PR would be required? Thanks in advanced.

**Comment by kof** [comment]
Do you mean something like this? https://twitter.com/oleg008/status/930186426574098432

**Comment by kof** [comment]
Ah you mean a component that has been wrapped by injectSheet hoc to be rewrapped by another injectSheet hoc? I think you can do it already.

**Comment by romelperez** [comment]
@kof yes! But with the exact code I posted doesn't work. How can I accomplish this? Or should I create another HOC to handle that situation?

**Comment by romelperez** [comment]
If that is not supported, would it be a good idea to support it with **react-jss** HOC? Or should it be another HOC?

**Comment by kof** [comment]
classes object is merged, so if you overwrite one property, just one property is overwritten. React-JSS doesn't merge though multi class strings {a: 'a'} > {b: 'b'} => {a: 'a', b: 'b'}, but if there is  {a: 'a b'} > {a: 'c'} => {a: 'c'}

**Comment by romelperez** [comment]
Awesome! Then how do I implement it? Because the example above didn't work. Thanks!

**Comment by romelperez** [comment]
I am gonna research how can I accomplish this. Thanks @kof !
