### ISSUE TITLE
react-redux connect in react-jss 8.0.0 not working well

### ISSUE THREAD

**Issue by codler** [cssinjs/react-jss#180]
This worked in previous version of react jss v7.2.0, but not in v8.0.0
```
import { connect } from 'react-redux';
import injectSheet from 'react-jss';
...
export default injectSheet(styles)(connect(mapStateToProps)(MyComponent));
```

**Comment by kof** [comment]
Can you please describe what is not working and ideally make a codesandbox.io example to make sure we understand?

**Comment by codler** [comment]
react-jss v7.2.0 https://codesandbox.io/s/r0mvo4vyrp
react-jss v.8.0.0 https://codesandbox.io/s/3xwqlk8v6q

**Comment by kof** [comment]
I see, will be fixed in a bit.

**Comment by kof** [comment]
fixed
