### ISSUE TITLE
duplicate classNames when importing components from multiple packages

### ISSUE THREAD

**Issue by hburrows** [cssinjs/react-jss#181]
Entirely possible I'm not understanding how to do this correctly....  I have components in shared, imported packages that are wrapped with `injectSheet`.  In development mode everything is fine.  However, when I create a production build I'm getting duplicate classNames.  It appears that each imported package has it's own "generateClassName" function.  The imported packages declare `react-jss` (and `styled-jss`) as peerDependencies only.

What is the recommended way to have components in multiple packages which use `injectSheet` but end up with a unique className in a production build?

**Comment by kof** [comment]
are you using provider around your app?

**Comment by kof** [comment]
I assume that you have different react-jss versions in those packages, so if you wrap it into a provider, jss over context will be used. Another option is to make sure you use the same react-jss version everywhere.

**Comment by kof** [comment]
Once you figured this out please help improve documentation on that.

**Comment by hburrows** [comment]
I will definitely update the docs when I figured this out.  However, I haven't fixed this yet but I have narrowed it down to my use of `styled-jss` as the culprit.  Doesn't appear that `styled-jss` honors anything in context put there by `JssProvider` -- I'm using `react-jss` and `styled-jss` in the same app (the combination of the 2 is great).  Most of my `styled-jss` use is in a separate, sharable package.  `styled-jss` does not declare `react-jss` as a dependency so I"m not sure this is technically a bug.  However, my expectation was that they'd work together -- especially since they both target react apps.  For the benefit of the `jss` ecosystem... and getting stuff to "just work" I wonder if `styled-jss` should honor what `JssProvider` puts there ?

I'm going to explore a "custom JSS" setup and try to share a className generator between the 2... but this seems like a lot of friction for 2 packages that I would expect to work well together.  Curious what your thoughts are ?

**Comment by kof** [comment]
Oh yes, styled-jss doesn't know anything about react-jss right now.

**Comment by kof** [comment]
We should talk about this in styled-jss repository!

**Comment by kof** [comment]
Initially they were not ment to be be used together, but I think in theory they should do so if they turn out to be complementary. I think we are not aware right now of complementarity.

**Comment by hburrows** [comment]
Moving discussion to `style-jss` as https://github.com/cssinjs/styled-jss/issues/60.
