### ISSUE TITLE
function rules, values with expand, and values inside fallbacks don't work

### ISSUE THREAD

**Issue by conundrumer** [cssinjs/react-jss#185]
These styles don't work

```javascript
const styles = {
  wrapper: () => ({
    padding: 40,
    background: 'blue'
  }),
  title: {
    font: () => ({
      size: 80,
      weight: 900
    }),
    color: 'invalid',
    fallbacks: {
      color: () => 'yellow'
    }
  }
}
```

Example: https://codesandbox.io/s/k2z9773rxv

Workaround: function fallbacks work

```javascript

    fallbacks: () => ({
      color: 'yellow'
    })
```

**Comment by kof** [comment]
Seems to be a bug.

**Comment by jedwards1211** [comment]
@kof have function values been silently deprecated?  I thought I remember being able to do
```js
const styles = {
  appContent: {
    position: 'absolute',
    left: props => props.sidebarOpen ? 240 : 0,
  }
}
```

**Comment by jedwards1211** [comment]
It seems like everything is breaking, at least when I use this with Material UI.  The class name generation seems to be broken and it's inserting spaces where it shouldn't.  Do you know what would be causing this?
`App- Unthemed- Dynamic-appContent-3 App- Unthemed- Static-appContent-2`

**Comment by kof** [comment]
@jedwards1211 please create a reproducible issue on the right repository, if this happens only with mui, then it is a mui issue.

**Comment by jedwards1211** [comment]
My apologies, I wasn't sure if it was purely mui's fault or it was bugs in both packages causing them to work together poorly, but I've now confirmed that it's completely the fault of mui's custom `generateClassName` function: https://github.com/mui-org/material-ui/issues/9643

**Comment by kof** [comment]
got rule values fixed

**Comment by kof** [comment]
- [ ] fallbacks
- [ ] expanded syntax with functions isn't fix

Will create separate issues for them
