### ISSUE TITLE
Use componentDidMount instead of componentWillMount

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#186]
Just tested the behavior, we can render styles after dom nodes and still have no FOUC if we do it in sync.

Here is a test https://codesandbox.io/s/qzrkx0lrl6

React is calling componentDidMount synchronously, right after dom render, so we can use it according to @bvaughn

Lets remove the use of componentWillMount, because it is not for side effects and may result in leaking styles if an error happens during mount.

**Comment by kof** [comment]
cc @oliviertassinari @nathanmarks

**Comment by bvaughn** [comment]
Relevant code is in the `ReactFiberScheduler`. First we [flush pending changes to eg the DOM](https://github.com/facebook/react/blob/8ec146c38ee4f4c84b6ecf59f52de3371224e8bd/packages/react-reconciler/src/ReactFiberScheduler.js#L385-L420) then we [call the commit phase lifecycle hooks and ref callbacks](https://github.com/facebook/react/blob/8ec146c38ee4f4c84b6ecf59f52de3371224e8bd/packages/react-reconciler/src/ReactFiberScheduler.js#L430-L464) (which is [where `componentDidMount` gets called](https://github.com/facebook/react/blob/8ec146c38ee4f4c84b6ecf59f52de3371224e8bd/packages/react-reconciler/src/ReactFiberCommitWork.js#L96-L122)).

**Comment by kof** [comment]
Just tried to do that, we can't, because componentDIdMount is not called during SSR, so we have no other hook to go.

**Comment by oliviertassinari** [comment]
> Lets remove the use of componentWillMount, because it is not for side effects and may result in leaking styles if an error happens during mount.

As far as I know we have no guarantees that `componentWillMount` -> `componentDidMount`. But we have the guarantee that `componentWillMount` -> `componentWillUnmount`. How can this cause a leak?

**Comment by kof** [comment]
It wasn't about a leak, it was a potential undeterministic state when side effects are done in componentWillMount

**Comment by bvaughn** [comment]
> Just tried to do that, we can't, because componentDidMount is not called during SSR, so we have no other hook to go.

I wonder if you considered doing environment detection in `componentWillMount` and only triggering the side-effects in the case of a server render?

> But we have the guarantee that `componentWillMount` -> `componentWillUnmount`.

This is incorrect, although it's probably a common misconception.

A component's will-mount lifecycle method may be called for a component that never actually mounts (due to an interruption or an error thrown by another component). If a component does not mount (aka no `componentDidMount`) then `componentWillUnmount` will not be called.

**Comment by kof** [comment]
> I wonder if you considered doing environment detection in componentWillMount and only triggering the side-effects in the case of a server render?

Do you think it is worth it? 

During SSR it still will do the side effect in componentWillMount with potential undeterministic state + now we have a potential bug that is only reproducible with SSR ...

**Comment by oliviertassinari** [comment]
> This is incorrect, although it's probably a common misconception.

@bvaughn Thanks for the following up! We need to rely on some timeout logic then.

**Comment by bvaughn** [comment]
This RFC is somewhat related: reactjs/rfcs/pull/8
