### ISSUE TITLE
React-jss and redux connect conflict

### ISSUE THREAD

**Issue by benn983** [cssinjs/react-jss#189]
Hi I've problem using react-jss injectSheet and redux connect.
This is my code.
In developer mode works perfectly but in build mode doesn't work anymore.
![schermata del 2017-12-20 17-57-38](https://user-images.githubusercontent.com/26009890/34218749-514c700a-e5af-11e7-95e1-5eb7ae750f8d.png)

**Comment by kof** [comment]
I don't see an obvious reason, please create a demo on codesandbox.

**Comment by benn983** [comment]
ok but does codesandbox work with a build pf a creare-react-app? Because I have this problem only  there and not running the app using npm start

**Comment by benn983** [comment]
The problem si that in build mode , where classes are autogenerated, the style doesn’t work anymore . I tried to do the same app without redux and connect hoc and this problem doesn’t exsist. Also I’ve noticed that classes are pretty different between two apps

**Comment by benn983** [comment]
Found it and probably resolve it. It wasn't a conflict but a really strange problem with Chrome cache and the service worker
