### ISSUE TITLE
Production mode for defaultClassNamePrefix

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#191]
Recent JSS version started to use classNamePrefix option also in production, now we end up having displayName in production as well, which might be bit longer than necessarily. Lets use 'jss' as a defaultClassNamePrefix if we are in production.

**Comment by kof** [comment]
cc @oliviertassinari

**Comment by kof** [comment]
@btmorex check out react-jss@8.2.1 and let me know if still not fixed

**Comment by btmorex** [comment]
@kof Working again. Thanks!

**Comment by dndhm** [comment]
@kof is it the desired behaviour to omit the `classNamePrefix` altogether in production? How do you locally-scope your classnames consistently across environments without this feature?
