### ISSUE TITLE
Function rules not working?

### ISSUE THREAD

**Issue by afrankel-sfdo** [cssinjs/react-jss#199]
I believe I am using them correctly, but can't seem to get them to execute/apply to the styles. In the example below I expect all of the tests to have red text. Function rule is the only one that doesn't work.

```
const styles = (theme) => ({
  basic: {
    color: 'red'
  },
  value: {
    color: () => 'red'
  },
  rule: () => ({
    color: 'red'
  })

})

const Comp = ({ classes }) => (
  <div>
    <h1 className={classes.basic}>Basic</h1>
    <h1 className={classes.value}>Function Value</h1>
    <h1 className={classes.rule}>Function Rule</h1>
  </div>
)
```

![screen shot 2018-02-12 at 3 41 03 pm](https://user-images.githubusercontent.com/31106469/36123828-2934b3e4-100b-11e8-8baa-dda891e1a5ed.png)

see: https://codesandbox.io/s/l226z8kzjl

**Comment by kof** [comment]
I see red text in all 3 on YOUR codesandbox

**Comment by kof** [comment]
mb some cache issue with codesandbox?

**Comment by afrankel-sfdo** [comment]
Looks good to me now also. FYI, the sample react-jss codepen project is on 8.0.0 (https://codesandbox.io/s/j3l06yyqpw). I had bumped to 8.3.3, but as you suspected, might have been a caching issue. Thanks!

![screen shot 2018-02-13 at 8 31 27 am](https://user-images.githubusercontent.com/31106469/36157955-502c8278-1098-11e8-8d6a-b5189bf568d8.png)
