### ISSUE TITLE
Media queries in function rules doesn't work

### ISSUE THREAD

**Issue by afrankel-sfdo** [cssinjs/react-jss#202]
As seen by the last two examples, `media queries` don't work correctly when included within a `function rule`

Example: https://codesandbox.io/s/612mjov4vw

```
const styles = theme => ({
  default: {
    color: theme.color
  },
  basic: {
    color: theme.error,
    "@media (min-width:0px)": {
      color: theme.color
    }
  },
  function: {
    color: theme.error,
    "@media (min-width:0px)": {
      color: () => theme.color
    }
  },
  rule: () => ({
    color: theme.error,
    "@media (min-width:0px)": {
      color: theme.color
    }
  }),
  dynamic: ({ breakpoint }) => ({
    color: theme.error,
    [breakpoint]: {
      color: theme.color
    }
  })
});
```
<img width="259" alt="screen shot 2018-02-19 at 1 33 53 pm" src="https://user-images.githubusercontent.com/31106469/36396123-aa65cf5c-1579-11e8-8a1c-19738002d5a8.png">

**Comment by kof** [comment]
so the part that is not working is only this?

`` `js
  dynamic: ({ breakpoint }) => ({
    color: theme.error,
    [breakpoint]: {
      color: theme.color
    }
  })

```

**Comment by kof** [comment]
This is currently not supported for perf reasons. I will consider this as a feature request.

**Comment by afrankel-sfdo** [comment]
@kof this one also doesn't work 
``` 
 rule: () => ({
    color: theme.error,
    "@media (min-width:0px)": {
      color: theme.color
    }
  }),
```

where is the performance hit with dynamic breakpoints?

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/jss/issues/682
