### ISSUE TITLE
Non standard css (-webkit-slider-thumb and similar)

### ISSUE THREAD

**Issue by delacalera** [cssinjs/react-jss#204]
Hi there,
When trying to style input type range elements, we run into an issue with specific browser properties.
JSS does the job for cross browser compatiblity for standard rules, but, there's no way to style these kind of elements.
I believe it cannot be achieved with the current functionality.
Is there any workaround for this?
Thanks

**Comment by kof** [comment]
what styles exactly are you trying to apply?

**Comment by delacalera** [comment]
Hi kof,
THe selector I am trying to access are regarding input type range elements:

-webkit-slider-runnable-track
-webkit-slider-thumb

Thanks!

**Comment by kof** [comment]
I fail to see what the problem is, its a regular pseudo elements selector, it can be generated using jss-nested plugin, which is already part of the react-jss bundle.

**Comment by delacalera** [comment]
Thanks a lot kof and sorry for this. I've got it working now, probably I didn't have enought coffe at the time...
