### ISSUE TITLE
Support for ES5 target

### ISSUE THREAD

**Issue by hisivasankar** [cssinjs/react-jss#205]
I am having a React-App with typescript targetting `es5`.

`CreateHOC.js` uses `Object.assign` because of which my app doesn't working IE 11

I have tried using it with `babel-preset-env`. Since I am not using `Object.assign` in any of my source code, polyfills are not getting added and I don't want to blindly add all polyfills

Any help would be appreciated.

**Comment by kof** [comment]
Its up to you how you add polyfills, I don't know how react-jss package can help with that.

**Comment by kof** [comment]
Its a general practice to rely on certain polyfills being installed by the consumer. Adding a polyfill directly to the library is not an option.
