### ISSUE TITLE
Adding RTL support to React-JSS 

### ISSUE THREAD

**Issue by hisivasankar** [cssinjs/react-jss#209]
Hi,

I have been recently working on add RTL support using `jss-rtl` plugin. I have faced few problems while implementing without degrading the performance.

I would like to add a PR to support RTL natively from React-JSS itself. Would you accept?

Thanks,
Sivasankar

**Comment by kof** [comment]
Please clarify very detailed problems you had and why it is not possible to solve them in a plugin.
