### ISSUE TITLE
how to write descendant selector in react for react-jss

### ISSUE THREAD

**Issue by luckystar12** [cssinjs/react-jss#211]
<Search
          className={classes.iSearchInput}
          placeholder='请输入'
          onSearch={this.onSeacher}
          enterButton
        />

render in broswer:
<div class='ant-input-search iSearchInput'>
    <input class='ant-input'/>
</div>

in react-jss how to use
import injectSheet from 'react-jss'
const styles = {
     iSearchInput: XXXX  // how to use
}

**Comment by kof** [comment]
take a look at jss-nested plugin http://cssinjs.org/jss-nested

**Comment by luckystar12** [comment]
thanks, I have solved it.
