### ISSUE TITLE
Adding ref support for injectSheet hoc.

### ISSUE THREAD

**Issue by alexankin** [cssinjs/react-jss#212]
In our project we need to have access to original component after it has been wrapped with injectSheet hoc.

Example:
```jsx
const Styled = injectSheet(InnerComponent);
let component;
<Styled ref = {cmp => component = cmp}/>
```
In this case component will be injectSheet(Component), not Component. And this is expected behavior. But we need to have acess to InnerComponent, something like this:
```jsx
<Styled componentRef = {cmp => component = cmp}/>
```

**Comment by TriPSs** [comment]
Can't you just set the `componentRef` yourself? Like:

```js
<Styled componentRef={ref => component = ref} />
```

```js
class Styled extends React.Component {

  render() {
    return (
       <div ref={this.props.componentRef}>

       </div
    )
  }
}
```

**Comment by alexankin** [comment]
I need ref to InnerComponent itself, not to any html element inside it. So `ref={this.props.componentRef}` should be done in injectSheet hoc.

**Comment by TriPSs** [comment]
Pharaps then update the render method of `createHoc` to

```js
  render() {
    const { theme, dynamicSheet, classes } = this.state
    const { ref = null, ...rest } = this.props
    
    const sheet = dynamicSheet || this.manager.get(theme)
    const props = {}
    
    if (injectMap.sheet) props.sheet = sheet
    if (isThemingEnabled && injectMap.theme) props.theme = theme
    
    Object.assign(props, rest)
    // We have merged classes already.
    if (injectMap.classes) props.classes = classes
    return <InnerComponent ref={ref} {...props} />
  }
```

Ideas @kof?

**Comment by HenriBeck** [comment]
@TriPSs Your example wouldn't work as you don't get the `ref` property inside `this.props`. We would need some prop named `componentRef` for that.

You should also be able to call `createRef` for example in the constructor of the component you need access too.
That should work too:
```js
// In your component where you need access
constructor(props) {
  super(props);

  props.createRef(this);
}
```

**Comment by TriPSs** [comment]
@HenriBeck Updated the example, forgot that ref would not be available in the props. Thanks!

**Comment by kof** [comment]
I am open to merge a PR for this.

**Comment by kof** [comment]
Normally other libraries call this prop `innerRef`

**Comment by kof** [comment]
Please also include a test

**Comment by alexkuz** [comment]
I have to point out that there is a problem now - if I already used `innerRef` in wrapped component (which I did) it will break the code. I'm fixing it by renaming, but the fact that the prop is now "swallowed" by wrapper component is a bit counter-intuitive.

**Comment by kof** [comment]
Hmm, I wonder what could be a fix for this?
