### ISSUE TITLE
re implement inject option to inject only part of theme as prop

### ISSUE THREAD

**Issue by yash-bagadia** [cssinjs/react-jss#214]
+1 if you think this is useful so that it can be merged to react-jss.

PR : https://github.com/cssinjs/react-jss/pull/216

By default theme is injected as prop to component. But in the options to injectSheet
we can whitelist props to be injected with 'inject' property. However, if we want to inject only some part
of theme as prop there is no way. So adding one more key to inject option to give
the flexibility to inject only part of theme. 
So lets take an example component where we are consuming a property 'height' and we want to provide flexibility where property can directly be passed to the component or at a global level as part of theme so that all component instances will get the same value for that property. 
```javascript
const Example = props => {
const height = props.height || props.theme.ButtonBase.height; //give priority to props.height
//as it is passed specific to this instance
  return <div> value of height is {height} </div>;
};
```
While this works, there are two problems with this approach: 

1. Entire theme object is passed to the component which might be huge and the component required
only few of the properties.
2. For each of the property that we are allowing to be defined in theme, we will end up writing code
like:
```javascript
props.height || props.theme.ButtonBase.height
```
which makes the code look ugly and difficult to maintain.

By providing the provision to inject only part of theme as prop to the component, we solve
both of the above problems. Only required properties will be injected making props
object small.
Secondly, for each property  we just need to consume it like:
```javascript
props.height
```

**Comment by kof** [comment]
I believe this may lead to more indirection, than it helps. I need a better case study to see a real problem that we need to solve here.
