### ISSUE TITLE
Get styles insid component

### ISSUE THREAD

**Issue by jdflaugergues** [cssinjs/react-jss#217]
It would be fine to get styles component inside it during `injectSheet`.
In this case, styles would be a static property of a component, and during the injectSheet, just need to pass the component as arguments.
Exemple :
```javascript
class MyComponent extends Component {
  static styles = {
    // put styles here
  }
  // other functions component
}

export default injectSheet(MyComponent); // (styles is fetch inside MyComponent, no need to pass styles arguments)
```

**Comment by kof** [comment]
Why?

**Comment by jdflaugergues** [comment]
To avoid redundant code by factorize it. It may be a convention for styles of components.

**Comment by kof** [comment]
What do I miss? I don't see how this is going to avoid redundance… can you make an example before and after?

**Comment by HenriBeck** [comment]
You could write your own little helper function which then calls injectSheet simply.

**Comment by jdflaugergues** [comment]
Yes @HenriBeck, I can write my own helper functin like this:
```javascript
import injectSheet from 'react-jss'

export default function customInjectSheet(component) {
  return injectSheet(component.styles)(component);
}
```
But the aim of my request is to avoid it and integrate this default shortcut into react-jss library.
We can assume that static styles property of a Component is a convention to inject style as a default behaviour argument injectSheet function is a react component.

Before this feature : 
```javascript
import injectSheet from 'react-jss'

const  styles = {
  // ...
}

class MyComponent extends Component {
  //...
}

export default injectSheet(styles)(MyComponent);
```

After with this featujre
```javascript
import injectSheet from 'react-jss'

class MyComponent extends Component {
  static styles = {
    // ...
  }
  //...
}

export default injectSheet(MyComponent);
```

**Comment by HenriBeck** [comment]
@jdflaugergues 

> We can assume that static styles property of a Component is a convention to inject styles as a default behavior if argument injectSheet function is a react component.

Why would we assume that this is a convention?

Also, would your proposal mean a breaking change?

**Comment by jdflaugergues** [comment]
Because `styles` is the most common variable name used to define styles in react app.
I don't think my proposal is a great breaking change but may be a usefull shortcut.
But if you don't thinks so, that's doesn't matter, I can use a helper function.

**Comment by kof** [comment]
@jdflaugergues I don't know how much value in this is compared to the indirection that `injectSheet(component)` now takes a component additionally to a styles object.

**Comment by kof** [comment]
I would rather not include this, its a neat thing, but adds an additional way of using injectSheet, which is more harm than good.
