### ISSUE TITLE
styles typing (auto-completion, validation)

### ISSUE THREAD

**Issue by caub** [cssinjs/react-jss#218]
I think many of us would like to have syntax highlighting, validation, .. for the styles

I'll talk about VSCode, sorry about other editors, styled-components have https://github.com/styled-components/vscode-styled-components

It should be possible to do it, but more using React definitions:
![2018-03-29-112240_1305x489_scrot](https://user-images.githubusercontent.com/3134574/38081267-e469068c-3343-11e8-9297-1606459c512d.png)

And trigger it for a 
```js
const styles = {
  foo: {
    alignItems: '...'
  }
};
```

@visioncan did something interesting: https://github.com/visioncan/vscode-jss-snippets, but I think I'd prefer that it behaves like React inline styles

**Comment by kof** [comment]
Also having flow and/or typescript typings for styles would allow vscode and other editors to show the hints https://github.com/cssinjs/jss/issues/361 https://github.com/cssinjs/jss/issues/375

Types could be generated out of [mdn database](https://www.npmjs.com/package/mdn-data), we started a repo but 
 I still had to time  https://github.com/cssinjs/style-type-generator

**Comment by HenriBeck** [comment]
I would also prefer adding types rather than specific plugins as types can work in all editor which support flow/typescript.

Also tracking down which object is a Jss stylesheet might be hard, especially when they are in different files.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by caub** [comment]
The ones from [Glamorous](https://github.com/paypal/glamorous/tree/master/typings) might be really close to what is needed [talk](https://www.youtube.com/watch?v=r5UtdJNxN94)

**Comment by jeffal** [comment]
Would this idea include class name validation? For example, a no unused class name lint rule.

**Comment by kof** [comment]
@jeffal I think its  a separate issue, created one here https://github.com/cssinjs/jss/issues/705

**Comment by HenriBeck** [comment]
I have typed my styles like this, though that doesn't save you from unused rules.

Example:
```js
const styles = {
  root: {
    display: 'flex',
  },
};

type Props = { classes: { [keys: $Keys<typeof styles>]: string } };

// or with a little helper type:
type ClassesProp<S> = { [keys: $Keys<S>]: string };

type Props = { classes: ClassesProp<typeof styles> };
```

**Comment by olee** [comment]
I usually type my style definitions like this:
```typescript
// helper definition
type WithStyles<K> = { [keys: K]: string };

const styles = {
  root: {
    display: 'flex',
  } as React.CSSProperties,
};
type StyleKeys = keyof typeof styles;

type Props = MyProps & WithStyles<StyleKeys>;
```
This allows proper type checking and autocomplete when writing styles and is quite easy to use.

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#806
