### ISSUE TITLE
Proposal: Make theme available as a second argument for function values

### ISSUE THREAD

**Issue by dotintegral** [cssinjs/react-jss#224]
This is a proposal for adding the `theme` argument to the function value in rule. 
### Use case:

```
const styles = {
  button: (props, theme) => {
    color: theme.primaryColor
  }
}
```

It would be an alternative for
```
const styles = theme => ({
  button: {
    color: theme.primaryColor
  }
})
```

### Motivation:
Currently, when not accessing `theme`, one can put JSS styles inside a separate file (`styles.js`) and export them using named exports, like so:

```
// styles.js file
export const button = { 
  /* ... */ 
};

export const extendedButton = {
  ...button, 
  /* ... */ 
};

export const label = { 
  /* ... */ 
};

/* .... */
```

All contents can be imported simply in the component file via: `import * as styles from './styles'`. This pattern is extremely convenient when extending the existing styles, like in `extendedButton` case.

But, when in need of using `theme` property, this pattern can't be used. One is being forced to create additional, big object that contains all of the styles, like so:

```
// styles.js file
const styles = (theme) => ({
  button: {
    color: theme.primaryColor,
    /* ... */
  },
  extendedButton: {
    /* ... */
  },
  label {
    /* ... */
  },
  /* ... */
})

export default styles;
```

Which is a bit less readable, and makes it more difficult to reuse existing styles, as the styles for button can't be easily extended. 

When having theme as a second argument, one could simply write:

```
// styles.js file
export const button = (props, theme) => ({ 
  color: theme.primaryColor,
  /* ... */ 
});

export const extendedButton = (props, theme) => ({
  ...button(props, theme), 
  /* ... */ 
});

export const label = { 
  /* ... */ 
};

/* .... */
```

**Comment by kof** [comment]
you got props.theme, have you seen that?

**Comment by dotintegral** [comment]
Was this added recently? I'm currently running `react-jss@8.1.0` and `react@16.2.0`, using `ThemeProvider` from `react-jss` and the `theme` prop is undefined. Yes, it's available inside the components code, but seems that in JSS scope it's not present.

**Comment by dotintegral** [comment]
Checked for both cases:
```
const styles = {
  button: props => {
    color: props.theme.primaryColor
  }
}
```
and:
```
const styles = {
  button:  {
    color: props => props.theme.primaryColor
  }
}
```
The `theme` property is not available in my current setup.

**Comment by HenriBeck** [comment]
Thats propably because the injectSheet doesn't see the passed in styles as themed because they are just an object. So it doesn't subscribe to the theme context and doesn't pass the theme as a prop.

Try making styles a function so the injectSheet passes the theme prop.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
Sorry I mixed it up with styled-jss, for now you can access theme from the themed styles declaration function:

```js
const styles = (theme) => ({button: {...}})
```

**Comment by dotintegral** [comment]
Thnx guys. I understand that I can have all styles inside one big function. But I think that it is much more readable and more reusable (please see the example with `extendedButton`) when developer can also use smaller objects/functions exported via named exports. Hence this proposal.

**Comment by HenriBeck** [comment]
Well, how do you use those named exports then?

I assume like so:
```js
injectSheet({
  button,
  extendedButton,
})(Component);
```

You could just do:
```js
injectSheet(() => ({
  button,
  extendedButton,
}))(Component);
```

This way you should get access to the theme inside the function rules.

**Comment by dotintegral** [comment]
> Well, how do you use those named exports then?

 Let's go with the following example, assuming that the proposal is working:
```
// file: styles.js
export const button = (props, theme) => {
  color: theme.primaryColor,
  /* ... */
}

export const extendedButton = (props, theme) => {
  ...button(props, theme)
  /* ... */
}

// other styles
```

```
// file: component.js
import React from 'react';
import injectStyles from 'react-jss'
import * as styles from './styles.js'

const Component = ({ classes }) => {
  return (
    <div>
      <button className={classes.button} >my button</button>
      <button className={classes.extendedButton} >my extended button</button>
    </div>
  );
}

export default injectStyles(styles)(Component);
```

The case is that you can have separated files for the component and the JSS styles, and inside the JSS styles you can use named exports to export small portions of styles. Then they can be reused (like in the extended button case) either within the same file or another file. Also it's much more cleaner to have couple of small functions instead of one big function.

**Comment by HenriBeck** [comment]
Then that should work:

```js
export default injectStyles(() => styles)(Component);
```

This way you will get the theme as `props.theme`. 
Adding the theme prop as the second argument is simply not possible as Jss is handling the function values.

**Comment by kof** [comment]
@dotintegral I think the reason you have one big function is because you have a huge component, which is already bad. I see your point, but it seems to me like the problem is rare and is based on a bad design.

**Comment by kof** [comment]
Out of curiosity, how many lines is your styles declaration  function?

**Comment by dotintegral** [comment]
Well, in real life projects, sometimes you need to do some sacrifices and have bigger components just to avoid having a billion of small components. Wouldn't call that a bad design though. Just finding the right balance between.  Most of the component's that I'm working with have somewhat a between 60 and 100 lines of styling. Having bigger components, that would for example have 10 css rules, is sometimes a common sense. Wouldn't blindly assume that every big component is bad by design.

**Comment by kof** [comment]
Most of the time you should split up. 10 CSS Rules should be most of the time less than 50 LOC and if you say it is a big component in your design, 100LOC styles is a  monster.
