### ISSUE TITLE
Function values not working as expected with react-transition-group

### ISSUE THREAD

**Issue by mdarens** [cssinjs/react-jss#225]
Good morning!

Recently I was migrating a component from using the imperative `sheet.addRules` API in its render method in order to pass dynamic styles to the classnames used by `CSSTransition` to one which uses function values. The old way still works, but 

Demo here:
https://codesandbox.io/s/4j1q5y86q0

Here they are side by side in the tree:
![screen capture of dev tools](https://user-images.githubusercontent.com/1239439/38372353-3732dc60-38b4-11e8-9c0a-e5b5fb5934ce.gif)

One thing I noticed is that the function values version appears to be receiving 2 sets of classnames, although I would expect the the styles from at least one of them to be visible.

versions used:
```
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-jss": "8.4.x",
    "react-scripts": "1.1.0",
    "react-transition-group": "2.3.0",
    "tinycolor2": "1.4.1"
```

**Comment by mdarens** [comment]
Also the apparent 2 sets of classnames could be a red herring. It could be devtools ui lag. I should log props to see what order they're actually changing in.

**Comment by kof** [comment]
Can you please simplify the example  by removing dependencies that are not necessarily to reproduce? Mb without transition group, just updating etc.

**Comment by mdarens** [comment]
Sure, here is a verison which does not use transitions. I thought they might be the culprit, but I guess not: https://codesandbox.io/s/7mwvp914l0

**Comment by kof** [comment]
Oh, damn, you got me here http://cssinjs.org/json-api?v=v9.8.1#support-of-important

Important inside of a string value doesn't work. It is not a JSS limitation, it is the CSSOM setProperty API. 

Please send a PR to the docs where it needs to be documented additionally, where you would have found that information.

**Comment by mdarens** [comment]
Array syntax fixed it, thanks!

**Comment by mdarens** [comment]
And seeing as how the main readme links to the detailed function values documentation, that's my own fault.

**Comment by mdarens** [comment]
Sorry to spam this issue, but do you think it would it make sense to preprocess return values from function values like so?

```javascript
const transformIfSuffix = suffix => val =>
	typeof val === "string" && val.endsWith(suffix)
		? [val.slice(0, val.indexOf(suffix)).trim(), suffix]
		: val;


const transformIfImportant = transformIfSuffix("!important");
```

**Comment by kof** [comment]
will cost you performance, function values in jss are high performance and work for animations as well

**Comment by kof** [comment]
I think also array syntax is nice… so the only problem is to make sure people read it

**Comment by mdarens** [comment]
I'm not sure how you feel about adding a warning in debug mode but people might read it there ;)

**Comment by kof** [comment]
oh yeah, good idea, in dev mode we could totally warn!

**Comment by kof** [comment]
Please create a separate issue!
