### ISSUE TITLE
Fix tests broken by symbols

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/react-jss#229]

**Comment by HenriBeck** [comment]
@kof I debugged some of the tests yesterday and couldn't seem to figure out why they were failing.
So I started to write some tests with enzyme and the tests begun to work again. (I will upload the code when I'm home from university into a separate repo).

**Comment by HenriBeck** [comment]
@kof Please revert it until I figured out why the tests are failing... Still can't seem to find any reason.

**Comment by HenriBeck** [comment]
Okay, I think I figured it out. Apparently, the Old Context API doesn't support symbols as object keys.
The new Context does support them.

Example: https://codesandbox.io/s/qk3rwr10o6

**Comment by kof** [comment]
damn, then we also need a check for this

**Comment by HenriBeck** [comment]
Well If we use the new context API we wouldn't need symbols as there can't be interfered with the new context. Though that would probably mean that we could only support React 16.3, right?

**Comment by kof** [comment]
true, so we need to revert that change alltogether

**Comment by HenriBeck** [comment]
I guess we could use that: https://github.com/jamiebuilds/create-react-context
Though that would mean a bigger rewrite of the JssProvider and the Sheet component.

**Comment by kof** [comment]
hmmm, not sure we can use it without much danger
