### ISSUE TITLE
Style functions taking in props not executing on mobx store update

### ISSUE THREAD

**Issue by zeeskhan1990** [cssinjs/react-jss#230]
I am using mobx-react, in conjunction with react-jss library for styling. 

The issue that I am facing is that **the store updates are not causing the functions in the style definition to execute with the new props**
The exact scenario can be replicated here 
[https://codesandbox.io/s/2wkw6m75kj](https://codesandbox.io/s/2wkw6m75kj)

Observations -

- I am injecting the styles first using the _injectSheet_ method of _react-jss_, followed by the mobx store injection. In this manner the store is available as props to the style rules ( which is needed to update the style dynamically on prop updates), on store updates the components are being re-rendered but the style functions are not executing.
- I have tried using both the injecting functions of mobx and react-jss as decorators instead of as functions, it causes the same behavior.

Mobx version used - 3.5.1
Mobx-react version used - 4.4.2
React-jss version used - 8.4.0
Browser - Electron 1.8.2

I would like to know that if there's something at my end that I can do to work around this issue, or if am doing something wrong here itself?

**Comment by kof** [comment]
As discussed on gitter, mobx passes a store which will not trigger componentWillReceiveProps, you need to pass the values manually or create a more generic wrapper https://codesandbox.io/s/r4o9wq0oln
