### ISSUE TITLE
prepare for react 17 (but maintain backward compat)

### ISSUE THREAD

**Issue by pradel** [cssinjs/react-jss#231]
From the react docs: `React version 17 will deprecate several of the class component API lifecycles: componentWillMount, componentWillReceiveProps, and componentWillUpdate.`

Would be great to have this library compatible :)

Can be migrated using https://github.com/reactjs/react-lifecycles-compat

Thanks!

**Comment by damianobarbati** [comment]
```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in App

componentWillMount: Please update the following components to use componentDidMount instead: Jss(Home), Jss(Layout), Jss(Nav), SideEffect(NullComponent), ThemeProvider

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Jss(Home), Jss(Layout), Jss(Nav), ThemeProvider

componentWillUpdate: Please update the following components to use componentDidUpdate instead: Jss(Home), Jss(Layout), Jss(Nav)

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by RusinovAnton** [comment]
Hey, I would like to help with this one. I need some heads up, is it correct that using following element for tests should cover all possible components with lifecycles?

```
<React.StrictMode>
  <ThemeProvider theme={theme}>
    <div />
  </ThemeProvider>
</React.StrictMode>
```

**Comment by kof** [comment]
also JssProvider and the biggest one injectSheet() HOC creator

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#802
