### ISSUE TITLE
SSR rendering breaks content property in pseudo elements (escape problem)

### ISSUE THREAD

**Issue by beholderrk** [cssinjs/react-jss#232]
Example
```
    breadcrumbs__item: {
        '&:not(:last-child):after': {
            content: '"/"',
        },
    },
```
Next result come from server
```
.Breadcrumbs-breadcrumbs__item--1-1789919010:not(:last-child):after {
    content: &quot;/&quot;;
}
```
This style not work because content property not valid.

When react-jss render this piece in client side everything is good
```
.Breadcrumbs-breadcrumbs__item--1-1789919010:not(:last-child):after {
    content: "/";
}
```
How to avoid escaping quotes in server side?

**Comment by beholderrk** [comment]
Problem found 😃  
`sheets.toString()` must be inserted through dangerouslySetInnerHTML in style component.
Like so
```
<style id="server-side-styles" type="text/css" dangerouslySetInnerHTML={{ __html: sheets.toString()}}>
</style>
```
Perhaps this nuance should be added to docs.

**Comment by kof** [comment]
👍
