### ISSUE TITLE
Recommended style object placement in projects

### ISSUE THREAD

**Issue by rdsedmundo** [cssinjs/react-jss#233]
I'd like to know if there's any kind of recommended structure for separating components and their styles, or if it's better to place them in the same file as the component file.

In short words, I'd like to know what's make more sense:

**Button.js**
```javascript
import React from 'react';
import injectSheet from 'react-jss';

const styles = {
  ...a ton of styles here
};

const Button = ({ classes }) => (
  <Button ... />
);

export default injectSheet(styles)(Button);
```

Or to have:

**buttonStyle.js**
```javascript
export default {
  ...a ton of styles here
};
```

**Button.js**
```javascript
import React from 'react';
import injectSheet from 'react-jss';

import styles from './buttonStyles';

const Button = ({ classes }) => (
  <Button ... />
);

export default injectSheet(styles)(Button);
```

**Comment by kof** [comment]
If you are able to write small components - put styles in the same file. I started with separate file per styles and after a year migrated to same file and small components.
