### ISSUE TITLE
React-JSS function rules aren't working

### ISSUE THREAD

**Issue by nai888** [cssinjs/react-jss#235]
While working on #234, I had trouble getting Function Rules to work in the [playground](https://codesandbox.io/s/j3l06yyqpw). Function Values _did_ work.

For example:

```javascript
import React from 'react'
import {render} from 'react-dom'
import injectSheet from 'react-jss'

const styles = {
  myButton: {
    padding: props => props.spacing
  },
  myLabel: (props) => ({
    display: 'block',
    color: props.labelColor,
    fontWeight: props.fontWeight,
    fontStyle: props.fontStyle
  })
}

const Button = ({ classes, children }) => (
  <button className={classes.myButton}>
    <span className={classes.myLabel}>
      {children}
    </span>
  </button>
)

Button.defaultProps = {
  spacing: 10,
  fontWeight: 'bold',
  labelColor: 'red'
}

const StyledButton = injectSheet(styles)(Button)

const App = () => (
  <StyledButton fontStyle='italic'>
    Submit
  </StyledButton>
)

render(<App />, document.getElementById("root"))
```

In the above code, which is based on the example that already exists in the docs, `myButton` was styled correctly, but `myLabel` received no styling at all.

The only way I could get it to work was if I converted the function rule to several function values:

```javascript
const styles = {
  myButton: {
    padding: props => props.spacing
  },
  myLabel: {
    display: 'block',
    color: props => props.labelColor,
    fontWeight: props => props.fontWeight,
    fontStyle: props => props.fontStyle
  }
}
```

Am I doing something wrong, or is this a bug?

**Comment by HenriBeck** [comment]
When I copy your code into a new sandbox it works for me. All of the styled are being applied correctly.
https://codesandbox.io/s/rj9x99wnm4

**Comment by nai888** [comment]
Oh, that's odd. It *does* work in a brand-new sandbox, but it *doesn't* work in the sandbox linked from the docs: https://codesandbox.io/s/j3l06yyqpw. Not sure exactly why that is.

In any case, if it's not working in that sandbox, then either the sandbox needs to be fixed or the docs should link to a different sandbox.

**Comment by HenriBeck** [comment]
I think we need to update the version of `react-jss` to `8.4.0` in the sandbox. That solved the problem for as well.

**Comment by kof** [comment]
its a caching issue in the sandbox @compulves

**Comment by kof** [comment]
I have updated react-jss dependency in the official playground, please try again

**Comment by nai888** [comment]
Aha, you're right, that's it. Updating the react-jss dependency fixes it.

Looks like your update didn't save, though. When I open it, it still loads `8.0.0`.

**Comment by kof** [comment]
ups, I wasn't logged in, now it saved
