### ISSUE TITLE
react-jss ignores @global when used within React TypeScript

### ISSUE THREAD

**Issue by nai888** [cssinjs/react-jss#238]
I'm trying to integrate `react-jss` into a React TypeScript project, and I'm having trouble with getting `global-jss` to work. The exact same code for the global styles works fine in a regular React JS project, but the TypeScript project completely ignores `@global` and instead just scopes the rule normally.

CC: @pbedat @YairoR, given your past interest in TS support for `react-jss`. Have you run into this issue at all?

**Comment by kof** [comment]
From JSS side there is nothing special that we do  for typescript. I think something is wrong with your setup, for e.g. if you did a custom plugins setup and didn't install a jss-global plugin.

**Comment by dagatsoin** [comment]
@nai888 You have to setup the global plugin with `jss.setup(preset())
jss.createStyleSheet(global).attach()` react-jss won't do it for you.

**Comment by nai888** [comment]
@dagatsoin Using global styles in regular React has been no problem with me, so clearly React-JSS *does* register the global stylesheet. It was only when I tried it in a React TypeScript project that global styles suddenly didn't work. In neither version of the project had I done any custom setup for JSS or the plugins.
