### ISSUE TITLE
Support styles testing for Jest Snapshot

### ISSUE THREAD

**Issue by kpavankotesh** [cssinjs/react-jss#243]
Problem: Unable to test styles in components

I am using cssinjs & I don't have separate style files for each component in my project. So I will not be able to import individual styles, rather I am using a single theme file to specify all the theme values. Right now I am passing on my theme to the ThemeProvider this way

```javascript
describe('Component', () => {
  it('renders correctly', () => {
    const tree = renderer
      .create(
        <ThemeProvider theme={theme}>
          <Component />
        </ThemeProvider>
      )
      .toJSON()
    expect(tree).toMatchSnapshot()
  })
})
```

But this doesn't snapshot the styles. Is there any way I can make the styles also work in the tests?

**Comment by HenriBeck** [comment]
This should work:

```js
describe('Component', () => {
  it('renders correctly', () => {
    const registry = new SheetsRegistry();
    const tree = renderer
      .create(
        <ThemeProvider registry={registry} theme={theme}>
          <Component />
        </ThemeProvider>
      )
      .toJSON()
    expect(tree).toMatchSnapshot()
    expect(registry.toString()).toMatchSnapshot()
  })
})
```

That way you can get the styles.

**Comment by kpavankotesh** [comment]
Thanks. I've tried your code. After I update my snapshots, and then when I modify the values of styles in my component, the tests are still passing. Also the snap file just has the class names and no styles in it. Not sure what am I missing here. 

I am using v8.4.0, anything specific I need to configure? @HenriBeck

**Comment by kof** [comment]
yes and ideally we need this https://github.com/cssinjs/react-jss/issues/93
