### ISSUE TITLE
[jss-expand] Function values are not called inside jss-expand block

### ISSUE THREAD

**Issue by petrkrulis** [cssinjs/react-jss#244]
See example https://codesandbox.io/s/53n8rrlw7x. Text should be red.

**Comment by petrkrulis** [comment]
Sorry, try it now with `size` please. It really doesn't work. Generated css looks like this `font-size: function size(props) { return "120px"; };`

**Comment by HenriBeck** [comment]
Ohh yeah, now I see it as well.

**Comment by petrkrulis** [comment]
There is a same problem when i try to use jss-expand inside a function value. https://codesandbox.io/s/k3n3o98wr3

**Comment by HenriBeck** [comment]
@petrkrulis could you please move this issue to the [jss](https://github.com/cssinjs/jss) repo as this has nothing to do with the React integration.

**Comment by petrkrulis** [comment]
@HenriBeck sure, it's done. Thanks for your help :)
