### ISSUE TITLE
Using props in rules sometimes returns empty results

### ISSUE THREAD

**Issue by alerizzo** [cssinjs/react-jss#245]
Hi, this is weird, and I've been testing this a long time before posting this because I was convinced I was doing something wrong. Maybe I am, but.... man, I can't really find out what it is....

I'm having issues trying to set rules using props and themes. But... not always.

This is my code:

```javascript
export const styles = theme => ({
  textInput: {
    '& > .input': {
      borderColor: (props) => (`${ props.invert ? 'transparent' : theme.colors.neutral.gray6 }`), // this works
      backgroundColor: (props) => (`${ props.invert ? theme.colors.primary.darkest : theme.colors.neutral.white }`), // this works
      // backgroundColor: (props) => (`${ props.invert ? theme.colors.primary.darkest : theme.colors.neutral.white } !important`), // this doesn't
      '&:hover': {
        borderColor: `${Color(theme.colors.primary.dark).alpha(0.35)} !important`,
        '& + .icon': {
          color: `${theme.colors.primary.dark} !important`, // this works
          // color: (props) => ( `${theme.colors.primary.dark} !important` ), // this doesn't
          // color: (props) => { return `${theme.colors.primary.dark} !important` }, // this doesn't
          // color: (props) => (`${ props.invert ? theme.colors.primary.base : theme.colors.primary.dark }`), // this doesn't
        }
      },
```
I commented lines with problems.

So, to summarize:

- In the rules below `& > .input`, if I add `!important` it breaks.
- In the rules below `& + .icon`, well... I guess that nothing will work if I pass the props...

Weird thing is, passing props works fine in other rules. And `!important` does too. So.... why in this other cases don't?

Also, if I inspect the generated CSS, all of the rules with problems are empty.

Any idea?

**Comment by kof** [comment]
- Please read JSON DSL docs related to !important and function values.
- Avoid !important, you should not need it after all. It is always a code smell.
- You don't need template strings (not an issue there)
- We have a few bug reports in the jss repo related to function values inside of nested selectors
- Avoid nesting if you can, you are using a not-scoped  class name here '& > .input'

**Comment by alerizzo** [comment]
@HenriBeck 
Sadly.... no. I've tried to encapsulate the problem but I haven't been able to do it. This only happens to me "sometimes". And it has nothing to do with react itself, npm modules folder, or whatever "context" reason you might think of. Some rules work, some don't. Some ways work, some don't. 

@kof 
Thanks! I'll try to check all of your observations. I don't really like to use `!important` either, but as I'm "over-styling" components that use Bulma styles (and I can't define those variations at SASS level, I need to do it in the context of the theme), some styles do not work without that.... or at least, I wasn't able to make it work "gracefully"...

**Comment by kof** [comment]
If source order specificity is enough to override those styles, use "insertionPoint" option/comment and place jss sheets after the others.

**Comment by kof** [comment]
If you can't reproduce it clearly, the chance is high that your problems come from bad props values or you are not doing the exact same thing.

**Comment by kof** [comment]
Please reopen once you have an actionable example and if we don't have an issue for that yet. Check the jss repository issues pls.
