### ISSUE TITLE
Any way to use bootstrap (scss) variables in styles?

### ISSUE THREAD

**Issue by smahdis** [cssinjs/react-jss#247]
Is there anyway to achieve such a thing?

```js
const styles = {
    item: {
        backgroundColor: $body-bg,
    },
};
```

**Comment by HenriBeck** [comment]
No, unless there is a way to compile the SCSS files to js files which export the variables.

**Comment by kof** [comment]
There is probably a way to extract scss variables into a json or javascript file, then load it and use it.
