### ISSUE TITLE
Injecting sheet in child component breaks jss-nested $ruleName

### ISSUE THREAD

**Issue by bmueller-sykes** [cssinjs/react-jss#249]
This may be a well-known issue, but I stumbled onto it today after much head-scratching, and figured I'd open a ticket around it.

I've got several components that all have the same stylesheet injected into them. Then, I wanted a hover effect on the parent to change the style of the child. I tore my hair out for a while trying to figure out what was going on, and I finally realized that by injecting the same stylesheet into two separate, though nested, components caused the computed styles to have different IDs. This makes sense as I think about it, but naively, I assumed that anywhere I could inject the stylesheet anywhere along the hierarchy, and everything would work. So, is this a bug or a feature?

Here's the code:

```
const wrapperStyles = {
  parent: {
    backgroundColor: 'yellow',
    '&:hover $child': {
      color: 'red'
    }

  },
  child: {
    fontSize: '2em',
    padding: 24
  }
}

class Child extends Component {
  render () {
    const { classes } = this.props;
    return (
      <div className={classes.child}>
        Child
      </div>
    )
  }
}
const WrappedChild = injectSheet(wrapperStyles)(Child)

class Parent extends Component {

  render () {
    const { classes } = this.props;
    return (
      <div className={classes.parent}>
        <WrappedChild /> {/* hovering over the parent changes nothing in this child */}
        <Child classes={classes} /> {/* hovering over the parent will change this child */}
      </div>
    )
  }
}
const WrappedParent = injectSheet(wrapperStyles)(Parent)

ReactDOM.render(
  <WrappedParent />,
  document.getElementById('root')
);
```

**Comment by AndriusBil** [comment]
Hey! I've stumbled upon the same problem. I think it makes sense that `injectSheet` generates separate class names each time you use it. I expected this to work, tho:

```javascript
const childStyles = {
    parent: {},
    root: {
        backgroundColor: 'black',
        '$parent:hover &': {
            backgroundColor: 'red',
        },
    }
};

const parentStyles = {
    root: {},
};

const Child = injectSheet(childStyles)(
    ({ classes }) => (
        <div className={classes.root}>Test</div>
    )
);

const Parent = injectSheet(parentStyles)(
    ({ classes }) => (
        <div className={classes.root}><Child classes={{ parent: classes.root }} /></div>
    )
);

ReactDOM.render(
    <Parent />,
    document.getElementById('root')
);
```

But child classes are generated without injected class names.

**Comment by AndriusBil** [comment]
As a work-around I prototyped a wrapper for injectSheet.
https://gist.github.com/AndriusBil/ee06afb1aa6db01f25335fed710aa2ad

Before generating class names for child, it replaces references denominated by `%` with parent class names.

Usage:
```javascript
const childStyles = {
    parent: {},
    root: {
        backgroundColor: 'black',
        '%parent:hover &': {
            backgroundColor: 'red',
        },
    }
};

const parentStyles = {
    root: {},
};

const Child = injectSheet(childStyles)(
    ({ classes }) => (
        <div className={classes.root}>Test</div>
    )
);

const Parent = injectSheet(parentStyles)(
    ({ classes }) => (
        <div className={classes.root}><Child classes={{ parent: classes.root }} /></div>
    )
);

ReactDOM.render(
    <Parent />,
    document.getElementById('root')
);
```

**Comment by AndriusBil** [comment]
Tried with
```javascript
const wrapperStyles = () => ({
  parent: {
    backgroundColor: 'yellow',
    '&:hover $child': {
      color: 'red'
    }

  },
  child: {
    fontSize: '2em',
    padding: 24
  }
})
```

Same problem

**Comment by kof** [comment]
I mean injectSheet(wrappedStyles())(Component)

**Comment by AndriusBil** [comment]
Doesn't seem to work

**Comment by kof** [comment]
can you make a codesandbox example please?

**Comment by AndriusBil** [comment]
Sure! https://codesandbox.io/s/zr1l3pnoym

**Comment by kof** [comment]
Oh man, now I realize how you tricked me. Parent of the second example has a class from the same sheet as its child, but a WrappedChild doesn't has its own parent from the same sheet. Of course it won't work. Referencing rules works only inside of one sheet, otherwise it would be madness.

It is not an bug and there are many ways how to do it differently. I am closing this.

**Comment by kof** [comment]
Nope, refs are resolved before you pass a classes map, redoing it on props change would be too expensive. There are much better ways to do it.

**Comment by AndriusBil** [comment]
Thx again for investing your time!

Last Q. Could you maybe give some ideas on how to style child component by parent states (hover, active and so on)?

One way it could be achieved is by passing class, that is styled inside parent.
https://codesandbox.io/s/52po2pwnw4

But this way there will be a lot of code duplication. Using my wrapper for injectSheet, I can remove hundreds lines of code.

**Comment by kof** [comment]
Do you have a real world example when you would need this?

**Comment by kof** [comment]
In general each component should be self contained and parent component should not style child component.

**Comment by AndriusBil** [comment]
Of course.

I have a table. It's rows have dark background and light text / buttons / icons. When i hover the row it should change it's background to light. But then text / buttons / icons won't be visible anymore, they must be changed to dark version. Texts, buttons and icons by itself are not simple components (they have various nesting levels), so targeting each of the component's elements inside parent inflates the row component with logic, that doesn't seem to belong there.

Also I have a card with dark background and I'm using the same button inside a card. When I hover card it changes background to light and so on.

**Comment by kof** [comment]
I see, in that case it makes sense to use javascript based events for state changes. You are trying to cut through component boundaries with css states and break the componentization. Either its a parent that knows everything about its children and there is no real decoupling or it is really decoupled and parent communicates with its children using props.

This is not a jss limitation, this is the nature of ceparating concerns and inability to hook into css states   and provide that information over javascript.

**Comment by bmueller-sykes** [comment]
@kof It wasn't my intention to trick you. (-;

The use-case for me is that I have a set of related components (in this particular case, a Kanban board). Sure, I could have written the whole kanban board as one giant component, but that's not a particularly good practice, so I broke up the code along logical lines. The individual components will likely never be used outside of this context, and they will all naturally share the same set of styles. So, naively, I injected the same stylesheet into each component, which caused the original issue I raised in this thread. The problem arose when I wanted to change the styles on a child component based on `hover` behavior on the parent. For example, hover over a kanban column, and change the background color of a card on that column. 

The solution is (obviously) to inject the styles once, then explicitly pass the injected `classes` down to all children. That's ever-so-slightly less elegant, but I don't see any other solution, unless there's a way we can "pre-compile" the JSS stylesheet (e.g. with a custom prefix on class names, or whatever), and then we could inject that pre-compiled sheet into each component. But I don't know that this really wins us anything in particular.

**Comment by kof** [comment]
As I said, in such case use javascript events and pass props to the children. Let children style themselves and react to props.

**Comment by kof** [comment]
I think using css states for something like hover to change a complex styling of a number of complex components inside of some container is not something you can do nicely with css without breaking encapsulation.

**Comment by bmueller-sykes** [comment]
I think you're right, so it's a tradeoff. Preserving encapsulation is good to a point, but for components that will never be used outside of a single context, going to all the trouble of encapsulation doesn't seem worth the effort.

**Comment by kof** [comment]
Depending on how complex they are it might still be worth the effort, because . you would have styling coupled with inner components instead of container.

**Comment by kof** [comment]
For a simplistic case you can just create one sheet in container and pass classes to the child.
