### ISSUE TITLE
Use of react-jss on component breaks ReactTransitionGroup

### ISSUE THREAD

**Issue by dwighthouse** [cssinjs/react-jss#25]
ReactTransitionGroup, the [official low-level animation system for React](https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup), will not function when child components of said ReactTransitionGroup are wrapped by react-jss's `useSheet`.

I believe this is because React expects to directly call the additional lifecycle methods on the child components. Since moving to the new form of higher-order components using decorators, rather than using mixin functionality, the wrapping react-jss class will not have these methods nor propagate their call to the actual children.

These animation methods will not fire on the child component when that child component is wrapped with a `useSheet` call.

* `componentWillAppear(callback)`
* `componentDidAppear()`
* `componentWillEnter(callback)`
* `componentDidEnter()`
* `componentWillLeave(callback)`
* `componentDidLeave()`

Here is a small example that shows the failure. Load this module within an existing project (it should be self-contained). Press the button to add new child items. They will load, but the transition function (`componentWillEnter()` in this case) will not be called. However, the children added will be styled. Now, swap out the commented-out code (the `var WrappedTestChild` lines). Doing the same thing will cause the transition function to be called, but no styling will be applied (because it was never wrapped).

```
'use strict';

var React = require('react');
var ReactTransitionGroup = require('react-addons-transition-group');

var jss = require('jss').create();
var useSheet = require('react-jss')(jss);

var Styles = {
    testStyle: {
        padding: '10px'
    }
};

var TestChild = React.createClass({
    componentWillEnter: function(callback) {
        console.log('Got to componentWillEnter');
        callback();
    },
    render: function() {
        // Have to check for existence only for this test case, because the styles will not be there if useSheet is not called
        var classes = ((this.props.sheet || {}).classes || {}).testStyle || '';
        return (
            <div className={classes}>
                Test
            </div>
        );
    }
});

// This one will not log 'Got to componentWillEnter', but styles applied
var WrappedTestChild = useSheet(TestChild, Styles);

// This one will log 'Got to componentWillEnter', but has no styles applied
// var WrappedTestChild = TestChild;

var Test = React.createClass({
    getInitialState: function() {
        return {
            childCount: 1
        };
    },
    addChild: function() {
        this.setState({
            childCount: this.state.childCount + 1
        });
    },
    render: function() {
        var children = [], i;
        for (i = 0; i < this.state.childCount; i += 1)
        {
            children.push(
                <WrappedTestChild key={i} />
            );
        }

        return (
            <div>
                <button onClick={this.addChild}>Add Child</button>
                <ReactTransitionGroup>
                    {children}
                </ReactTransitionGroup>
            </div>
        );
    }
});

module.exports = Test;
```

Related issues:

* [Accessing original component #15](https://github.com/jsstyles/react-jss/issues/15)
* [Added a ref value to the DecoratedComponent #17](https://github.com/jsstyles/react-jss/pull/17)

**Comment by kof** [comment]
Interesting, so ReactTransitionGroup doesn't support higher order components in general. I wonder why this is not issue with lots of others higher order components ... need to have a closer look into ReactTransitionGroup as I didn't use it yet.

**Comment by kof** [comment]
@dwighthouse I was going through the issues right now and realized I didn't answer you. Could you make any progress on this already?

**Comment by dwighthouse** [comment]
No. This is still just as broken, as far as I know. Currently, I simply removed animations from my project (not a long-term solution by any means). I do not know that anyone has solved this, as it seems to be an inherent limitation of decorating components.

JSS could make an exception and forward calls on the decorated object to the child component for API functions associated with any official React API (including the plugins).

**Comment by vieks** [comment]
Omg I spent 2 hours with that bug before realize the problem come from  the **react-jss** HOC.

I use double decorations (ES6) on my components:

```javascript
export default style(gsap(Notice), styles);
```
With react ReactTransitionGroup low level API, and the probleme is only about your enhencer component not the others.

For example, If I remove react-jss and keep the [gsap](https://github.com/azazdeaz/react-gsap-enhancer):

```javascript
export default gsap(Notice);
```
Everything works well: Transition is OK.

This is a serious problem and It came from the react-jss HOC not the ReactTransitionGroup addon.

**Comment by kof** [comment]
So you can tell what exactly is the problem? How is react-jss hoc breaking breaking the other hoc? also have you tried to switch the order?

**Comment by vieks** [comment]
Of course I tried to swap the HOC ordering, but same result. And I chose this ordering exactly because the first time I start playing with **react-jss** I got another bug (don't remember its too old, Its something like styles just won't apply) so I keep this order since this time.

I havn't enough time to investigate futher on why the HOC breaks the chain, but for sure it came from it.
The only thing I can do why my time management, is posting short code snippet when the problem happens.

**Comment by vieks** [comment]
>  I got another bug (don't remember its too old, Its something like styles just won't apply) so I keep this order since this time.

I have make a test, and If I swap the order, GSAP animations just doesn't work anymore...

```javascript
Uncaught TypeError: this.addAnimation is not a function
```

Definitively, the **react-jss** HOC/enhancer break up.

**Comment by imjasonmiller** [comment]
I am not sure if this is entirely relevant @dwighthouse  @vieks and @kof as I am not using `jsstyles` but a `withStyles` higher-order component from [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader) for Webpack.

I also have limited knowledge of React, but I am currently looking into it after thinking for an hour that the [gsap](https://github.com/greensock/GreenSock-JS) animation library was the cause of `react-addons-transition-group` not working. It seems that is not the case, as `componentDidEnter` is triggered as expected by removing the `withStyles` higher-order component.

Doesn't `react-addons-transition-group` also depend on the `key` and `ref` values? The [documentation](https://facebook.github.io/react/docs/animation.html) states:

> **Note:**
> You must provide the key attribute for all children of ReactCSSTransitionGroup, even when only rendering a single item. This is how React will determine which children have entered, left, or stayed.
> 

They aren't passed along from what it seems when I inspect my components using the [React Developer Tools](https://facebook.github.io/react/blog/2015/09/02/new-react-developer-tools.html):

![image](https://cloud.githubusercontent.com/assets/12190184/15927806/f365c1ae-2e43-11e6-93d4-a49ce727be8d.png)
_With the higher-order component on the left and without on the right._

It looks like `gsap-enhancer` attaches the `keys` and `refs` of the component that was passed in [here](https://github.com/azazdeaz/react-gsap-enhancer/blob/master/src/attachRefs.js).

I realize that what I am using might not have much in common with `jsstyles`, but perhaps it has something to do with it?

**Comment by kof** [comment]
I  am curious if hoistNonReactStatics has potentially fixed those issues, does anybody know?

**Comment by umidbekkarimov** [comment]
Same here - https://github.com/reactjs/react-redux/issues/303 and I agree with https://github.com/reactjs/react-redux/issues/303#issuecomment-189864169
