### ISSUE TITLE
Styles as functions of props override styles as values

### ISSUE THREAD

**Issue by kavehsajjadi** [cssinjs/react-jss#251]
Hey there, I had a look around issues and didn't see anything that seemed to be the same but the issue also feels like the kind you'd probably already be aware of. Sorry if it's known / a deliberate decision.

The problem is styles created using functions seem to override styles created using values. 

An example of the problem:
```
const styles = {
    breaks: {
        background: props => props.background || '#fff',
        ['@media(min-width: 1024px)']: {
            background: '#000' // this guy doesn't override the css 2 lines up
        }
    },
    works: {
        background: props => props.background || '#fff',
        ['@media(min-width: 1024px)']: {
            background: props => '#000' // using a props function fixes it though
        }
    }
}
```

**Comment by HenriBeck** [comment]
I think that might be because of the injection order🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HenriBeck** [comment]
Could you create a codesandbox where the issue happens?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
Yes, this is true, dynamic rules are rendered after the static once. A case with media query is valid, I consider it a bug.

**Comment by kof** [comment]
The problem is we can't really have reuse of static styles between elements and at the same time maintain this order.

I don't see a good solution here. We could stop extracting static styles and just turn them all into dynamic as soon as you have at least one dynamic property. This way we don't have this issue but we also don't have styles reuse between component instances.

**Comment by kof** [comment]
Or we just document function values the way they behave and don't treat it as a bug. Same thing would happen with inline styles.

**Comment by HenriBeck** [comment]
I think for this case, simply make the `backgroundColor` in the media query also a function or make the whole class a function. I don't think there would be an easy solution for this on our end and removing the reuse of styles between components seems too big for a tradeoff.

**Comment by kavehsajjadi** [comment]
@kof I didn't even know until just before that dynamic styles don't get reused (although I should have noticed immediately looking at the fairly specific classnames that get generated).
I had to keep coding when I reported this and ended up doing what @HenriBeck suggested, it's not the prettiest but it gets the job done.
If it gets bad I suppose I can always toggle classnames on props instead

**Comment by kavehsajjadi** [comment]
Lol @HenriBeck I actually went the other way. I was using props for theming but I made a utility function that takes
```
{
    someRootClass: true,
    someThemeClass: props => (props.theme === 'dark')
}
```

Class toggling solves all my issues without significantly increasing number of keys for -most- of my components

**Comment by kavehsajjadi** [comment]
The price we pay for living in browserland I guess, we can just selectively do both depending on the class of problem being solved?. conveniently the fn values override the other values anyway :P

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/jss/issues/682
