### ISSUE TITLE
dynamic class bug on `overflow` property

### ISSUE THREAD

**Issue by damianobarbati** [cssinjs/react-jss#254]
Here what I'm experiencing (using `"react-jss": "^8.4.0"`):

working =>
```
tbody: {
    width: '100% !important',
    overflow: 'overlay !important',
},
```
not working =>
```
tbody: ({ rects }) => ({
    width: '100% !important',
    overflow: 'overlay !important',
}),
```

In the latter the `overflow` property is not added to the class at all.

**Comment by kof** [comment]
So far in function values/rules we have this syntax for !important http://cssinjs.org/json-api?v=v9.8.4#support-of-important
