### ISSUE TITLE
Readd forwardRef support

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#256]
It was removed due to issues with redux-connect and the fact that it needs a major release, see #255 

Now we need to understand how redux-connect and similar can be supported.

**Comment by HenriBeck** [comment]
I don't think we can support react-redux in any way, rather we need to wait for react-redux to not check against a function and rather against a valid react element described [here](https://github.com/reduxjs/react-redux/issues/914#issuecomment-377406014)

**Comment by kof** [comment]
Yeah, but how can we release react-jss with forwardRef support without making it incompatible with so  many react-redux versions?

**Comment by HenriBeck** [comment]
I don't think we can.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
Well, then if somneone wants to use forwardRef api, he will have to wrap injectSheet with his own wrapper and use it. I am closing this for now.

**Comment by kof** [comment]
Lets release this change in a major version as soon as https://github.com/reduxjs/react-redux/issues/914 is fixed

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#800
