### ISSUE TITLE
StyleSheet injection order

### ISSUE THREAD

**Issue by jeremie-stratumn** [cssinjs/react-jss#257]
I have an issue related to the style sheet injection order. Say I create a React component library that exports a `Button`:

```
// MyLib/index.js
export const Button = 
  injectSheet({ root: { color: 'blue' } })
    (({children, classes, className}) => 
      <button className={classnames(classes.root, className)}>{children}</button>)
``` 

Now I want to use this `Button` in my App:
```
// MyApp/menu.js
import { Button }  from 'mylib';

export const Menu = injectSheet({ button: { color: 'red' } })
  (({classes}) => <Button className={classes.button}>Click Me</Button>
```

In this scenario, I'd expect the `button` element in Menu to be red and this is how I understand this part of the documentation: https://github.com/cssinjs/react-jss/#injection-order
> Style tags are injected in the exact same order as the injectSheet() invocation. Source order specificity is higher the lower style tag is in the tree, therefore you should call injectSheet of components you want to override first.

In practice this is what I see, so it works fine, except when I am developping both MyLib and MyApp at the same time so linking MyLib in MyApp: `yarn link mylib`. In that case, I have noticed some order issue. The button element has 2 classes that look like this:
- `Button-root-1-1-1` -> this is coming from the first `injectSheet` in MyLib
- `Menu-button-0-1-2` -> from the second `injectSheet` in Menu
In this scenario, the `Button-root-1-1-1` class wins and the button is blue and not red..

I've noticed that the `moduleId` number differs between the two. Could it be the issue? I tried using a `JssProvider` with `classNameGenerator` prop in MyApp as explained here https://github.com/cssinjs/react-jss/#multi-tree-setup which seems to keep the `moduleId` to 0 but still I see the same css conflict.

Any idea on how to solve this?

Thanks

**Comment by kof** [comment]
if module id differs, you included multiple versions of JSS in your bundle, try to fix that and use one version.

**Comment by jeremie-stratumn** [comment]
Thanks @kof for your prompt response. When doing a `yarn link` you do not expect this happening right?

**Comment by kof** [comment]
Can't tell, not using yarn, but you can check what version ends up in the bundle in the various ways.
