### ISSUE TITLE
react-hot-loader doesn't hot replace changes to react-jss styles

### ISSUE THREAD

**Issue by cjevning** [cssinjs/react-jss#258]
This seems unrelated to https://github.com/cssinjs/react-jss/issues/117 but it may be.

I've set up a minimal repo to show the issue here: https://github.com/cjevning/jss-hot-broken

Essentially, HMR works as expected when changing any component code, inline component styles, or theme values (theme value changes require a full reload, which makes sense), however it fails to replace existing jss styles. Webpack-dev-server is aware of the changes and claims to update the modules, but the changes aren't reflected.

In the example repo above, changing the injected styles for Counter or Counter3 has no effect until refresh, while changing Counter2's inline styles hot swap fine. WDS seems to think all of the changes have been swapped:
![screenshot from 2018-06-13 15-08-12](https://user-images.githubusercontent.com/4167923/41381998-023a812e-6f1f-11e8-9058-10f8c135f33e.png)

Ultimately this may be related more to webpack-dev-server itself, as a similar codesandbox example seems to handle jss style changes, albeit while losing the internal component state: https://codesandbox.io/s/zk29z664ml

**Comment by kof** [comment]
#117 is the right issue I think. We still haven't implemented a proper integration, also see https://github.com/cssinjs/react-jss/pull/123
