### ISSUE TITLE
Add disable styles generation

### ISSUE THREAD

**Issue by in19farkt** [cssinjs/react-jss#259]
Hello, is there a way to render without styles generation? For example Material UI [provide](https://material-ui.com/api/mui-theme-provider/#__next) us with prop `disableStylesGeneration` and it is pretty convenient to use for traversing React component tree without side effects:

> You disable the generation of the styles with this option. It can be useful when traversing the React tree outside of the HTML rendering step on the server. Let's say you are using react-apollo to extract all the queries made by the interface server side. You can significantly speed up the traversal with this property.

We could not use `react-async-bootstrapper` without such prop because it will lead to the generation and injection of styles before the `ReactDom.render` is called.

**Comment by kof** [comment]
we created an issue for this https://github.com/cssinjs/react-jss/issues/167

Not generating styles also means you won't have proper classes injected, so its really for the use case described in MUI.

**Comment by kof** [comment]
Would you like to implement this?
