### ISSUE TITLE
react-jss is not transpiling correctly when using dynamic values and nesting

### ISSUE THREAD

**Issue by abelosorio** [cssinjs/react-jss#260]
Hi all!

First, I'm sorry if I'm repeating something or if the solution for this issue is already documented, but I couldn't find anything related.

Second: I'm not sure if this is an issue in `react-jss` or in the plugin `jss-nested`.

## My code is:
`styles.js`:
```
export default (theme) => ({
  app: (props) => ({
    '& .btn-default': theme.buttons.defaultStyle,
    '& .btn-primary': theme.buttons.primaryStyle,
    '& .btn-success': theme.buttons.successStyle,
    '& .btn-info': theme.buttons.infoStyle,
    '& .btn-warning': theme.buttons.warningStyle,
    '& .btn-danger': theme.buttons.dangerStyle,
    '& h1': theme.fonts.h1,
    '& h2': theme.fonts.h2,
    '& h3': theme.fonts.h3,
    '& h4': theme.fonts.h4,
    '& h5': theme.fonts.h5,
    '& a': theme.fonts.link,
    '& a:hover': theme.fonts['link:hover'],
    '& .form-control': theme.formInputs.formControl,
    '& .form-group': theme.formInputs.formGroup,
    '& label': theme.formInputs.controlLabel,
    '@media (min-width: 1200px)': {
      '& .container': {
        maxWidth: '1500px'
      }
    }
  })
});
```

*Each value is an object with different CSS properties.*

## What I get:
```
<style type="text/css" data-jss="" data-meta="App, Themed, Dynamic">
.App-app-0-1-2 {
  & .btn-default: [object Object];
  & .btn-primary: [object Object];
  & .btn-success: [object Object];
  & .btn-info: [object Object];
  & .btn-warning: [object Object];
  & .btn-danger: [object Object];
  & h1: [object Object];
  & h2: [object Object];
  & h3: [object Object];
  & h4: [object Object];
  & h5: [object Object];
  & a: [object Object];
  & a:hover: [object Object];
  & .form-control: [object Object];
  & .form-group: [object Object];
  & label: [object Object];
  @media (min-width: 1200px): [object Object];
}
</style>
```

## What I expect:

The `App-app-0-1-2`'s values correctly transpiled to CSS.

Am I missing something?

Thanks in advance
cc @sergioshev

**Comment by kof** [comment]
Yes, this is something we need to add support for https://github.com/cssinjs/jss/issues/682

**Comment by abelosorio** [comment]
Ok. Thanks @kof! I have not seen that issue.

**Comment by DurgaPammi** [comment]
how can we right the JSS for the below example :

             <Collapsible trigger="Start here">
    <p>This is the collapsible content. It can be any element or React component you like.</p>
                  </Collapsible>
CSS is:

.Collapsible__trigger {
display: block;
font-weight: 600;
text-decoration: none;
color: #ffffff;
position: relative;
border: 1px solid white;
padding: 10px;
background: #f3f4f4;
color: black;
}
.Collapsible__trigger:after {
font-family: 'FontAwesome';
content: '\f107';
position: absolute;
right: 10px;
top: 10px;
display: block;
transition: transform 300ms;
}
.Collapsible__trigger.is-open:after {
transform: rotateZ(180deg);
}
.Collapsible__trigger.is-disabled {
opacity: 0.5;
background-color: grey; }


JSS code is:

refineContainer: {
    border: '1px solid',
    '@global': {
      '& > span > & .Collapsible__trigger': {
        display: 'block',
        fontWeight: '600',
        textDecoration: 'none',
        position: 'relative',
        border: '1px solid white',
        padding: '10px',
        background: '#f3f4f4',
        color: 'black',
        '&::after': {
          fontFamily: 'FontAwesome',
          content: '\f107',
          position: 'absolute',
          right: '10px',
          top: '10px',
          display: 'block',
          transition: ' transform 300ms',
        },
        '&::is-open:after': {
          transform: ' rotateZ(180deg)',
        },
        '&::is-disabled': {
          opacity: '0.5',
          backgroundColor: 'grey',
        },
      },
    },
  },

Can You please any one help me about this
