### ISSUE TITLE
How to use component classnames in other components?

### ISSUE THREAD

**Issue by dannystyleart** [cssinjs/react-jss#262]
Hello!

We are just started using React-jss in our ui-kit project and just faced with this problem:

We have sibling components like IconButton, Button, Dropdown, each as a separate component.

We have a ButtonGroup component which needed because of design. In ButtonGroup we have to overwrite some styles and match the components inside with nested selectors.

We have discovered the composes property in rules which is useful in local scope.

Is there a way to use composes or somehow get the generated classnames by component name to match those children components?

Thanks in advance,
D

**Comment by kof** [comment]
As far as I can understand your use case from the description, you want to reach into internals of a child component. This is a generally bad practice in a component world. It was  a way to go with plain CSS but is an anti-pattern with components. Pass the props you need from the parent to the child and let child adapt according to the props. Additionally you can leverage the context if you need to. 
I think you can find a plenty of inspiration in the material-ui library which is also using JSS
https://material-ui.com/

**Comment by dannystyleart** [comment]
Yeah generally I'd like to achieve the same thing but could not (yet) find that solution because mui - as far as I know - using an own implementation of has provider with custom utilities

**Comment by kof** [comment]
They don't use any other utilities for your use case other than props and context.
