### ISSUE TITLE
Dynamic rules are rendered before the static ones

### ISSUE THREAD

**Issue by doasync** [cssinjs/react-jss#269]
Check this: https://codesandbox.io/s/3qqjrq77m5

Login button should be red, but it's white.

I guess, the bug occurs when the insertion point is at the end of the head.

**Comment by kof** [comment]
Weird, renaming insertion point to anything else fixes it.

**Comment by kof** [comment]
Not sure what that is, might be something in MUI as well, needs further investication.

**Comment by kof** [comment]
Oh, that was basically "not specifying the insertionPoint" fixes the issue

**Comment by kof** [comment]
Bug is 90% in mui.

**Comment by kof** [comment]
@oliviertassinari is it possible that mui fails to read the insertionPoint from context somehow?

**Comment by kof** [comment]
@doasync same behaviour with regular value, so fn value has nothing to do with it. It is probably that jss from react-jss receives the insertion point and mui doesn't so react-jss renders after it since it doesn't need to sort with the same namespace.

**Comment by oliviertassinari** [comment]
I can reproduce the same issue without Material-UI: https://codesandbox.io/s/wkky8j6rv8

**Comment by kof** [comment]
@oliviertassinari thanks for reproduction, you are right

It seems like the style sheet with dynamic values doesn't consider the static one when sorting and there is a defined insertion point

**Comment by HenriBeck** [comment]
Could it be that both sheets get the same index, but as the dynamic sheet is created after the static one, it places the element before the other one?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#798
