### ISSUE TITLE
Move JssProvider into own package

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/react-jss#270]
I was thinking about moving the JssProvider into it's own package for reuse in styled-jss or for other packages to integrate easier without including react-jss.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
Its possible if its worth it.

**Comment by TrySound** [comment]
Or we can just treeshake out unused stuff and do not care about one more package.

**Comment by TrySound** [comment]
I would even move styled-jss into this package.

**Comment by kof** [comment]
Since we have monorepo and separating packages is cheap now, I would rather tend to split into more packages where it makes sense I guess?
