### ISSUE TITLE
Error with flowtype and classes props

### ISSUE THREAD

**Issue by fseglard** [cssinjs/react-jss#273]
Hi there!

When using flowtype for props validation I always have this error:
```Property `classes` is missing in props [1] but exists in Props [2].```

Here's an example to reproduce this error:

**DummyComponent.js**
```jsx
// @flow
import React from 'react';
import injectSheet from 'react-jss';
import type {Classes} from 'react-jss';

// Styles
const styles = {
  root: {
    color: 'red'
  }
};

// Types
type Props = {
  classes: Classes<typeof styles>,
  content: string
};

class DummyComponent extends React.Component<Props> {
  render() {
    const {classes, content} = this.props;

    return (
      <div className={classes.root}>
        {content}
      </div>
    );
  }
}

export default injectSheet(styles)(DummyComponent);
```
**OtherComponent.js**
```jsx
// @flow
import React from 'react';
import injectSheet from 'react-jss';
import type {Classes} from 'react-jss';

// DummyComponent
import DummyComponent from './DummyComponent';

// Styles
const styles = {
  root: {
    color: 'blue'
  }
};

// Types
type Props = {
  classes: Classes<typeof styles>
};

class OtherComponent extends React.Component<Props> {
  render() {
    const {classes} = this.props;

    return (
      <div className={classes.root}>
        <DummyComponent content="Hello world!" /> {/* Flow throws the error here */}
      </div>
    );
  }
}

export default injectSheet(styles)(OtherComponent);
```
I'm using `flow-typed` with this `react-jss` definition: https://github.com/flow-typed/flow-typed/pull/2277/files

When I run the tests for this definition, everything looks good, so I don't understand...

Here is my packages version:
```
flow-bin@0.75.0
flow-typed@2.4.0
react@16.4.1
react-jss@8.6.0
```

**Comment by kof** [comment]
where did you get `Classes<typeof styles>` from ?

**Comment by fseglard** [comment]
From the `react-jss` package:
```
import type {Classes} from 'react-jss';
```

`styles` is the const containing the component styles

**Comment by kof** [comment]
yes, but thats not what classes is, classes is a map of a rule name and class name `{ruleName: className}`

**Comment by fseglard** [comment]
I follow the same logic from the definition tests file : https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-jss_v7.x.x/test_react-jss_v7.x.x.js

But maybe i'm doing it wrong?

**Comment by kof** [comment]
https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-jss_v7.x.x/test_react-jss_v7.x.x.js#L20

**Comment by kof** [comment]
its basically says it is type of object

**Comment by HenriBeck** [comment]
It's a problem with the return type of the injectSheet function. Currently, flow thinks that the classes prop are required.

**Comment by fseglard** [comment]
Yes @HenriBeck, that's the exact problem I'm facing. Do we have a workaround for this?

**Comment by HenriBeck** [comment]
You need to remove the classes key from the returned component. I think it's [this](https://github.com/flow-typed/flow-typed/pull/2277/files#diff-36b5db5d7e9f09f3ab18aa84593122efR17) one. You can do that by the `$Diff` type.

```js
declare class ConnectedComponent<OP, P, Def, St> extends React$Component<$Diff<OP, { classes: any }>, St> {

```

**Comment by fseglard** [comment]
I got this error with this change:
```
Cannot extend React.Component [1] with ConnectedComponent because inexact OP [2] is incompatible with exact $Diff [3]in property props.
```

**Comment by kof** [comment]
but classes IS required

**Comment by fseglard** [comment]
Yes but `classes` is injected by `react-jss`, we can't pass it as props when we call the `<DummyComponent>`, but Flow thinks that `classes` is required as props so it throws the error.

**Comment by kof** [comment]
Oh I see now, its about telling flow that the classes are injected by injectSheet …

**Comment by fseglard** [comment]
Yes :)

**Comment by HenriBeck** [comment]
@fseglard i can give you my definition when I'm home. I doesn't have the error

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fseglard** [comment]
Thanks @HenriBeck!

**Comment by HenriBeck** [comment]
@fseglard https://gist.github.com/HenriBeck/438f0cbd6c6168ccced47287b0d61f0e#file-react-jss-js that's how I typed it. I don't know if it works anymore, might wanna try it out before and make sure it works as expected

**Comment by kof** [comment]
@HenriBeck Lets make sure this is fixed for everyone!

**Comment by HenriBeck** [comment]
@kof yeah thought about adding flow to this project🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
I am for it, but didn't have time, if you are using it with flow and its an easy thing for you, go ahead!

**Comment by fseglard** [comment]
@HenriBeck could you provide me an example of how you use your definition please?

**Comment by HenriBeck** [comment]
I think you should be able to use it the same way you did.

**Comment by kof** [comment]
I am gonna close this, @HenriBeck feel free to open a new one if you want to add typings to react-jss
