### ISSUE TITLE
Add flowtype support

### ISSUE THREAD

**Issue by HenriBeck** [cssinjs/react-jss#274]
As the `jss` libary is already using flow, we could add flow to this one as well.

**Comment by HenriBeck** [comment]
Probably won't be in the near future as I'm currently working on migrating the plugin repos to the monorepo.

**Comment by gomesalexandre** [comment]
@kof I would like to contribute the flow support for this repo, is it something that you would be interested in ?

**Comment by HenriBeck** [comment]
Sure, go ahead. Create a PR and we will review it.

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#797
