### ISSUE TITLE
Is there any way of selecting a theme between two different channels in themed styles declaration function?

### ISSUE THREAD

**Issue by alc0034** [cssinjs/react-jss#276]
We are using `Material UI` and our own custom components library which is using `react-jss`.

The providers are nested like: 

```
<MuiThemeProvider theme={MUItheme}>
     <CustomComponentsProvider theme={customTheme}>
        <MaterialUIComponent />
        <OwnComponent />
     </CustomComponentsProvider>
</MuiThemeProvider>
```

And for our custom theme provider, we are creating a custom channel:

```
// custom.provider.js

import { createTheming } from 'react-jss';

export const THEMING = createTheming('CUSTOM_UI_COMPONENTS_THEME');
const { ThemeProvider: CustomComponentsProvider } = THEMING;

....

```

The issue comes up in our components when we tried to create the styles with `themed styles declaration function`, we found that the theme passed as parameter is the MaterialUI theme `MUITheme` instead of `customTheme`.

```
// OwnComponent.js

import * as React from 'react';
import injectSheet from 'react-jss';
import {THEMING} from './custom.provider';

const styles = (theme) => {
  // theme is always Material UI theme 

  button: {
    color: theme.primaryColor
  }
};

class OwnComponent extends React.Component {
  ....
}

export const OwnComponent = injectSheet(styles, {THEMING})(OwnComponent);

```

If we remove the custom channel and use the default provider `ThemeProvider`, in that case, both themes are merged and we can access to the properties of both.

Is there any way of getting the specific theme from our custom provider `<CustomComponentsProvider theme={customTheme}>` in the `themed styles declaration function`?

**Comment by HenriBeck** [comment]
That should fix your problem:
```js
export const OwnComponent = injectSheet(styles, {theming: THEMING})(OwnComponent);
```

**Comment by alc0034** [comment]
@HenriBeck That fixes the issue! Thank you 👍
