### ISSUE TITLE
Refs not forwarding

### ISSUE THREAD

**Issue by ralphsmith80** [cssinjs/react-jss#277]
According to the [README](https://github.com/cssinjs/react-jss#the-inner-ref) refs should be forwarded. 

Here's a [codesandbox example](https://codesandbox.io/s/o54lj508r5). You'll need to open view the console to see the following error. 

```
sandbox.c7332c5c.js:1 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Jss(Component)`.
    in Unknown (created by Jss(Component))
    in Jss(Component) (created by InnerReference)
    in InnerReference
    in Reference (created by App)
    in Manager (created by App)
    in div (created by App)
    in App (created by Jss(App))
    in Jss(App)
```

The example provided implies it forwards to functional components so I expected this to work. I plan to update it to class component to see if that fixes the issue. 

Also to note I tried `innerRef` and `ref`.

Versions:
react: 16.3.2
react-jss: 8.6.1

**Comment by ralphsmith80** [comment]
Tried this with `class` and `React.forwardRef`. No dice.

https://codesandbox.io/s/o54lj508r5

**Comment by HenriBeck** [comment]
We had to take out the `React.forwardRef` because it hat problems with react-redux connect function.
The `innerRef` can only work if the inner component is a class component.

https://codesandbox.io/s/v0xy2656wy

**Comment by HenriBeck** [comment]
So you want to have a reference to the button component and not your actual 'component'. Then yeah, you need some other name. Currently, the `ref` prop will give you the Jss instance because we had to remove `React.forwardRef` and the `innerRef` prop gives you the reference to your wrapped component.
