### ISSUE TITLE
Wrong style order in webkit browsers

### ISSUE THREAD

**Issue by bungu** [cssinjs/react-jss#278]
I'm not sure if this is `react-jss` or `jss` issue.

In webkit-based browsers (Chrome, Safari, Mobile Chrome for Android) styles attach in a wrong order in my project. It works as expected in FF and in a server-side rendering. Could you help me find the source of this behaviour?

This is style order in chrome:
![chrome 2018-07-11-14 41 21](https://user-images.githubusercontent.com/1529956/42569297-ba3b816a-8518-11e8-8da7-f9e7582d7157.png)
![chrome-screenshot](https://user-images.githubusercontent.com/1529956/42569440-2e083714-8519-11e8-845b-181ded2285bb.png)

Same code in firefox:
![firefox 2018-07-11-14 42 01](https://user-images.githubusercontent.com/1529956/42569298-ba5ecf8a-8518-11e8-89e4-f1b6e2ffbd0f.png)
![ff-screenshot](https://user-images.githubusercontent.com/1529956/42569441-2e2d04f4-8519-11e8-89b6-43575f05aefa.png)

Second, third and fouth `<Alert>` background property is replaced by `<Panel>` background style. As far as i know it caused by [ThemeProvider inside Alert](https://github.com/bungu/jss-wrong-style-order-example/blob/master/lib/Alert/index.tsx#L11) ([StyleContextProvider source code](https://github.com/bungu/jss-wrong-style-order-example/blob/master/provider/context.tsx)). But I need it to redefine color palette for Alert children.

Repo with project: https://github.com/bungu/jss-wrong-style-order-example

I tried to reproduce it in codesandbox, but it works fine: https://codesandbox.io/s/z31znxv6vm

**Comment by bungu** [comment]
It seems that this code works fine only on server and in FF on MacOS X. Every browser on Windows behave like Chrome (even FF).

**Comment by kof** [comment]
So your problem is related to your SSR setup. It has nothing to do with how runtime css is generated.

**Comment by bungu** [comment]
Thanks for the clue. I copied example from codesandbox to my project and it is rendering with wrong order too. Probably it is issue with my setup.

But I still don't understand why runtime css in FF is different from runtime css in Chrome. I thought the order of `<style>` is the same order of react components mounting.

**Comment by kof** [comment]
I opened your codesandbox example in FF and Chrome, it looks same to me.

**Comment by bungu** [comment]
SSR related code is here at the end of the file: https://codesandbox.io/s/18vj538joq

Example in codesandbox works as expected. It is not works in my demo project: https://github.com/bungu/jss-wrong-style-order-example

**Comment by bungu** [comment]
@kof this bug occures when JSS insertion point is the last child of `<head>`. It is not related to specific browser. Codesandbox add some elements at the end, that's why it's impossible to reproduce bug here. So, it's a bug of DomRenderer from package `jss`. I'll add issue tomorrow afternoon.

# How it works

React tree:
```xml
<Root>
  <Alert data-id="0">
    <Panel data-id="0-0" />
  </Alert>
  <Alert data-id="1">
    <Panel data-id="1-0" />
  </Alert>
</Root>
```

Styles:
```css
.alert { background: #F00 }
.panel { background: #FFF }
```
Attaching styles order:
1. Alert 0
2. Panel 0-0
3. Alert 1
4. Panel 1-0

`Alert 0` attached as expected at insertion point because there is no other sheet attached.
`Panel 0-0` attached above `Alert 0` because there is [higher sheet](https://github.com/cssinjs/jss/blob/master/packages/jss/src/renderers/DomRenderer.js#L227).
`Alert 1` has no higher sheet, that is why it finds [highest sheet](https://github.com/cssinjs/jss/blob/master/packages/jss/src/renderers/DomRenderer.js#L231) `Alert 0`. But `Alert 0` has no [next sibling element](https://github.com/cssinjs/jss/blob/master/packages/jss/src/renderers/DomRenderer.js#L232), so the function `findPrevNode` returns `null` and function `insertStyle` add `Alert 1` styles at [insertion point](https://github.com/cssinjs/jss/blob/master/packages/jss/src/renderers/DomRenderer.js#L262).

Instead of
```css
.panel-0-0 { ... }
.panel-1-0 { ... }
.alert-0 { ... }
.alert-1 { ... }
```

we get
```css
.alert-1 { ... }
.panel-0-0 { ... }
.panel-1-0 { ... }
.alert-0 { ... }
```

It worked in my FF browser because I had browser extension that add tag `<style>` at the end of `<head>`.

# Workaround

As a temporary solution I added `<title>` at the end, but it will work with any html element.

**Comment by kof** [comment]
Thats strange, mb try to add a test in jss repo.
