### ISSUE TITLE
function value doesn't work for nested levels

### ISSUE THREAD

**Issue by tibbus** [cssinjs/react-jss#280]
It worked on **8.6.0** but it doesn't work on **8.6.1**
Even though I saw this : https://github.com/cssinjs/jss/issues/682

Ex. the below code works on **8.6.0**, but it doesn't work anymore and a warning is displayed in the console : 

> Warning: [JSS] Could not find the referenced rule fieldLabel ....

```
export default {
  flowLayout: {
    padding: '5px'
  },
  fieldLabel: {
    background: 'blue'
  },
  layoutGroup: {
    '&.flowLayout': {
      '& $fieldLabel': {
        marginBottom: () => {
          return '500px';
        }
      }
    }
  }
};
```

**Comment by kof** [comment]
Are you sure it worked on 8.6.0? This was actually never supported, I assume something tricked you into thinking it worked, please check again?

**Comment by tibbus** [comment]
Hey @kof , thanks for the fast reply !

I have created 2 playgrounds with react-jss : 

8.6.0, here it works, div background turns 'red' : https://codesandbox.io/s/nkvvl4z7n0
8.6.1 it does NOT work, div background stays 'blue' : https://codesandbox.io/s/9jvzo7qm6w

(it worked before 8.6.0 as well, I used 8.3.1)

**Comment by kof** [comment]
Interesting, thanks for the report! We fixed a bug which apparently broke something that I wasn't aware it worked! cc @HenriBeck

**Comment by HenriBeck** [comment]
I think the problem is with the merge classes. Because earlier we added every static class to the dynamic sheet which meant that jss-nested could resolve the reference.
But now the classes are in different sheets and jss-nested can't resolve them anymore...

Really not sure if there is a solution for this with supporting both problems 🤔

**Comment by kof** [comment]
I think we can do it within jss-nested, since we have still an access to classes.

**Comment by HenriBeck** [comment]
We don't have access to the static classes inside the dynamic sheet sadly. We would need a way to pass the classes to jss-nested but that seems like a hack. It makes sense that we would only allow jss-nested to reference the rules in the same stylesheet, this is a tradeoff from react-jss I would say.

**Comment by kof** [comment]
I have an idea how to fix this: unrelated to this in this PR I added a classes option to the style sheet: https://github.com/cssinjs/jss/pull/757/commits/36416cc7347f045338e6e54fd88edae652b8245a#diff-29aac1ba5d08e188c14800bc889c5474R38

This allows to pass a classes object to a stylesheet with a predefined class names. So if we pass classes from the static sheet to the dynamic one, the rules which have the same name, will use that class name and the problem should get fixed automatically.

**Comment by kof** [comment]
I wonder if I should merge that change separately, so that we can separately fix this bug.

**Comment by HenriBeck** [comment]
We would need to release jss 10 with that fix and I don't think we are quite ready for that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HenriBeck** [comment]
Also did you test the change with jss-nested, if jss-nested actually considers the classes🤔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
That change is non-breaking so its a minor release. But have to try and see if its all we need to fix it.

**Comment by HenriBeck** [comment]
Yeah, you would expect that it works but the architecture of react-jss works differently. I think the fix should be in react-jss and not jss

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
well, the classes option I added serves actually a different point  there, but it can be used to fix this. So  kinda ok to use it if we have it anyways.

**Comment by HenriBeck** [comment]
In my opinion the jss-nested rule should only reference the rules in the same sheet. That's why I think it's a problem of react-jss

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kof** [comment]
Yes, it won't be referencing rules from another sheet, its the classes map that is passed from static sheet to dynamic sheet.

**Comment by HenriBeck** [comment]
Would this require a breaking change in the plugins api?

**Comment by kof** [comment]
Nope

**Comment by michael-ecb** [comment]
Hi,
does it the same problem here ? 
I'm trying to get a value into my  property: "&$checked" but does not work for me
thanks

```
const styles = {
        checkbox: props => ({
            width:  props.width,
            height: props.height,
            "&$checked": {
                    color: props.checkedColor
              }
        })
}
```

**Comment by michael-ecb** [comment]
thanks @HenriBeck  but I 'm using material-ui v1, 
they need this property to be pass like this "&$checked",
I also have an example : 

```
const styles = {
        checkbox: {
            width:  props=>  props.width, <-- working
            height: props=> props.height, <-- working
            "&$checked": {
                    color:  "#000"  <-- working
                    color: props =>   props.checkedColor    <--- does not working
              }
        }),
        checked:{}
}
```

thanks

**Comment by kof** [comment]
you can not use 2 color properties in one object, the last one will always override the first one

**Comment by michael-ecb** [comment]
@kof  of course it was only for give you an example... I used only one, still not works...

**Comment by tibbus** [comment]
Looks the same as in my example, Nested level + value from function call does not work in this version.

**Comment by kof** [comment]
In that case its what the initial issue describes, we could release a 9.minor version which would fix it, if v10 takes more time

**Comment by michael-ecb** [comment]
thanks , for me it's not working also with previous version...

**Comment by tibbus** [comment]
Then is not this issue, I suggest to create a sandbox similar with mine to see exactly what's not working

**Comment by HenriBeck** [comment]
This issue was moved to cssinjs/jss#796
