### ISSUE TITLE
Function values & rules results in CSS with invalid property name

### ISSUE THREAD

**Issue by thomasgrivet** [cssinjs/react-jss#283]
Hi!

I use this package quite a lot and decided to give functions values and functions rules a go. But for whatever reason it result in badly formatted CSS.

Code like this : 

![screenshot from 2018-07-25 14-49-24](https://user-images.githubusercontent.com/18561703/43201845-f15acc4e-9019-11e8-8ade-adc57168ca07.png)

becomes : 

![screenshot from 2018-07-25 14-50-28](https://user-images.githubusercontent.com/18561703/43201895-17f253c2-901a-11e8-85a1-6efa555dbfd4.png)

I'm not sure if it's an issue related to react-jss or just jss.

Thanks for your help and all the time you put in this project :heart:

**Comment by kof** [comment]
It means you don't have proper plugins setup.
