### ISSUE TITLE
React Context API: Cannot access value from render props in styles

### ISSUE THREAD

**Issue by conor909** [cssinjs/react-jss#284]
Do we need a plugin or is there something else I'm missing?
Working (not working) example:

https://codesandbox.io/s/y36q6lvzx1

**Comment by conor909** [comment]
@kof I'm not too familiar with codesandbox but I'v tried to create one here https://codesandbox.io/s/y36q6lvzx1

**Comment by kof** [comment]
tried to reload? I don't see a code that is broken

**Comment by conor909** [comment]
Apologies @kof, you should be able to see it working now

**Comment by kof** [comment]
Ok you are not passing props to that component where you try to render styles.

**Comment by conor909** [comment]
@kof My question is, is it possible to do, or can I request a feature?  So could you please re-open the issue?

**Comment by kof** [comment]
No, you are using context inside of the app, but you render styles as a HOC of the APP, so nothing is passing your context as props to the HOC that renders styles

**Comment by kof** [comment]
Pass the props to the component that renders the styles, you need to refactor your code, thats it.

**Comment by conor909** [comment]
Ok so I guess we wont ever be able to use values from render props

**Comment by kof** [comment]
No, thats not what I said.
