### ISSUE TITLE
How to use react-jss to select and style inner input elements

### ISSUE THREAD

**Issue by yijiaow** [cssinjs/react-jss#285]
I'm trying to style `<input className={classes.slider} type="range" name="slider" />`. I am able to use `appearance: 'none'` and reactjss conveniently handled all the cross-browser stuff. However I tried to access and style`slider-thumb`, `slider-runnable-track` by using 
```
slider: {
    appearance: 'none',
    borderRadius: 5,
    backgroundColor: '#ccc',
    width: 200,
    height: 25,
    '&::slider-thumb': {
      appearance: 'none',
      border: '3px solid blue',
    }
```
but no luck. All the other nested pseudo selectors have been working for me. 

I have read this Issue #204 but the author did not post about how it's been solved...

Thank you very much!

**Comment by yijiaow** [comment]
@HenriBeck thank you! This solved the problem. This might be out of scope for react-jss, since ::-webkit-slider-thumb is not on standard track, is there a better way to customize input type="range"? I'm using Semantic-UI-React and it doesn't have a Slider component.

**Comment by HenriBeck** [comment]
There is currently no other way of styling those things unless you use a custom slider component.
