### ISSUE TITLE
Suggestion: Auto detect PureComponent (with proposed fix)

### ISSUE THREAD

**Issue by rob2d** [cssinjs/react-jss#286]
I've noticed one thing which adds to the boilerplate of apps using `react-jss` is you must either create a utility for wrapping `PureComponent` in something like recompose's `pure` wrapper to prevent re-renders of the external JSS HOC or JSS HOC will just attempt a re-render upon any prop change. It also is a very easy optimization hit to miss if you take `react-jss` and make that assumption without running Perf tests. 

Considering immutability is a very sensible default for React re-renders, would it make sense to auto detect whether `InnerComponent` in `createHoc.js` is an instance of `PureComponent` and then substitute that vs `Component` when possible? This looks like it can be done pretty easily in the `createHoc` function. One implementation detail to help make the library even more transparent to end users while debugging in the inspector may be to name the Hoc `PureJSS` or `ImmutableJSS` rather than just `JSS` when it is extending `PureComponent`.

As I am not overly familiar with the internals here and intention, I just wanted to pass this idea along. I would be more than willing to submit it as a PR if preferred if it is agreed that it makes sense.

Thanks and thanks again for the amazing work with this set of libraries.

**Comment by kof** [comment]
In my experience it makes no sense, I also wrote an article that touches this point https://medium.com/@oleg008/arrow-functions-in-react-f782d11460b4

**Comment by kof** [comment]
1. React is fast enough in 99% of cases without PureComponent optimization. 
2. PureComponent optimization works only if all references are not created within render, which is hard to achieve in complex apps
3. PureComponent will introduce an overhead if shallowEqual can't avoid rerendering

**Comment by rob2d** [comment]
I appreciate the quick feedback. 

Unfortunately, sometimes you do need to actually use a Component interface. I agree generally with what you are saying, but we are assuming here in your article that every use case is the same which is not necessarily good for a general purpose library e.g. style. For example, when you have mouse listeners, do you hard code every ref to your global state, or simply use a Component class to be able to bind lifecycle events (e.g. mount/unmount)? This applies to most dynamic media content; especially non serializable. I really don't mean to be condescending but these assumptions are being made with the thought that we will not encounter a use case for web apps besides kind of boiler plate stuff without non serializable media. This is not the case for many important flagship products and apps. If we are going to say JSS should not be used for anything that doesn't require simple interfaces and we should then stick to CSS if you need to use Component/PureComponent when it makes sense, that is fine.

Also, it is very easy to adopt the habit of not using new function references in props. A lot of the arguments about speed are using a unique use case scenario or mindset.

**Comment by kof** [comment]
>  that we will not encounter a use case for web apps

Actually we always need to make assumptions and the best one is the one that fits the most. What you are talking is an edge case that can be easily solved in your specific case, no?

**Comment by rob2d** [comment]
Using lifecycle hooks is a fundamental feature of React; it's not an edge case. Also if we will stress about a few milliseconds hit of using `PureComponent` at the convenience of never thinking about controlling re-render state, we could start to apply this to everything such as simply using Go over Node to support preprocessors. Its a trade-off and it isn't really an objective thing.  Limiting re-renders is also a pretty fundamental aspect of React and there's many cases where it's something to consider.

We have had very different experiences with the types of apps we've worked on; that does not mean yours is wrong or mine is right. It means there's different use cases which could be considered.

**Comment by kof** [comment]
Totally agree, thats why you can use your own component and make it PureComponent instance, right?

**Comment by rob2d** [comment]
Yep. Will use a wrapper Hoc that takes care of it and close out. Not the biggest deal, but would be nice :p Thanks for being responsive on this issue though.

**Comment by kof** [comment]
You would have to use a wrapper HOC only in specific cases, right? Or is it every component in your case?

**Comment by rob2d** [comment]
Most react libs are pretty opinionated, so I end up using PureComponent just not to deal with the nuances when it's not a functional component (as perf isn't much different), and rely on immutable libs. Its also a bit forced on us thanks to libraries like `react-redux` with connect Hoc which enforce this concept. So the most part will use them 🤷‍♂️ I use `recompose's/pure` btw for this purpose as functional components are not yet optimized to actually be stateless in React (last I checked).

**Comment by kof** [comment]
Still, do you have a use case, that requires you do wrap all components that use injectSheet with PureComponent or you do it in specific places?

**Comment by rob2d** [comment]
I wrap components at the base of a functional component hierarchy that isn't connected to redux already (if I am being completely mindful). We can agree by nature of functional components if we're not insane that if a functional component inherits a functional component, it's should not arbitrarily receive new props at random times to refresh itself

**Comment by rob2d** [comment]
(tbh I am just getting back into front end hence I'm back here bothering you with this issue... So I haven't been very systematic/defined rules for this until further consideration here this AM 🙃 )
