### ISSUE TITLE
question: how to inject different styles to multiples use of same component

### ISSUE THREAD

**Issue by michael-ecb** [cssinjs/react-jss#288]
Hi,

I have a multiple use of a generic component in my page, 
this component can change his style  according to his props received, my problem is that the last component styles always **override** styles of others...  
In this simple example I can work with inline styles but for my real and complex components I have to send class names to a third party (material ui)

component file :

```
const styles = {
     label: props => ({
            color: props.color,
            fontSize: props.fontSize
	  })
};

export class Label extends React.Component {
	
	static propTypes={
              color: PropTypes.string,
              fontSize:PropTypes.number
        };
	
	 render() {
		const {children, classes} = this.props;
		return <span className={classes.label}>{children}</span>
    }
}

export default injectSheet(styles)(Label);

```

from my page:

`<Label color="red">red label</Label>`
`<Label color="blue">blue label</Label>`

all labels will be blue .

Thanks.

**Comment by HenriBeck** [comment]
Can you please create a codesandbox.io where your problem exists.

**Comment by michael-ecb** [comment]
I make it more  simply  : 
[https://codesandbox.io/s/m38znz2438](url)

in this example the hover style will not affect when I use "props", my real target is to send "hoverStyle" but here with only color change its also not changing...
I have this problem in all my components that they need a complex css object and deal with props...

thanks

**Comment by HenriBeck** [comment]
The problem is that we don't support every syntax when using function rules.

```js
const styles = {
  root: {
    color: props => props.color,
    '&:hover': {
      color: 'yellow',
    },
  },
};
```

Working example: https://codesandbox.io/s/jl65nlzxvv

**Comment by michael-ecb** [comment]
thanks @HenriBeck it's fine when the properties are not dynamics :(
do you plan to support it on future ? 
if not, can you tell me if it's not a best practice in React to do it or I need wrap all my components and call function rules before injectStyles ?

thanks for your help

**Comment by HenriBeck** [comment]
Why would you need to call your function rules?

Maybe we will support it in the future, but my solution is also more efficient because we can reuse the static part of the stylesheet between mounted component instances.

**Comment by HenriBeck** [comment]
You can have styled affected by props the way I showed you. Instead of the whole rule being affected by the props, only certain style properties can be calculated by props.

http://cssinjs.org/react-jss?v=v8.6.1#dynamic-values

**Comment by michael-ecb** [comment]
ok I understand it's better to change only specifics props, but where I will need to deal with dynamic value for  '&:hover' or '&$checked' it will not work for third party...

**Comment by HenriBeck** [comment]
Function values should work with `&:hover` etc
