### ISSUE TITLE
Question: how to link rule with sheet option link:true?

### ISSUE THREAD

**Issue by oyshan** [cssinjs/react-jss#289]
Hi!

I'm trying to create a dynamic flex container with react-jss. Specifically, I'm trying to make a dynamic flex item gutter. When I added the dynamic flex item gutter on the flex items (ie. a positive margin on all childs), I got the warning: `Warning: Rule is not linked. Missing sheet option "link: true".`

My code looks like this:

    const styles = {
	    container: {
		display: 'flex',
		flexDirection: props => props.flexDirection,
		flexWrap: props => props.wrap,
		justifyContent: props => props.justifyContent,
		alignItems: props => props.alignItems,
		alignContent: props => props.alignContent,
		// Item spacing:
		margin: props => -(props..itemSpacing/2)
		'&>*': {
			// This is what causes the "rule not linked" warning
			margin: props => (props.itemSpacing/2),
		},
	    },
    }

    export let Container = props => (
		<div className={props.classes.container}>
			{props.children}
		</div>
	)
    
    Container = injectSheet(styles)(Container)

My question is: how do I link this rule with sheet option link:true to make it work dynamically? Thanks!:)

**Comment by kof** [comment]
what you posted should already work, link: true is integrated in react-jss, the last part with '&>*' will not work with function value due to https://github.com/cssinjs/jss/issues/682

**Comment by oyshan** [comment]
Thanks. Do you know of a workaround, though, @kof , as the function value inside the child selector doesn't work?

**Comment by HenriBeck** [comment]
The problem is your selector, see for an example: https://codesandbox.io/s/o43vmmlmp6

Your selector should be to get it working: `& > *`

**Comment by oyshan** [comment]
Thanks, @HenriBeck!:) Why should `& > *` working, but not `&>*`? Does JSS try to do different things in these cases?

**Comment by kof** [comment]
there is no difference between `& > *` and `&>*` for jss

**Comment by HenriBeck** [comment]
Why does my codesandbox than work?

**Comment by kof** [comment]
Need to check, there was a problem that we introduced in the recent versions.

**Comment by HenriBeck** [comment]
Yeah, but that was only related to referencing rules I think.
