### ISSUE TITLE
Theme prop is not injected into a component if the styles passed to injectSheet is a object rather than a function.

### ISSUE THREAD

**Issue by jmitchell89** [cssinjs/react-jss#291]
Specifically this line in the code:
`isThemingEnabled = typeof stylesOrCreator === 'function';`

Causes the theme object to not be injected.

A work around for us now is to just change the styles passed in to a function instead of an object, but I feel as though we shouldn't need to do this if we aren't using the theme object in the styles? Is there a reason the theme only gets passed to the component via props when the styles object is a function? For us its useful as we pass color values to different external components from the theme.

Thanks!

**Comment by kof** [comment]
The complication is that we would need to subscribe for theme updates in every HOC always. There are 2 potential other ways to detect if theming is required:

1. pass an option isThemingEnabled
2. use state.dynamicSheet to set isThemingEnabled additionaly to typeof check (so if there are function values, we enable theming automatically)

**Comment by kof** [comment]
can you please migrate this issue to jss repo? We are in a migration state right now.

**Comment by HenriBeck** [comment]
I think we should go with the first way because function values are not a definitive sign of theme usage.

This would be easy to implement.

**Comment by kof** [comment]
Another thought: need to check the cost of subscribing, mb its not worth optimizing and we could always subscribe if ThemeProvider is used at all.

**Comment by kof** [comment]
And another thought: we could remove the emitter all together if we use the new context api.

**Comment by HenriBeck** [comment]
I don’t think this is a good idea because it will create a potential of a lot of rerenders.

Don’t we also export the withTheme Hoc?

**Comment by HenriBeck** [comment]
This will be tracked in cssinjs/jss#856
