### ISSUE TITLE
How can I pass custom properties through to my style method from injectSheet?

### ISSUE THREAD

**Issue by JamesDonnelly** [cssinjs/react-jss#293]
Hey guys, I'm really new to JSS. I have a progress bar component which I'd like to display differently under certain circumstances. I'm wanting to pass a `source` property through to my style function, but the only way I've found to do this feels like a complete hack:

```javascript
const Component = injectSheet(theme => props.style(theme, props.source))(...)
```

This gives me the `source` property within my style method, allowing me to use:

```javascript
export default (theme, source) => {
  // Source-specific styles.
  if (source === 'some-source')
    return { ... }

  // Default styles.
  return { ... }
}
```

I'm sure there must be a better way than wrapping my style method in an additional method when passed through to `injectSheet`.

Is there an accepted way of doing this, or is what I have perfectly okay?

**Comment by kof** [comment]
I assume you are looking http://cssinjs.org/react-jss?v=v8.6.1#dynamic-values

**Comment by JamesDonnelly** [comment]
Ah perfect, thank you!
