### ISSUE TITLE
&:hover not work

### ISSUE THREAD

**Issue by Rabinzon** [cssinjs/react-jss#296]
Hi, when I return style object from function, '&:hover' not working  🤔  
works fine: 
```
div1: {
    background: theme.background,
    width: 100,
    height: 100,
    margin: 10,
    "&:hover": {
      background: "green"
    }
  }
```
hover will not work in this example
```
  div2: props => ({
    background: "red",
    width: 100,
    height: 100,
    margin: 10,
    "&:hover": {
      background: "green"
    }
  })
```

https://codesandbox.io/s/2o8npjkqyy

**Comment by kof** [comment]
we don't support most plugins within function rules/values yet, see https://github.com/cssinjs/jss/issues/682

**Comment by Rabinzon** [comment]
ok, thanks
