### ISSUE TITLE
[feature-request] Shadow Root styles

### ISSUE THREAD

**Issue by trusktr** [cssinjs/react-jss#297]
It'd be nice for react-jss to auto-detect elements inside a shadow root and inject styles there.

Related: 

- https://github.com/cssinjs/jss/issues/539#issuecomment-421523750
- https://github.com/cssinjs/jss/issues/366

**Comment by trusktr** [comment]
I have an idea!

JSS can make a `data:` URL of the styles, then instead of adding `<style>` elements to shadow roots, it can add `<link>` elements that use the data URL. This will use the same stylesheet content from the browser cache.

The browser can optimize from there.

---

To improve on this later, we could make each root component separate style, and based on the root style selectors, we could determine which styles to `<link>` into a given root that way the root only has styles that it needs.

**Comment by trusktr** [comment]
This two-year old article has some insight: https://www.smashingmagazine.com/2016/12/styling-web-components-using-a-shared-style-sheet/

**Comment by kof** [comment]
You just mixed 2 separate things as far as I can see: one is auto detection of shadow root, which might be interesting at some point, another optimizations using data url. I am not sure how those 2 are related, and why you would want to generate data url.

**Comment by HenriBeck** [comment]
I think traversing the dom on every component mount would create a performance issue. This could be behind an option though I don't see why and how react-jss components whould be used in custom elements

**Comment by kof** [comment]
Also I assume there could be use cases, where entire react app is rendered within one custom element with a shadow root. We need to learn more about such use cases, I am not sure though if in this case there is a need for auto detection, since its done once, user can do it even in the Jss instance setup.

**Comment by HenriBeck** [comment]
I don't think we could cache it, because components can be rendered anywhere

**Comment by trusktr** [comment]
> why you would want to generate data url.

How else would we avoid duplicating styles in every shadow root? Once it the data URL is generated, each root can `@import` it (there could be hundreds or thousands of shadow roots).

> If you think generating base64 encoded data url is faster think twice and make a bench

Yeah, interesting question: would it be faster to create one single data URL for a JSS style sheet and then `@import` it hundreds of times (once per shadow root)? Or would it be faster to add/duplicate the styles to each `<style>` tag hundreds of times (once per root)?

Indeed a bench would be nice.

- [ ] TODO make a bench

> traversing the dom on every component mount would create a performance issue

Maybe we can monkey patch `attachShadow` so we get direct references to shadow roots, and don't have to traverse the DOM to find them. Then after that we would have some options:

1. just attach all JSS styles to any shadow root (easiest)
2. run `querySelector`s on the root to see if any generated selectors match, and only in that case add the stylessheets (I guess this circles back to traversing DOM)
3. Give end users some API so they can choose when to attach styles to a shadow root.

I think I like the last idea more? Maybe it would look like this:

```js
const sheet = jss.createStyleSheet({...})
const root = el.attachShadow({...})
sheet.attach(root)
```

In this case, JSS would not need to detect shadow roots or traverse DOM, the user would just attach whatever sheets it needs to a root.

> Also I assume there could be use cases, where entire react app is rendered within one custom element with a shadow root

This is _very_ true. I use [SkateJS](https://github.com/skatejs/skatejs) which use ShadowDOM, and I will definitely have this problem there. In this case, I think being able to attach a JSS sheet to my component's root (I always have a reference to it) would work fine. I could abstract it away as a mixin or base class.

**Comment by trusktr** [comment]
> So it's more of a feature for jss and not react-jss?

Actually yeah, sounds like support needs to be in `jss`.

But the thing is, if I'm using `react-jss`, and my component is somewhere inside a shadow root, as the author of the React component using `react-jss` I don't want to think about if it will work, I just assume it'll work.

So maybe `react-jss` needs some way to detect the shadow root and use the feature from `jss` when needed.

**Comment by kof** [comment]
Need further investigation, also we are moving to monorepo, can you please summarize this issue in a new one in JSS repo or should we move this issue there? Looks less nice then.
