### ISSUE TITLE
Functions and pseudo-selectors

### ISSUE THREAD

**Issue by gabchang** [cssinjs/react-jss#298]
There is a parsing problem when using a function combined to pseudo selectors.
This already happened in version prior to 6.0.0 (see here #81)

Tested with react-jss@8.6.1

When I write this
```
button: ({ color, colorHover }) => ({
    color,
    ':hover': {
      color: colorHover,
    }
  }),
```

The result is 
```
.button-0-1-28 {
  color: #68B0AB;
  &: hover: [object Object];
}
```

If I write this 
```
  button: {
    color: ({ color }) => color,
    '&:hover': {
      color: ({ colorHover }) => colorHover,
    }
  },
```
It works as expected 
```
.button-0-1-58:hover {
  color: #948D88;
}
.button-0-1-58 {
  color: #685D55;
}
```

Thanks for your work by the way !

**Comment by HenriBeck** [comment]
Function rules currently do not support all of the other plugin syntaxes.
See cssinjs/jss#682

We are planning to support the full syntax in v10


Also you're example is wrong, it should be:
```js
button: ({ color, colorHover }) => ({
    color,
    '&:hover': {
      color: colorHover,
    }
  }),
```
Though this isn't supported either currently.
