### ISSUE TITLE
How to use :not selector in JSS?

### ISSUE THREAD

**Issue by bexoss** [cssinjs/react-jss#300]
I want to apply background on hovered div except first child.  
so I should use :not with :hover 

` 
card: {
        '&:not:first-child' : {
            '&:hover' : {
          background: 'red'
        }
    }
`

I am using material-ui, so jss-nested works already. What is proper syntax?

**Comment by HenriBeck** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:not 

You are using the selector wrong
