### ISSUE TITLE
[question] CSS differences during SSR and hydration

### ISSUE THREAD

**Issue by rafaeltavares** [cssinjs/react-jss#301]
Hi!

I'm trying to render my react application on a server.
I've followed the instructions on this project `readme.md` file.
But I'm getting CSS differences during the server rendering and the application hydration.

As an example, I rendered the snippet below on Safari 8.

The first image shows the CSS rendered on the server:

![image](https://user-images.githubusercontent.com/4458855/46217170-a8e45300-c317-11e8-8935-980c4714e261.png)

The second one shows the CSS rendered on Safari:

![image](https://user-images.githubusercontent.com/4458855/46217175-ac77da00-c317-11e8-8f9d-87b77716cf03.png)

Since Safari needs the prefixed version of Flexbox I can't get the correct style until the hydration.
Is there a way to provide the correct user agent to the vendor-prefix-plugin?

**Comment by HenriBeck** [comment]
Sadly not, because we apply the vendor prefixes based on some style testing in the actual DOM and not based on the User-Agent.
So we create an empty element and see if the style works, and if not, we go through the vendor prefixes and try them.
