### ISSUE TITLE
Problem with bundle, when react-jss alias

### ISSUE THREAD

**Issue by ximet** [cssinjs/react-jss#302]
I try to use react-jss like an alias in my App. And have some problem with my bundle.

```javascript
resolve: {
        alias: {
            react: path.resolve('./libs/react-16.4.1.debug.js'),
            React: path.resolve('./libs/react-16.4.1.debug.js'),
            'react-dom': path.resolve('.libs/react-dom-16.4.1.debug.js'),
            classnames: path.resolve('.libs/classnames-2.2.5.debug.js'),
            'react-jss': path.resolve('../node_modules/react-jss/dist/react-jss.js'),
        },
        modules: [NODE_PATH],
        extensions: ['.js', '.jsx', '.json', '*']
    },
```
and my loader:

```javascript
rules: [
            {
                test: /\.(js|jsx)$/,
                use: {
                    loader: 'babel-loader',
                },
                exclude: /node_modules(?!(\/|\\)libComponents)/,
           },
```

libComponents - it's my library where I use react-jss, react, react-dom like a peerDependency.

My error:

```javascript
Uncaught Error: Cannot find module 'React'
    at webpackMissingModule (react-jss.js:3)
    at webpackUniversalModuleDefinition (react-jss.js:3)
    at Object.../node_modules/react-jss/dist/react-jss.js (react-jss.js:10)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.../node_modules/libComponents/src/components/index.js (createTheme.js:17)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.../node_modules/libComponents/index.js (index.js:1)
    at __webpack_require__ (bootstrap:724)
```

How to resolve this bundle problem? I really need to use react-jss like a peerDependency

**Comment by kof** [comment]
not sure whats this exactly, but it seems like a problem with your webpack config, not with JSS, if you can show why its a problem with react-jss package, please reopen.

**Comment by ximet** [comment]
@kof 'react-jss': path.resolve('../node_modules/react-jss/dist/react-jss.js'), don't understand React library. It's not a problem webpack config

**Comment by ximet** [comment]
@kof I can't use this library, using just dist file: react-jss. And I think, the problem not in my own configuration

**Comment by kof** [comment]
I looked into the dist file it has this

```
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("React"));
	else if(typeof define === 'function' && define.amd)
		define(["React"], factory);
	else if(typeof exports === 'object')
		exports["reactJss"] = factory(require("React"));
	else
		root["reactJss"] = factory(root["React"]);
```

Looks like we should require('react') but access root.React from the window. So if you have a require currently it will try to require('React') starting from upper case.

**Comment by ximet** [comment]
@kof Sure, and if you can see, I add this opportunity in my alias

alias: {
            react: path.resolve('./libs/react-16.4.1.debug.js'),
            React: path.resolve('./libs/react-16.4.1.debug.js'),
            'react-dom': path.resolve('.libs/react-dom-16.4.1.debug.js'),
            classnames: path.resolve('.libs/classnames-2.2.5.debug.js'),
            'react-jss': path.resolve('../node_modules/react-jss/dist/react-jss.js'),
        }

**Comment by kof** [comment]
Not sure why then ... can you provide  a quick runnable example?

**Comment by kof** [comment]
btw @TrySound @HenriBeck I just looked into the new bundle 

```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react')) :
	typeof define === 'function' && define.amd ? define(['exports', 'react'], factory) :
	(factory((global.reactJss = {}),global.react));
}(this, (function (exports,React) { 'use strict';
```

In this case we require correctly lower case, but global.react probably won't exist, I guess it would be upper cased.

**Comment by TrySound** [comment]
I think toCamelCase wrongly converts globals. It's better to provide explicit globals object.

**Comment by kof** [comment]
Yep, we need to capitalize the first char.

**Comment by TrySound** [comment]
[camelcase](https://www.npmjs.com/package/camelcase) with pascalCase option may do this.

**Comment by HenriBeck** [comment]
The problem is that you are using the umd distribution and you should use the cjs version.

**Comment by TrySound** [comment]
@HenriBeck Globals are the problem too. `window.React` and `window.ReactDOM` are provided by react itself.

**Comment by ximet** [comment]
@kof ok(when I capitalize first letter), now after rebuild I have another problem:

```javascript
react-jss.js:2911 Uncaught TypeError: Cannot read property 'CSS' of undefined
    at Object.<anonymous> (react-jss.js:2911)
    at Object.<anonymous> (react-jss.js:2928)
    at n (react-jss.js:30)
    at Object.<anonymous> (react-jss.js:2202)
    at n (react-jss.js:30)
    at Object.<anonymous> (react-jss.js:1779)
    at n (react-jss.js:30)
    at Object.<anonymous> (react-jss.js:1697)
    at n (react-jss.js:30)
    at Object.<anonymous> (react-jss.js:1573)
```

You can check this problem in my Repo https://github.com/ximet/ReactBoilerplate branch: master

**Comment by kof** [comment]
What webpack version are you using? its this line `var CSS = global.CSS;` looks like your webpack doesn't polyfill global

**Comment by kof** [comment]
Why are you actually trying to use dist instead of lib?

**Comment by kof** [comment]
Wait, the bundle itself  is actually polyfilling global, I don't know why it can't find it in your case

```
/***/ (function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {'use strict';
	
	Object.defineProperty(exports, "__esModule", {
	  value: true
	});
	var CSS = global.CSS;
	
	var env = ("development");
	
	var escapeRegex = /([[\].#*$><+~=|^:(),"'`])/g;
	
	exports['default'] = function (str) {
	  // We don't need to escape it in production, because we are not using user's
	  // input for selectors, we are generating a valid selector.
	  if (env === 'production') return str;
	
	  if (!CSS || !CSS.escape) {
	    return str.replace(escapeRegex, '\\$1');
	  }
	
	  return CSS.escape(str);
	};
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))
```

**Comment by ximet** [comment]
@kof because global === undefined

**Comment by kof** [comment]
@ximet obviously, but why is it undefined, see the code above, also check if you are actually using the code above.

**Comment by ximet** [comment]
@kof I using a vendor, because all our libs in App have this flow.

Yes, I check, and I using code above. And my webpack: 4.20.2 with babel 7

**Comment by ximet** [comment]
@kof and one more point: I have all dependency on the next path: window.vendor.React

And in this case, I really need to use alias for bundle

**Comment by ximet** [comment]
About polyfill, I check my entrypoint and find in the 1st line: import "@babel/polyfill";
It's correct connect polyfill to app, I checked in doc

**Comment by HenriBeck** [comment]
Why do you have all of your vendors on `window.vendor.React`? Why don't use the normal import way?

**Comment by ximet** [comment]
@HenriBeck because it's our standard in project

**Comment by HenriBeck** [comment]
Can you then create a repo with the issue for us to check out?

**Comment by HenriBeck** [comment]
global should be the window but apparently it isn't. Maybe thats because you use it on window.vendors.ReactJss?

**Comment by ximet** [comment]
Build the library, using cjs and everything OK.
