### ISSUE TITLE
Travis build fails for the last 8 months

### ISSUE THREAD

**Issue by krzysztofpniak** [cssinjs/react-jss#303]
https://travis-ci.org/cssinjs/react-jss/builds

**Comment by HenriBeck** [comment]
Yes, we know, we are currently migrating the whole project into a monorepo, and the tests are running successfully in the new repo. This repo will be soon deprecated.

**Comment by kof** [comment]
should we add a hint somewhere? or deprecate right away?

**Comment by HenriBeck** [comment]
We could deprecate right away, but then should do the same with the other repos.

**Comment by kof** [comment]
yeah, I think we should do it, we are not doing anyways anything in those repos
