### ISSUE TITLE
Non-css properties doesn't work inside dynamic values function

### ISSUE THREAD

**Issue by chapa** [cssinjs/react-jss#308]
Hi !

I'm not sure it hasn't been fixed in cssinjs/jss#878 (not yet released so I couldn't test it), but here's a bug I'm faced with : https://codesandbox.io/s/633pqj4mz

This is working as expected :
```js
const styles = {
  style1: {
    color: 'red',
    '@media (min-width: 768px)': {
      fontWeight: 'bold'
    },
    '&:hover': {
      color: 'blue'
    }
  }
}
```

And when I tried to use dynamic values, "non css properties" are wrongly interpreted :
```js
const styles = {
  style2: props => ({
    color: 'red',
    '@media (min-width: 768px)': {
      fontWeight: 'bold'
    },
    '&:hover': {
      color: 'blue'
    }
  })
}
```

The latter example is generating this css :
![image](https://user-images.githubusercontent.com/457659/47952083-7b1fa900-df6a-11e8-813b-cfb18601dc54.png)
Like if the media query and hover are interpreted as css properties.

Maybe I should precise what I want to do concretely (which require to put the media query inside a function with props), something like that :
```js
const styles = {
  style1: props => ({
    [`@media (min-width: ${props.width}px)`]: {
      display: 'none'
    }
  })
}
```

Tell me if you need more details, thank you !

**Comment by kof** [comment]
yes, this should be fixed in v10, subscribe https://github.com/cssinjs/jss/issues/795 for release info

**Comment by chapa** [comment]
Ok thanks !
