### ISSUE TITLE
[Problem] Integrate Theme functionality 

### ISSUE THREAD

**Issue by jonathangiamp** [cssinjs/react-jss#313]
Hi guys 👋

I've a problem to integrate the theming functionality inside my next.js project who use *react-jss*. I tried the ThemeProvider who I've found inside the documentation.
My page is rendered two times. I think the theme style is apply during the server-side rendering process but the page is immediately destroy during the browser rendering.
What are you feeling about that? How can I solve my problem?

Here are my files:

**_document.jsx**

    import React from 'react';
    import Document, { Head, Main, NextScript } from 'next/document';
    import {
        SheetsRegistry,
        JssProvider,
        ThemeProvider,
    } from 'react-jss';

    const theme = {
      colorPrimary: 'green',
    };

    export default class JssDocument extends Document {
      static getInitialProps(ctx) {
        const registry = new SheetsRegistry();
        const page = ctx.renderPage(App => props => (
            <JssProvider registry={registry}>
                <ThemeProvider theme={theme}>
                    <App {...props} />
                </ThemeProvider>
            </JssProvider>
        ));

        return {
          ...page,
          registry,
        };
      }

      render() {
        return (
          <html lang="en">
            <Head>
              <style id="server-side-styles">
                {this.props.registry.toString()}
              </style>
            </Head>

            <body>
              <Main />
              <NextScript />
            </body>
          </html>
        );
      }
    }

**index.jsx**

    import React from 'react';
    import injectSheet from 'react-jss';
    import PropTypes from 'prop-types';

    const styles = theme => ({
      myButton: {
        backgroundColor: 'black',
        color: theme.colorPrimary || 'white',
      },
    });

    const Index = ({ classes }) => (
      <div className={classes.myButton}>Welcome to Novatopo website!</div>
    );

    Index.propTypes = {
      classes: PropTypes.shape({
        myButton: PropTypes.string,
      }).isRequired,
    };

    export default injectSheet(styles)(Index);

**_app.jsx**

    import App from 'next/app';    
    export default class MyApp extends App {
      componentDidMount() {
        const style = document.getElementById('server-side-styles');

        if (style) {
          style.parentNode.removeChild(style);
        }
      }
    }

Here a CodeSandbox to reproduce the problem: [codesandbox.io/s/pyrznxkr1j][1] 

  [1]: https://codesandbox.io/s/pyrznxkr1j

**Comment by HenriBeck** [comment]
Your ThemeProvider is only rendered on the server. You will either need to wrap your App around a ThemeProvider on the client or move the ThemeProvider into your main App component.

**Comment by jonathangiamp** [comment]
Thanks you very much 😁
