### ISSUE TITLE
HOC API

### ISSUE THREAD

**Issue by oliviertassinari** [cssinjs/react-jss#37]
Reading the documentation, I have noticed that you propose two differents API for the same thing.
Wouldn't it be better to have a single API?
Why not removing this one if favor of the *"ES7"* one?
```js
// ES5 and ES6
useSheet: (ReactClass, rules[, options]) => ReactClass
```
Using the following pattern seems totally fine and closer to the other HOC components available in the OSS community.
```js
export default useSheet(styles)(Button);
```

**Comment by oliviertassinari** [comment]
Noticed that the *"ES5 and ES6"* API is breaking composition.
E.g. it's very handy to have currified functions as you can use the following pattern:
```js
import compose from 'recompose/compose';
import pure from 'recompose/pure';
import {connect} from 'react-redux';

const styles = {};
const Component = () => {};

export default compose(
  pure
  useSheet(styles),
  connect()
)(Component);
```

**Comment by kof** [comment]
I agree.

**Comment by kof** [comment]
We should deprecate the useSheet(styles, Component) signature.

**Comment by kof** [comment]
fixed and released
