### ISSUE TITLE
Allow override of sheet prop in DecoratedComponent for theming

### ISSUE THREAD

**Issue by mdarens** [cssinjs/react-jss#47]
In the [render method of `DecoratedComponent`](https://github.com/cssinjs/react-jss/blob/master/src/index.js#L58) the `sheet` prop is passed after the `...this.props` spread, thus overriding it, and if I e.g. want to consume a something which by default exports a styled component using `useSheet` and theme it by wrapping it in another `useSheet` there is no way to do that now as far as I can tell without requiring more separate exports and more composition at the point of consumption, although I may be totally missing something here.

My proposal is to pass `sheet` through from `props` if present (simply by flipping the prop order) as well as checking for `this.props.sheet` in the lifecycle methods and skipping the ref counting, sheet attaching/detaching/create calls if present.

What do you think?
Thanks for your time!

**Comment by kof** [comment]
Will take a look at it soon.

**Comment by jcperez-ch** [comment]
Might be related to PR https://github.com/cssinjs/react-jss/pull/53, where there is an small implementation of skins.  I did unit tests around it and left comments on the README for specific usage.  We might want to go for another solution since, it is not specifically a `composed stylesheet`, since it still uses the `refs` counter.

Still, that PR needs some review, feedback.

**Comment by mdarens** [comment]
I know a full theming solution/dynamic sheets are being worked on for jss core, but is there any current use case flipping the order of `{...this.props} sheet={this.sheet}` to `sheet={this.sheet} {...this.props}` would break?

**Comment by kof** [comment]
@mdarens you want to pass a StyleSheet instead of styles objects, right?

**Comment by mdarens** [comment]
Indeed, with the assumption being that if you're passing a `sheet` prop that it has the same things the react-jss HOC would (or at least the same sheet properties being referenced in the wrapped component), eg a user-provided react-jss HOC instance higher up in the tree.

The other part (messing with the lifecycle methods) would probably needlessly complicate things vs. the hypothetical performance win.

**Comment by kof** [comment]
Released 2 things:

- Function injectSheet(styleSheet) now accepts StyleSheet instance.
- You can override the sheet property now from the parent component. (#47)

**Comment by mdarens** [comment]
Thanks man!
