### ISSUE TITLE
Hoist props and state to support unit testing wrapped components.

### ISSUE THREAD

**Issue by husterk** [cssinjs/react-jss#51]
The Jss class that is returned from the injectSheet function does not make available the "props" and "state" fields from the wrapped component. This makes writing unit tests against these wrapped components unnecessarily complex since I am forced to actually render the component vs just instantiating it.

I want to be able to continue writing tests as I have been for standard React components (see example below).

``` javascript
it("defaultProps: Should define expected default props.", () => {
        // Arrange
        const expected = {
            props1: "prop1Value"
            prop2: "prop2Value'"
        };

        // Act
        const result = <MyComponent />;

        // Assert
        expect(result.props).toEqual(expected);
});
```

Another option would be to expose the actual wrapped component as a field on the wrapped Jss component. This way I would have easy access to all of the features and functions of the wrapped component and it would support all of my testing needs.

**Comment by kof** [comment]
Do you have any examples for HOC's who did that well?

**Comment by husterk** [comment]
After thinking about this more we decided to go a different route in handling testing of higher order components. We decided to separate the raw component and the higher-order version of the component so that they may be tested independently.

**Comment by kof** [comment]
good choice.
