### ISSUE TITLE
pass down local jss via context provider

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/react-jss#54]
as discussed in https://github.com/cssinjs/jss/issues/352, right now styles are not being cleaned up during SSR, with `aphrodite` at least, but I think also with plain `jss` SSR.

As a solution I propose wrapping the app in a `jss` `context` provider:

```jsx
<JssProvider jss={localJss}>
  <MyApp />
</JssProvider>
```

And then creating a HOC like `injectStyles` that uses the `jss` from `context`.

With this architecture, instead of needing to clean up style sheets after each SSR, one would just create a different `localJss` for each request:

```es6
import React from 'react'
import {renderToString} from 'react-dom/server'
import {create as createJss} from 'jss'
import {JssProvider} from 'react-jss'
import MyApp from './MyApp'
import {Router} from 'express'

const app = Router()

app.get('*', (req, res) => {
  const body = renderToString(
    <JssProvider jss={createJss()}>
      <MyApp />
    </JssProvider>
  )
  // obviously not a full-blown ssr example here
  res.send(`<html><body>${body}</body></html>`)
})

export default app
```

One problem is I assume the compiled styles wouldn't be cached since `createStyleSheet` has to be called for each new instance of `jss` and plugin configuration is controlled by the instance created for SSR, meaning components can't use different `jss` configurations.

I would argue that there would be benefits to being able to create a `StyleSheet` without reference to a jss registry and then attach it to any registry later.  This would probably mean removing the registry from the `jss` instance containing plugins and passing the registry down via context provider rather than all the other configuration currently in a `jss` instance.

**Comment by kof** [comment]
> One problem is I assume the compiled styles wouldn't be cached 

What exactly would you want to cache?

**Comment by jedwards1211** [comment]
Sorry, I don't know where I got the idea of caching per se, yesterday was a whirlwind of looking into various css in jss type frameworks for me.
But there's at least a small amount of computation that happens in `createStyleSheet` to turn the JSON into rules right?  With the current SSR example `createStyleSheet` is not repeatedly called for each request, but with the approach I'm describing it would be.  All that really needs to be redone for each request is attaching to a different registry.

**Comment by kof** [comment]
Released.
