### ISSUE TITLE
No compatible version found: jss@^6.0.0

### ISSUE THREAD

**Issue by AlastairTaft** [cssinjs/react-jss#59]
When I install this package I get the above error message.

It looks like it's depending on version 6 of jss which isn't on npm (5.5.6) is the latest.

Got a few broken builds.

**Comment by kof** [comment]
Hmm its a circular dependency problem right now, jss 6 is on the way. Why did you upgrade to react-jss 5.0 , its a major release, you shouldn't be updating it automatically.

**Comment by AlastairTaft** [comment]
I had the flag as "*" in my project. Which is a little loose, but yeah the fix is to fix the version, just bringing it to your attention.

**Comment by kof** [comment]
yep! thanks!

**Comment by kof** [comment]
its released, check it out.,

**Comment by AlastairTaft** [comment]
👍
