### ISSUE TITLE
dependency incompatibility

### ISSUE THREAD

**Issue by misha-pachin** [cssinjs/react-jss#60]
Hello there. In the last version of the 'react-jss' module (5.0.0) there is **jss@^6.0.0** dependency in package.json, but you can check it by typing `npm show jss` that there are only **jss@5.5.6** currently in npm. It takes an effort from me to understand what the problem is when I tried to install this module, so please fix this in case somebody as a junior developer like me run into this problem again :)

**Comment by kof** [comment]
Please don't usee react-jss 5 yet, and tip: never use a flexible major version in your dependencies. Fix is comming though.
