### ISSUE TITLE
Source order

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#61]
By design, React renders parents first, children second. This results in sheets rendered from parent first, child second. When you pass a class name from the parent to the child, childs style is later in the head, so it has a higher source order specificity and you can't override it from the parent without using '!important'.

Now we need to think of a way to reverse order for sheets rendering: child's sheet first, parents sheet second.

cc @nathanmarks

**Comment by cvle** [comment]
You can solve this by introducing a `createStyles` function, that assigns an index to the styles using a global index counter.

~~~js
import React from 'react'
import injectSheet from 'react-jss'

let globalIndex = 0

function createStyles(styles) {
  return { 
    styles,
    index: globalIndex++
  }
}

const styles = createStyles({
  button: {
    backgroundColor: 'yellow'
  },
  label: {
    fontWeight: 'bold'
  }
})

const Button = ({sheet: {classes}, children}) => (
  <button className={classes.button}>
    <span className={classes.label}>
      {children}
    </span>
  </button>
)

// injectSheet uses index when creating the style sheet.
export default injectSheet(styles)(Button)
~~~

Naturally this is a breaking change to the current API.

**Comment by kof** [comment]
lets go for it!

**Comment by kof** [comment]
released and merged, thanks!!!!
