### ISSUE TITLE
Question about use with dynamic styles

### ISSUE THREAD

**Issue by jcheroske** [cssinjs/react-jss#64]
I built a small theming HOC that injects a jss sheet dynamically, and I would like some feedback on my approach. Specifically, I'm wondering if what I have done has decent code smell and doesn't violate certain assumptions and/or best practices of the jss and react-jss libraries.

I saw cssinjs/jss#170, but I wanted a solution that lets me write all of my styles using the full jss syntax, and not one that forced me into only using a subset of the syntax. Here is my HOC:

```
import { inject } from 'mobx-react'
import { compose, createEagerElement } from 'recompose'
import injectSheet from 'react-jss'

export const applyTheme = ( mapThemeToStyles = () => ({}), mapThemeToProps = () => ({}) ) =>
  compose(
    // Get the theme from a mobx store, then call the
    // mapping functions to create the dynamic jss and
    // any additional theme-based props
    inject(({themeStore: {theme}}, props, context) => ({
      ...mapThemeToProps(theme, props, context),
      themeStyles: mapThemeToStyles(theme, props, context)
    })),
  
    // Take the dynamically generated jss and call injectStyles
    // with it. This is the part I'm wondering about...
    BaseComponent => {
      const OuterHelper = ({themeStyles, ...rest}) => {
        const InnerHelper = injectSheet(themeStyles)(BaseComponent);
        InnerHelper.displayName = 'applyTheme-InnerHelper';
        return createEagerElement( InnerHelper, rest );
      };
      OuterHelper.displayName = 'applyTheme-OuterHelper';
      return OuterHelper;
    }
  );
```

Using the HOC looks like this:
```
const mapThemeToStyles = theme => ({
  button: {
    borderWidth: theme.button.borderWidth
  }
});

const enhancer = applyTheme(mapThemeToStyles);

const SomeButton = props => {
...
};

export default enhancer(SomeButton)
```
It works, but I'm not sure that I haven't done something horrible.

**Comment by kof** [comment]
What happens on every render?

**Comment by jcheroske** [comment]
The code runs fine and renders correctly. I've modified the theme during runtime, and the UI updates great. I guess what I'm asking is not so much a, "Why is it broken?" question, but I'm more wondering if what I've done is just bad code and why? And if so, how can it be improved? To say it another way, I can't imagine that dynamic styles wouldn't have already been included in react-jss if they were easy. There must be something wrong with my code, no?

**Comment by kof** [comment]
Thats why I am asking what happens on every render when props you use in the theme change … a sheet in react-jss is shared between all elements. So if one element has different props than the other what happens?

**Comment by jcheroske** [comment]
I understand what you're saying now. I think the current implementation of react-jss isn't going to work for my needs. I'm messing around with a modified HOC that generates a dynamic stylesheet, and I have noticed that, if I call `jss.createStyleSheet()` twice with the same rules I will get two sheets that have the same class names. Am I seeing that correctly? The class names are a hash of the rules?

**Comment by kof** [comment]
> The class names are a hash of the rules? 

https://github.com/cssinjs/jss/blob/master/src/utils/generateClassName.js#L9

Class name is based on style object , meta and rule name.

**Comment by jcheroske** [comment]
Thanks. I dug around and found that. GT

**Comment by jcheroske** [comment]
Thanks. I dug around and found that. It seems like maybe there's three different general categories for how jss would be used:

1) Static styles applied to all components of a given type. This is what react-jss does
2) Dynamic styles applied to all components of a type. This is general theming usage.
3) Dynamic styles applied to one component instance. This is the most flexible, but requires a sheet per component instance.

I've got an HOC that's doing number 3 now, and it's working pretty well. I realize it's very simplistic. I'm really just trying to wrap my head around this stuff. Thanks for your patience.

```
import { inject } from 'mobx-react'
import { Component } from 'react'
import getDisplayName from 'react-display-name'
import { jss } from 'react-jss'
import { createEagerElement } from 'recompose'
import { composeWithName } from '../recompose-extras'

export const applyTheme = ( mapThemeToStyles = () => ({}), mapThemeToProps = () => ({}) ) => composeWithName(
  'applyTheme',
  inject(({themeStore: {theme}}, props, context) => ({
    ...mapThemeToProps(theme, props, context),
    themeStyles: mapThemeToStyles(theme, props, context)
  })),
  BaseComponent => class extends Component {
    static displayName = 'applyTheme-DynamicStyleManager';
    sheet;

    constructor(props) {
      super(props);

      this.attachSheet();
    }

    attachSheet() {
      this.sheet = jss.createStyleSheet(this.props.themeStyles, {
        link: true,
        meta: getDisplayName(BaseComponent) + '-dynamic'
      }).attach();
    }

    detachSheet() {
      jss.removeStyleSheet(this.sheet);
      this.sheet = undefined;
    }

    componentWillUpdate({themeStyles}) {
      this.detachSheet();
      this.attachSheet();
    }

    componentWillUnmount() {
      this.detachSheet();
    }

    render() {
      const {themeStyles: _, ...rest} = this.props;
      const {classes} = this.sheet;
      return createEagerElement(BaseComponent, {classes, ...rest});
    }
  }
);
```

**Comment by kof** [comment]
> three different general categories for how jss would be used

yep

> trying to wrap my head around this stuff. Thanks for your patience.

take a look at this issue https://github.com/cssinjs/jss/issues/356

**Comment by jcheroske** [comment]
Thanks for the pointer to that thread. I'm interested in seeing how this all shakes out. In the meantime, here's a simple take on dynamic styles that supports both class-level styles and instance-level styles that seems to meet my needs. Any feedback is much appreciated.

```
import { inject } from 'mobx-react'
import { Component } from 'react'
import { jss } from 'react-jss'
import { compose, createEagerElement, getDisplayName } from 'recompose'

const InstanceSheetInjector = BaseComponent => class extends Component {
  static displayName = 'applyTheme-instanceSheet';
  instanceSheet;

  constructor(props) {
    super(props);
    this.attachSheet();
  }

  componentWillUpdate({themeStyles}) {
    this.detachSheet();
    this.attachSheet();
  }

  componentWillUnmount() {
    this.detachSheet();
  }

  render() {
    const {themeStyles: _, ...rest} = this.props;
    const {classes} = this.instanceSheet;
    return createEagerElement(BaseComponent, { classes, ...rest });
  }

  attachSheet() {
    this.instanceSheet = jss.createStyleSheet(this.props.themeStyles, {
      link: true,
      meta: getDisplayName(BaseComponent) + '-instanceSheet'
    }).attach();
  }

  detachSheet() {
    jss.removeStyleSheet(this.instanceSheet);
    this.instanceSheet = undefined;
  }
};

const ClassSheetInjector = BaseComponent => {
  let
    classSheet,
    instanceCount = 0,
    updateId = 0;

  return class extends Component {
    static displayName = 'applyTheme-classSheet';
    updateId = 0;

    constructor(props) {
      super(props);

      if (instanceCount === 0) {
        this.attachSheet();
      }
      instanceCount++;
    }

    componentWillUpdate({themeStyles}) {
      if (this.updateId === updateId) {
        this.detachSheet();
        this.attachSheet();
        updateId += 1;
      }
      this.updateId = updateId;
    }

    componentWillUnmount() {
      instanceCount--;
      if (instanceCount === 0) {
        this.detachSheet();
      }
    }

    render() {
      const {themeStyles: _, ...rest} = this.props;
      const {classes} = classSheet;
      return createEagerElement(BaseComponent, { classes, ...rest });
    }

    attachSheet() {
      classSheet = jss.createStyleSheet(this.props.themeStyles, {
        link: true,
        meta: getDisplayName(BaseComponent) + '-classSheet'
      }).attach();
    }

    detachSheet() {
      jss.removeStyleSheet(classSheet);
      classSheet = undefined;
    }
  }
};

export const applyTheme = ( mapThemeToStyles = () => ({}), mapThemeToProps = () => ({}), {sheetPerInstance = false} = {} ) => compose(
  inject(({themeStore: {theme}}, props, context) => ({
    ...mapThemeToProps(theme, props, context),
    themeStyles: mapThemeToStyles(theme, props, context)
  })),
  sheetPerInstance ? InstanceSheetInjector : ClassSheetInjector
);
```

**Comment by kof** [comment]
Closing this for now as I don't know what to do.

**Comment by jcheroske** [comment]
That's fine. I was just looking for some help making jss more dynamic. I've
got a working solution now. Thanks for your input.

Jay

**Comment by gitsupersmecher** [comment]
@jcheroske - thanks a lot of starting this thread! It really helped, and saved a lot of hours of reading code. You really rock!

**Comment by kof** [comment]
Thread is very old, we switched to counters based class name generator!

**Comment by gitsupersmecher** [comment]
Thanks @kof! I will follow the other discussion and improvements, that you shared. This discussion helped to get me started.
