### ISSUE TITLE
problem with flowtype

### ISSUE THREAD

**Issue by mattcolman** [cssinjs/react-jss#65]
Hi, when I wrap a Component using injectSheet my flowtype returns "no errors" when there are errors. Not sure if this is a flowtype problem, react-jss problem, or a me problem...

Here is my main test file:
```
// @flow
import Greeter from './Greeter';

<Greeter />;
<Greeter name={null} />; // `name` should be a string
<Greeter name="World" />; // "Hello, World!"
```

Greeter component without injectSheet - running `flow` shows errors:
```
// @flow
import React, { Component } from 'react';

type Props = {
  name: string,
};

class Greeter extends Component {

  props: Props;

  render() {
    return <p>Hello, {this.props.name}!</p>;
  }
}

export default Greeter;

```

Greeter component with injectSheet - running `flow` shows 'no errors':
```
// @flow
import React, { Component } from 'react';
import injectSheet from 'react-jss';

type Props = {
  name: string,
};

class Greeter extends Component {

  props: Props;

  render() {
    return <p>Hello, {this.props.name}!</p>;
  }
}

const styles = {
  main: {
    background: 'red',
  },
};

export default injectSheet(styles)(Greeter);
```

Any help will be appreciated. 
Thanks, 
Matt.

**Comment by kof** [comment]
injectSheet returns  a HOC and probably flow can't follow the props deeper into your component, it probably stops by the HOC which has no validation for this prop.

I haven't tried to workaround this yet, sounds like an interesting issue!

**Comment by brandonmp** [comment]
i dug into this a little bit, but came up short.  

It looks like it's an [outstanding question](http://stackoverflow.com/questions/39358847/how-to-type-an-exported-relaycontainer) for the Relay HOC as well.

The [Flow docs](https://flowtype.org/docs/react.html#higher-order-components) were updated relatively recently with an HOC example, but I can't figure out to apply the example to this case.

**Comment by kouak** [comment]
Hello,

I wrote basic flow type definitions for React-JSS here : https://gist.github.com/kouak/4e05908b64ebc0f2b5a138a06359bbd5

These are heavily inspired by [react-redux definitions](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.30.x-/react-redux_v5.x.x.js) from the [flow-typed project](https://github.com/flowtype/flow-typed) and work fine for both stateless functional components and regular class components.

I don't have the skillset nor the time to contribute them properly to [flow-typed](https://github.com/flowtype/flow-typed) but feel free to use them in your project.

**Comment by mattcolman** [comment]
works a treat! nice work @kouak

**Comment by mattcolman** [comment]
trying now to get this working with `export const injectSheet = createInjectSheet(jss)` :/

**Comment by tmonte** [comment]
I'm having problems related to this also. I'm using the same definitions from @kouak, and they work fine as long as I'm on the same file. If I import "TestComponent" for example, and don't pass in required props, flow shows "No errors." I believe I need to add explicit types to my injector, but I'm having problems doing so:
```javascript
const injector: Injector<Props, void, void, void> = injectSheet(styles)
```
to which I get the some errors like:
```
inconsistent use of library definitions
type parameter `OP` of function call. Expected object instead of function call.
...
```
Any ideas on what I'm doing wrong?

**Comment by mattcolman** [comment]
@tmonte can you show us all the code that is not working. From what you've described it works for me.

**Comment by tmonte** [comment]
The code is exactly the same code in the gist: https://gist.github.com/kouak/4e05908b64ebc0f2b5a138a06359bbd5

I just exported the component
```javascript
const injector: Injector<P, *, *, *> = injectSheet(styles)
export const StyledFunc = injector(TestComponentFunc);
```

then in a different component:
```javascript
import React from 'react'
import { StyledFunc } from './styled-func'

const Container = props => <div><StyledFunc value={1} /></div> // This works
```

It fails if I don't pass the required props:
```javascript
const Container = props => <div><StyledFunc /></div> // Errors: no required props
```

But in both I get those other two errors. I didn't paste all the error description because it's really long.

**Comment by kouak** [comment]
I tried to fiddle with your example a bit and couldn't get it to work.

Unfortunately, my knowledge of FlowType is too limited to properly debug the issue :(

**Comment by kouak** [comment]
I came up with a different way that seems to work.

See here : https://github.com/kouak/jss/commit/ebb9230c38bc99ce6124dc9327615f592925be08

What do you think ?

**Comment by tmonte** [comment]
@kouak that seems to work for class components, but not for function ones.
If you go to App.js, and remove the text prop from StyledFunc, flow is still happy, when it should actually fail.

**Comment by kouak** [comment]
Yeah, I don't know whether my definitions are wrong or this is a flow bug.

Having flow complain in the same file and be fine after an import is definitely weird.

**Comment by tmonte** [comment]
It is, from what I found on other issues there you need to explicitly annotate the typing for the connector. See this issue and comment: https://github.com/facebook/flow/issues/2883#issuecomment-262701667
My problem is that when I typed my connector on your previous defs I got those errors.

**Comment by tmonte** [comment]
@kouak I got it to work by adding the types explicitly: https://gist.github.com/tmonte/406fcb19e8df8920e199d323d0374e35

**Comment by mattcolman** [comment]
nice work @tmonte ! Agree it's odd that we have to explicitly type FunctionalComponents, but hey, it works!

**Comment by tmonte** [comment]
Thanks @kouak for the work on the definitions. @mattcolman yeah they sem to work okay for me. I think we can close this if it works for you too.

**Comment by mattcolman** [comment]
I think without committing the types anywhere users of react-jss will still experience this problem, so I'm not sure if the issue should be closed. Ideally types are committed to flowtyped to close off this issue. But I'm easy, close if you like.

**Comment by tmonte** [comment]
You're right, I'll try to submit them to flow-typed.

**Comment by wizardzloy** [comment]
Hey, guys, I opened a [PR](https://github.com/flowtype/flow-typed/pull/941) to the flow-typed repo, please take a look and comment/improve the typings there.

@kof could you please take a look if I didn't mess things up there

**Comment by iamstarkov** [comment]
@kof ping

**Comment by kof** [comment]
@wizardzloy we released today react-jss 7, can you please update the typings in flow-typed repo?

**Comment by wzrdzl** [comment]
Oh, I somehow missed the comment above, let me know if we still need the typings for` react-jss@7.x.x`

**Comment by kof** [comment]
@wzrdzl there has been 2 breaking changes between v6 and v7 https://github.com/cssinjs/react-jss/blob/master/changelog.md#breaking-changes-1

**Comment by wzrdzl** [comment]
ok, I will take a look in the evening!

**Comment by kof** [comment]
Thanks!

**Comment by wzrdzl** [comment]
I opened a PR for react-jss@7 typings here https://github.com/flowtype/flow-typed/pull/1141
A quick question, shall we maybe use flow in `react-jss`'s sources, same as we do in `jss`. It would be easier to define certain types, for example currently there is no working solutions to import types from a specific version of your dependency in type definitions file in flow-typed, whereas it is easy to do if you define your types in sources

**Comment by kof** [comment]
Yes, it just needs to be added

**Comment by kof** [comment]
Btw. there is https://www.npmjs.com/package/react-flow-types

**Comment by mattcolman** [comment]
When I ran `flow-typed upgrade` it didn't find the latest react-jss flow typings `react-jss_v7.x.x.js`. Instead it just gave me the old generated stub `react-jss_vx.x.x.js` ?
![2017-09-01 09-59-08](https://user-images.githubusercontent.com/1013215/29949999-39dc7ed8-8efc-11e7-8455-6c3f6a0ea7cc.png)

**Comment by wzrdzl** [comment]
@mattcolman what version of flow do you use? Currently the typings support `flow_v0.30.x-v0.52.x`. In `flow@0.53.x` React typings were changed significantly so that it requires completely different typings for `react-jss` as well and it is not implemented yet

**Comment by mattcolman** [comment]
oh right. k thanks! I was using flow@0.53
