### ISSUE TITLE
Pass only classes, but not whole sheet?

### ISSUE THREAD

**Issue by just-boris** [cssinjs/react-jss#67]
Currently I am receiving the whole `sheet` object into the component:

```js
const Button = ({sheet: {classes}}) => (
  <button className={classes.button}>Click me</button>
);
```

However, I am using only `classes` property. So, it could be much shorter

```js
const Button = ({classes}) => (
  <button className={classes.button}>Click me</button>
);
```

Not a big deal, but it is very overwhelming to write `{sheet: {classes}}` for *every* component. What else can I do with `sheet` object within the component? I don't see any, so I'd like to write less.

**Comment by kof** [comment]
You can do some other things with the sheet object. Though in the 99% of my cases I also just use the classes. We should consider passing classes additionally to sheet to the component. @giuseppeg wdyt?

**Comment by giuseppeg** [comment]
that'd be handy

**Comment by kof** [comment]
Ok then lets do this. We need to consider that user might be using this property as well, because its very generic. I think if there is a passed classes object, we shouldn't overwrite it and in this case you will have to go over sheet.classes as right now.

**Comment by kof** [comment]
@just-boris you wanna send a pr?

**Comment by kof** [comment]
published
