### ISSUE TITLE
[help-wanted][mui] Dynamically updating the injected sheet

### ISSUE THREAD

**Issue by pierrecholhot** [cssinjs/react-jss#70]
I am trying to update the stylesheet injected with `react-jss` with no luck.

Following the [docs](http://cssinjs.org/js-api?v=v6.2.0#set-or-get-a-rule-property-dynamically), I expected the following code to work:

```
  constructor(props) {
    super(props)
    const theme = this.props.muiTheme
    this.props.sheet.getRule('root').prop('backgroundColor', theme.palette.canvasColor)
    this.props.sheet.getRule('root').prop('color', theme.palette.textColor)
  }
```

I tried appending both `detach()` and `attach()` respectively to try to refresh the stylesheet, but still it doesn't get updated in the DOM.

Any ideas ? I am using `react-jss`'s `injectSheet` directly, no custom setups.

**Comment by kof** [comment]
It makes more sense u describe what problem u are solving, where u  are heading.

**Comment by pierrecholhot** [comment]
Thanks for that fast reply,
I will try to describe the problem again:

I am using `react-jss` with Material UI.  
In Material UI, I defined a couple of Themes (Colors / Margins / Typo, ...) and I am able access these variables in all of my components from `this.props.muiTheme`.

My issue is when trying to forward these colors (or any other component prop), to `react-jss` Sheet

```js
import React from 'react'
import muiThemeable from 'material-ui/styles/muiThemeable'
import injectSheet from 'react-jss'

const styles = {
  button: {
    // how do I set this variable
    // to the Buttons's (muiTheme.primaryColor) ?
    backgroundColor: 'yellow' 
  },
  label: {
    fontWeight: 'bold'
  }
}

const Button = ({classes, children, muiTheme}) => (
  <button className={classes.button}>
    <span className={classes.label}>
      {children}
    </span>
  </button>
)

const ThemableComponent = muiThemeable()(Button)
const StyledComponent = injectSheet(Stylesheet)(ThemableComponent)
export default StyledComponent
```


Once I inject a stylesheet into my component using `injectSheet`, I cannot find a working API to add or update declarations/properties on that same stylesheet.

I extracted a simplified version of my [not working] code below:
 
```js
import React, { PropTypes } from 'react'
import injectSheet from 'react-jss'

const Stylesheet = {
  root: {
    height: '100%'
  }
}

class App extends React.Component {

  constructor(props) {
    super(props)
    const { sheet, muiTheme } = this.props
    this.props.sheet.getRule('root').prop('backgroundColor', this.props.muiTheme.palette.canvasColor)
    this.props.sheet.getRule('root').prop('color', this.props.muiTheme.palette.textColor)
  }

  render() {
    return (
      <div className={this.props.classes.root}></div>
    )
  }
}

App.propTypes = {
  sheet: PropTypes.object.isRequired,
  classes: PropTypes.object.isRequired,
  muiTheme: PropTypes.object.isRequired,
}

const ThemableComponent = muiThemeable()(App)
const StyledComponent = injectSheet(Stylesheet)(ThemableComponent)
export default StyledComponent
```

In the previous code, my issue is with
```
this.props.sheet.getRule('root').prop('backgroundColor', this.props.muiTheme.palette.canvasColor)
```
that doesn't update the injected CSS in the DOM.


I hope it's a bit clearer! Cheers

**Comment by kof** [comment]
I see now, so first of all you are using the current stable mui, which isn't based on JSS, I haven't used it yet.

**Comment by pierrecholhot** [comment]
Yes I agree, but this issue isn't about MUI at all ; Any other props have the same problem.

Is this code valid ? Do you expect that this code updates the values of the injected CSS ?

```
this.props.sheet.getRule('root').prop('backgroundColor', this.props.muiTheme.palette.canvasColor)
```

**Comment by pierrecholhot** [comment]
I managed to get it working using the following code:

```js
this.props.sheet.addRule('root', {
  backgroundColor: theme.palette.canvasColor,
  color: theme.palette.textColor
})
```

**Comment by kof** [comment]
Things you need to consider:

1. react-jss sheets are reused across elements, which means is that if you modify a rule from one component instance, it is modified in all others
2. for modifications you needed to pass  a `link: true` option, its described right in the documentation you pointed me to.
3. I recommend using the beta mui, which uses JSS, its not fully ready though.
4. react-jss is basically lacking the possibility for dynamic styling at render time, this will be added at some point, follow [this issue](https://github.com/cssinjs/jss/issues/356). MUI beta is using [jss-theme-reactor](http://cssinjs.org/jss-theme-reactor?v=v0.9.0) which allows you to do that, maybe its a better option for you as of today

**Comment by pierrecholhot** [comment]
@kof thanks for these clarifications, indeed `jss-theme-reactor` seems to be my best option!
