### ISSUE TITLE
ThemeProvider

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#72]
[Here](https://github.com/styled-components/styled-components/blob/master/src/models/ThemeProvider.js) is a good example of how to implement a ThemeProvider.

As we now have function values it will be nice to have a theme object there.

```
const styles = {
  button: {
    color: (props) => props.theme.color
  }
}
const Button = ({classes}) => <button className={classes.button} />
const StyledButton = injectSheet(styles)(Button)

<ThemeProvider theme={theme1}>
   <StyledButton />
  <ThemeProvider theme={theme2}>
     <StyledButton />
  </ThemeProvider>
</ThemeProvider>
```

**Comment by kof** [comment]
@jcperez-ch you may want to give this one a shot.

**Comment by jcperez-ch** [comment]
Looks neat... it was similar to my original idea! I like it 👍

**Comment by kof** [comment]
They (and redux) implement the workaround for changes propagation to the context using pubsub.

**Comment by kof** [comment]
@jcperez-ch if you feel like you want to port it to react-jss I am happy to let you do it!

**Comment by kof** [comment]
Btw. I am wondering if there is any generic package that can be used to implement a ThemeProvider easily.

**Comment by mxstbr** [comment]
It exists: https://github.com/reacttraining/react-broadcast

Adds another wrapper component though, so I basically took that implementation and inlined it into our components.

**Comment by kof** [comment]
There should be a way to not copy paste that…

**Comment by jcperez-ch** [comment]
So, I guess the whole idea is to have a `ThemeProvider` component that uses the broadcast strategy for context changes propagation, so the current JssWrapper can consume that change and refresh the styles (if changed) based on the new theme, right?

Also, there is a possibility to compose the theme one on the top of the other.  Looks challenging! I am down to branch out and start the gig.  I might need you guys as reviewers!

**Comment by kof** [comment]
The main use case right now for the ThemeProvider is to receive a theme object inside of the function values. The need for the broadcast is just a work around the  reacts shouldComponentUpdate logic. I would not implement anything else right now as we need to see if there is a specific use case.

**Comment by iamstarkov** [comment]
we have a use-case for this

**Comment by kof** [comment]
@iamstarkov tell us!

**Comment by iamstarkov** [comment]
i would, hold on

**Comment by iamstarkov** [comment]
This is my validation of this idea https://github.com/iamstarkov/isolated-kit
This is ongoing pull-request to ours UI kit https://github.com/nordnet/nordnet-ui-kit/blob/feat/pure-jss-2/src, ([ThemeProvider][], [withTheme][] and Example [Component][])

[ThemeProvider]: https://github.com/nordnet/nordnet-ui-kit/blob/feat/pure-jss-2/src/hocs/theme-provider.js
[withTheme]: https://github.com/nordnet/nordnet-ui-kit/blob/feat/pure-jss-2/src/hocs/with-theme.js
[Component]: https://github.com/nordnet/nordnet-ui-kit/blob/feat/pure-jss-2/src/components/badge/badge.jsx

**Comment by iamstarkov** [comment]
But I have another suggestion to leverage theme usage.

_**Current** (this way color is dynamic prop, without a real need for that):_

```jsx
import injectSheet, { withTheme } from 'react-jss';
const styles = {
  alert: {
    color: ({ theme }) => color(theme.color.primary).hex(),
  }
}
const Alert = ({ classes, children }) => (
  <div className={classes.alert}>
    { children }
  </div>
)
export default withTheme(injectSheet(styles)(Alert))
```

_**Suggestion** (this way color is static for real per theme):_
```jsx
import { injectThemedStyles } from 'react-jss';
const styles = theme => ({
  alert: {
    color: color(theme.color.primary).hex(),
  }
})
const Alert = ({ classes, children }) => (
  <div className={classes.alert}>
    { children }
  </div>
)
export default injectThemedStyles(styles)(Alert))
```

what do you think?

**Comment by kof** [comment]
This is what [jss-theme-reactor](https://github.com/nathanmarks/jss-theme-reactor) currently does.

1. One tradeoff of this approach is that you have no access to the props inside of the styles function. You will need to compose classes inside of the `render` if they depend on props. For e.g. if prop "disabled" is passed, you will need to compose 2 classes `classNames(classes.default, classes.disabled)`, where using function value it could return the value depending on the props.

2. Another tradeoff is that you will produce all styles for each theme. There will be no common styles for all themes and then specific styles depending on what theme it is. For e.g. a button has core styles that are independent of a theme and theme dependent styles. If we create 3 differently themed buttons, amount of generated styles will be `allStyles * 3`, where if we would reuse same parts it would be `coreStyles + (themeStyles * 3)`

**Comment by kof** [comment]
On the other hand there should be no 100 differently themed buttons in one application, one theme should handle all variants/states.

**Comment by kof** [comment]
I think actually for a limited amount of variations like theming this should be a good way, lets support this pattern as well!

**Comment by kof** [comment]
Actually we should think of function values more like a replacement for inline styles rather than for theming.

**Comment by iamstarkov** [comment]
> This is what jss-theme-reactor currently does.

i disagree, jss-theme-reactor does that by bringing in new `StyleManager` entity, which increases cognitive load for everybody.

My current HoC-based approach doesnt bring new entities on the scene. its being handled by only by context, and we all are used to it. Also it doesnt distuingish theme from any other component's props, so it simplify things by order of magnitude. Though, it has several problems, like theme based css props are considered "dynamic".

In suggested proposal, i acknowledged those pitfalls and agreed that theme is supposed to be shared among all css props. Somewhat legit way is to have styles as a function from theme. My idea is:
* ThemeProvider is broadcasting theme changes to injectThemedStyles.
* injectThemedStyles are react to emitted changes from ThemeProvider and compile styles with theme, and pass it down to injectStyles.

pseudo code will tell it all
```jsx
<ThemeProvider theme={theme} /> // broadcast.emitMessage(theme); also, dont rerender children


const injectThemedStyles = stylesFn => child => broadcast.onMessage(
  theme => injectSheet( stylesFn(theme) )(child)
) 
```

> Another tradeoff is that you will produce all styles for each theme

with this approach i would regenerate all theme related css props as static ones. And thats fine, because once I changed the theme, i dont need previous theme's static styles.

**Comment by kof** [comment]
> i disagree, jss-theme-reactor does that by bringing in new StyleManager entity, which increases cognitive load for everybody.

I was't talking about HOC vs function inside of render, I consider it implementation detail. I was talking about a function that returns styles and receives a theme.

**Comment by kof** [comment]
>  Also it doesnt distuingish theme from any other component's props, so it simplify things by order of magnitude

Your example uses theme as an argument. I assumed that the styles in your example should only have an access to the theme object, not to the props. This makes sense, because otherwise you will need to call that function on every props change and rerender styles or implement some diffing.

**Comment by kof** [comment]
Otherwise, yes I totally agree, this is a good way for static theming when the theme is known in advance and we don't use many themes on the same page.

**Comment by iamstarkov** [comment]
I made a [thing](https://github.com/iamstarkov/isolated-kit/tree/feat/react-jss-with-theming#react-jsstheming)

```sh
git clone git@github.com:cssinjs/react-jss.git
cd react-jss
git checkout feat/theming
npm install
npm run build:lib
npm link
cd ..

git clone git@github.com:iamstarkov/isolated-kit.git
cd isolated-kit
git checkout feat/react-jss-with-theming
npm install
npm link react-jss
npm start
```

Open http://localhost:6060/ and look at `DynamicThemedBox` and `StaticThemedBox` components.

**Comment by iamstarkov** [comment]
DynamicThemedBox https://github.com/iamstarkov/isolated-kit/blob/feat/react-jss-with-theming/src/components/dynamic-themed-box/index.js

```js
import React from 'react';
import c from 'color';
import injectSheet, { withTheme } from 'react-jss';

const styles = {
  alert: {
    padding: '.75em 1.25em',
    marginBottom: '1em',
    border: '1px solid transparent',
    borderRadius: '.25em',
    display: 'block',
    color: ({ theme }) => c(theme.colors.variants.success).darken(0.3).hex(),
    borderColor: ({ theme }) => c(theme.colors.variants.success).lighten(0.4).hex(),
    backgroundColor: ({ theme }) => c(theme.colors.variants.success).lighten(0.5).hex(),
    borderRadius: 10,
  }
};

const DynamicThemedBox = ({ classes, children }) => (
  <div className={classes.alert}>
    { children }
  </div>
)

export default withTheme(injectSheet(styles)(DynamicThemedBox));
```
![screen shot 2017-04-20 at 2 48 14 am](https://cloud.githubusercontent.com/assets/559321/25208279/dbd6b188-2573-11e7-9246-d1ea03d29a41.png)

**Comment by iamstarkov** [comment]
StaticThemedBox https://github.com/iamstarkov/isolated-kit/blob/feat/react-jss-with-theming/src/components/static-themed-box/index.js

```js
import React from 'react';
import c from 'color';
import { injectThemedSheet } from 'react-jss';

const styles = theme => ({
  alert: {
    padding: '.75em 1.25em',
    marginBottom: '1em',
    border: '1px solid transparent',
    borderRadius: '.25em',
    display: 'block',
    color: c(theme.colors.variants.success).darken(0.3).hex(),
    borderColor: c(theme.colors.variants.success).lighten(0.4).hex(),
    backgroundColor: c(theme.colors.variants.success).lighten(0.5).hex(),
    borderRadius: 10,
  }
});

const StaticThemedBox = ({ classes, children }) => (
  <div className={classes.alert}>
    { children }
  </div>
)

export default injectThemedSheet(styles)(StaticThemedBox);
```

![screen shot 2017-04-20 at 2 51 05 am](https://cloud.githubusercontent.com/assets/559321/25208335/543dad16-2574-11e7-98c0-44252af1a5a6.png)

**Comment by kof** [comment]
tbc in https://github.com/cssinjs/react-jss/issues/91

**Comment by iamstarkov** [comment]
submitted initial theming support in #95, just `ThemeProvider` and `withTheme` for now
