### ISSUE TITLE
Problem with function values and injectSheet

### ISSUE THREAD

**Issue by lttb** [cssinjs/react-jss#73]
Huge thanks for function values implemention!
But I ran into some problems with function values and `injectSheet`

[Online example](https://www.webpackbin.com/bins/-KfGQbpUQlp_wYy3DSGi)

It seems that:
- if we have some classes with function values - classes without them don't reach in `classes`
- function values dont work with `StyleSheet` (there is also problem with values like `font-size` -they stay as `fontSize`)
- but if we use pseudo classes/elements, it's alright

## Example of code and  rendered view:

![image](https://cloud.githubusercontent.com/assets/11135392/23945472/b077d98e-0987-11e7-8a0c-58578b2f54be.png)

```jsx
import React from 'react'
import { render } from 'react-dom'

import jss from 'jss'
import injectSheet from 'react-jss'

const styles = {
  title: {
    fontSize: '20px'
  },
  
  app: {
    color: 'red'
  }
}

const stylesFV = {
  title: {
    fontSize: '20px',
    color: ({ color }) => color
  },
  
  app: {
    color: 'red'
  }
}

const stylesPseudoFV = {
  title: {
    fontSize: '20px',
    color: ({ color }) => color
  },
  
  section: {
    '&:hover': {
      opacity: .5
    }
  },
  
  app: {
    color: 'red',
    
    '&::before': {
      content: "'before'"
    }
  }
}

const styleSheetFV = jss.createStyleSheet(stylesFV)

const App = ({ classes }) => (
  console.log(classes), 
  <div className={classes.app}>
    <h1 className={classes.title}>jss</h1>
    
    <pre>{JSON.stringify(classes)}</pre>
    
    <p>test</p>
  </div>
)

const AppStyled = injectSheet(styles)(App)
const AppStyledFV = injectSheet(stylesFV)(App)
const AppStyledSheetFV = injectSheet(styleSheetFV)(App)
const AppStyledWithPresuoFV = injectSheet(stylesPseudoFV)(App)

render(
  <div>
    <p>plain css (no function values):</p>
    <AppStyled />
    <hr />
    
    <p>no styles for .app:</p>
    <AppStyledFV color="green" />
    <hr />
    
    <p>functiom values dont work + also something went wrong with font-size:</p>
    <AppStyledSheetFV color="green" />
    <hr />
    
    <p>expected view (with FV and pseduo):</p>
    <AppStyledWithPresuoFV color="green" />
  </div>,
  document.getElementById('root')
);


```

**Comment by kof** [comment]
Thanks for the report!

> there is also problem with values like font-size -they stay as fontSize)

https://github.com/cssinjs/jss/issues/441

> function values dont work with StyleSheet

Yeah, sheet as an injectSheet argument isn't supported yet, can you create a separate issue please?

> if we have some classes with function values - classes without them don't reach in classes

True, needs a separate issue.

**Comment by kof** [comment]
I think we can close this one, right?

**Comment by lttb** [comment]
Yep, thanks!
