### ISSUE TITLE
Support function values in StyleSheet with injectSheet

### ISSUE THREAD

**Issue by lttb** [cssinjs/react-jss#74]
From #73 

Function values dont work with sheets as injectSheet argument

[Online example](https://www.webpackbin.com/bins/-KfGdyMiVgKkWgGrdoNh)

Example:

```jsx
import React from 'react'
import { render } from 'react-dom'

import jss from 'jss'
import injectSheet from 'react-jss'

const stylesFV = {
  title: {
    fontSize: '20px',
    color: ({ color }) => color
  },
  
  app: {
    color: 'red'
  }
}

const styleSheetFV = jss.createStyleSheet(stylesFV)

const App = injectSheet(styleSheetFV)(({ classes }) => (
  <div className={classes.app}>
    <h1 className={classes.title}>jss</h1>
  </div>
))

render(
  <App color="green" />,
  document.getElementById('root')
);
```

**Comment by iamstarkov** [comment]
It does work for me

**Comment by lttb** [comment]
> It does work for me

@iamstarkov have you checked an example? It still does not work for me (expected **green** color)

![image](https://cloud.githubusercontent.com/assets/11135392/24627093/46a072d4-18bc-11e7-9e02-c2773cedb66f.png)

**Comment by razetdinov** [comment]
I don't quite get how to use functional values with react-jss. Is it possible to call sheet.update(data) with the render method?

**Comment by kof** [comment]
You don't need to do anything, react-jss calls it for you.

**Comment by kof** [comment]
Though you can call sheet.update() manually if you want to.

**Comment by octalmage** [comment]
Something I wanted to do was set the function values from inside the component, but I didn't have any luck getting that to work. Instead I went with something like this: 

```

/**
 * Higher order component to inject the width. 
 */
const injectWidth = (WrappedComponent) => {
  class PP extends React.Component {
    render() {
      const width = `${(this.props.value / this.props.max) * 100}%`;
      return <WrappedComponent {...this.props} barWidth={width} />;
    }
  }
  return PP;
};

```

Does this seem like a good approach?

**Comment by kof** [comment]
@octalmage please create a separate issue and please start with explaining your use case, what you are trying to achieve, this is a wrong thread, I am going to remove it from here. Thank you.

**Comment by octalmage** [comment]
My post was a possible solution to this issue, I feel that it fit in well. I don't have a separate question.  Feel free to remove this too.

**Comment by kof** [comment]
Due to this bug and complexity we have to deal with to introduce theming support me and @iamstarkov decided to remove StyleSheet instance support from injectSheet.
