### ISSUE TITLE
nested rule with dynamic value doesnt seem to work

### ISSUE THREAD

**Issue by xiaofan2406** [cssinjs/react-jss#76]
```
container: {
    color: props => props.color, // this works
    '&:before' : {
        content: 'text',
        color: props => props.color // this doesn't
    }
}
```

Did i miss something?

**Comment by kof** [comment]
Yeah, works right now only for top level rules. Lets keep this issue for enhancement. Not sure though if it is worth it.

**Comment by kof** [comment]
I will migrate this issue to the jss repo because it is not react-jss related.

**Comment by kof** [comment]
Issue moved to [cssinjs/jss #445](https://github.com/cssinjs/jss/issues/445) via [**ZenHub**](https://www.zenhub.com/)
