### ISSUE TITLE
How Do i get Vendor AutoPrefix support?

### ISSUE THREAD

**Issue by SeunLanLege** [cssinjs/react-jss#80]
i am new to this package, but i've checked the css output and there is no vendor prefix, please how do i enable it?.

**Comment by kof** [comment]
you don't need to do anything. If you expected a prefix we need to see your
case to validate, vendor prefixer is under a big rewrite right now and will
be autoprefixer compliant soon.

**Comment by SeunLanLege** [comment]
```
import React from 'react'
import injectSheet from 'react-jss'

const style = {
  body: {
    display: 'flex',
    transition: '2s',
    boxSizing: 'content-box',
    justifyContent: 'center',
    opacity: 0.3,
    '& h1': {
      textAlign: 'center',
      background: 'green',
      padding: '100px',
      borderRadius: '10px',
      transform: 'translateX(100px)',
      boxShadow: '10px 10px 0px 3px grey'
    },
  }
}

@injectSheet(style)
class Body extends React.Component {
  render () {
    console.log(this.props)
    const { sheet: { classes } } = this.props
    return (
      <body className={classes.body}>
        <title>Play ground</title>
        <h1>Hello World, I'm seun lanlege</h1>
      </body>
    )
  }
}
export default Body

```

![image](https://cloud.githubusercontent.com/assets/16494314/24284826/84c0d83a-106d-11e7-8b80-aa71d160b67b.png)

**Comment by SeunLanLege** [comment]
![image](https://cloud.githubusercontent.com/assets/16494314/24284908/e1bda2d4-106d-11e7-8e32-fce446b994c8.png)

**Comment by SeunLanLege** [comment]
![autoprefixer](https://cloud.githubusercontent.com/assets/16494314/24284932/f6588bd2-106d-11e7-9a21-533839f60620.png)

**Comment by kof** [comment]
Ok for "display: flex" there will be no prefix in your browser, our vendor prefixer does feature tests compared to static prefixer like auto-prefixer. It will only add prefixes if the environment requires it.

**Comment by SeunLanLege** [comment]
@kof thanks for clearing this. cheers!
