### ISSUE TITLE
Fix React 15.5 prop-types warning

### ISSUE THREAD

**Issue by dwighthouse** [cssinjs/react-jss#86]
React 15.5.0 was just released, including some forward-looking deprecations.

From now on, propTypes will be checked with the separate prop-types dependency, rather than being built into core React.

Without this change, using react-jss results in this warning in the console:

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

propTypes are used at these lines:
https://github.com/cssinjs/react-jss/blob/master/src/index.js#L90
https://github.com/cssinjs/react-jss/blob/master/src/SheetsRegistryProvider.js#L5

Explanation: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
New Dependency: https://github.com/reactjs/prop-types

**Comment by kof** [comment]
yep, thanks!

**Comment by kof** [comment]
fixed in 6.1.1
