### ISSUE TITLE
Default props are not passed to sheet.update()

### ISSUE THREAD

**Issue by kserjey** [cssinjs/react-jss#87]
Default props is not injected in update data.
[Example](https://www.webpackbin.com/bins/-KhaeerXIdMPyBidaJ9r)

**Comment by kof** [comment]
sounds like  a bug

**Comment by kof** [comment]
Its clear now - default props are defined on the inner component. Not on the hoc.

**Comment by kof** [comment]
cc @iamstarkov wdyt? should we merge defaultProps from the user component to the HOC? We currently use "hoist-non-react-statics" package which does this for all other props.

**Comment by kof** [comment]
fixed and published v6.1.0

**Comment by jedwards1211** [comment]
@kof this exact same issue was filed in `react-redux` and they **don't** consider it a bug: https://github.com/reactjs/react-redux/issues/111

As they said in that issue, if @kserjey wants a default `backgroundColor` to get passed to functions in `baseStyles`, he should explicitly add `defaultProps` to the component created by `injectSheet(baseStyles)(SomeComponent)`, not to `SomeComponent` itself.

**Comment by kof** [comment]
Yep, got it now, will try to fix both issues.

**Comment by jedwards1211** [comment]
Cool, thanks!
