### ISSUE TITLE
Integrate ThemeProvider

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#91]
@iamstarkov has been working on a unified styling solution https://github.com/iamstarkov/theming and react-jss needs to integrate it

Main issue https://github.com/cssinjs/jss/issues/488

**Comment by iamstarkov** [comment]
I need feedback, pls take a look https://github.com/iamstarkov/theming/pull/2

**Comment by Gertt** [comment]
Are you planning on adding support for the "statically themed" components as mentioned in #72 or will the theme only be available through props? [iamstarkov/theming](https://github.com/iamstarkov/theming) does not seem to force a specific approach.

Example below:

```js
import React from 'react';
import injectSheet from 'react-jss';

const styles = theme => ({
    button: {
        padding: (props) => props.compact ? 5 : 20, // this will be dynamic ofcoure
        backgroundColor: theme.color.primary
    }
});

const Button = ({ classes, children }) => (
  <button className={classes.button}>
    { children }
  </button>
)

export default injectSheet(styles)(Button);
```

**Comment by kof** [comment]
Statically themed component is basically taking a theme manually and putting it into props. Thats easy it seems.

**Comment by Gertt** [comment]
Maybe I did not explain well enough, or maybe I did not understand correctly what you are trying to say. I think calling them statically themed components is where I went wrong.

What I would like to know is: when you add support for [iamstarkov/theming](https://github.com/iamstarkov/theming), will the theme provided to its `<ThemeProvider />`:

**a)** be available only through JSS' function values (which well get the theme through props, I suppose), like so:

```js
const styles = {
    button: {
        color: props => props.theme.color.primary
    }
};

injectSheet(styles)(Component);
```

**or b)** are you open to also allow passing a function to `injectStyles` that will receive the theme as its argument, like so:

```js
const styles = theme => ({
    button: {
        color: props => theme.color.primary
    }
});

injectSheet(styles)(Component);
```

My apologies if this is what you were describing above 🙂. As a side-note, I'm happy to help out if you're open to option B but not planning on implementing it yourself.

**Comment by kof** [comment]
both!

**Comment by kof** [comment]
It is already implemented https://github.com/cssinjs/react-jss/tree/feat/theming and waiting for theming package consolidation with other cssinjs lib maintainers. We are building a unifying solution.

**Comment by Gertt** [comment]
Great, thanks! I will wait a bit before I start hacking together something custom then. 😀

**Comment by iamstarkov** [comment]
submitted initial theming support in #95, just `ThemeProvider` and `withTheme` for now

**Comment by iamstarkov** [comment]
Done in next branch
