### ISSUE TITLE
Enchanted selectors

### ISSUE THREAD

**Issue by kserjey** [cssinjs/react-jss#92]
Is it possible to make component selector by name? Like [this one](https://github.com/airbnb/enzyme/blob/master/docs/api/selector.md)?!

**Comment by kof** [comment]
Sure, you can use any attribute or separate class name to select your element.

**Comment by kserjey** [comment]
I mean React Component's displayName

**Comment by kof** [comment]
`displayName` is up to you to define, class components have them automatically, functional components would need either manual definition or a babel plugin. This hoc will take whatever is provided on your component [see here](https://github.com/cssinjs/react-jss/blob/master/src/getDisplayName.js)

**Comment by kserjey** [comment]
I'm about react-jss. Is it possible to add this selector feature in JSON Syntax?
```
import React from 'react';
import injectSheet from 'react-jss';
import SomeComponent from './SomeComponent';

const styles = {
  app: {
    '& > SomeComponent': {
      padding: '4px 8px',
      border: '1px solid black'
    }
  }
};

const App = ({ classes }) => (
  <div className={classes.app}>
    <h3>Component Selector</h3>
    <SomeComponent/> {/* styled */}
  </div>
);

export default injectSheet(styles)(App);
```

**Comment by kof** [comment]
Can you explain why you want to do that?

**Comment by kserjey** [comment]
I think it will might be useful, readable and less code. For example I have some components and elements, I want to set just margin-bottom for one of components.
```javascript
import React from 'react';
import injectSheet from 'react-jss';
import { render } from 'react-dom';

const SomeComponent1 = () => (<div>Component #1</div>);
const SomeComponent2 = () => (<article>Component #2</article>);

const styles = {
  app: {
    padding: 8,
    backgroundColor: 'lightgrey',
    border: '2px solid black',
    '& > SomeComponent1': {
      marginBottom: 8
    }
  }
};

const App = injectSheet(styles)(({ classes }) => (
  <div className={classes.app}>
    <SomeComponent1/>
    <div>Some DIV</div>
    <SomeComponent2/>
  </div>
));

render(<App/>, document.getElementById('app'));
```

**Comment by kof** [comment]
Its not only hard to implement but also ideologically problematic. By doing this you are basically overwriting something on the inner component. Inner component might not have expected this kind of override. What you currently can do is to pass a className down to that component and that component will add that class to a proper dom node. This is a bit more verbose but also more clear semantically.
