### ISSUE TITLE
Testing components with styles.

### ISSUE THREAD

**Issue by kof** [cssinjs/react-jss#93]
Motivation: when you snapshot components with jest, you can also snapshot css generated by the component. Ideally this should also work with styled-jss. Also we should support testing generated CSS without jest.

See for e.g. https://github.com/styled-components/jest-styled-components/

**Comment by kof** [comment]
Right now one can obtain all sheets by using SheetsRegistryProvider or JssProvider if you are on the next branch/pre release version.

**Comment by kserjey** [comment]
But what if i use enzyme for testing instead of jest snapshot?

**Comment by kof** [comment]
Thats fine, the example above is not using jest.

**Comment by kserjey** [comment]
I often use selectors to find component in Enzyme testing and for that i map classes to new object with next function: 
```javascript
sheet.getRule(ruleName).selectorText
```
Is there more reliable method?

**Comment by kof** [comment]
1. for testing you may want to pass your simplified selector generator so that you can use a simpler selector without counters and hardcode the result
2. you can use a different attribute for testing

**Comment by kof** [comment]
Also what about `classes` object?

**Comment by iamstarkov** [comment]
i dont get original problem of the issue

**Comment by kof** [comment]
@iamstarkov can you write down what exactly needs clarification?

**Comment by kserjey** [comment]
@iamstarkov comfortable testing functional values and styles in general

**Comment by iamstarkov** [comment]
@kserjey its easy. one things to note is you dont need to test injectSheet:

```js
// src/components/button/index.js
import injectSheet from 'react-jss'
import styles from './styles'
import Button from './button'

export default injectSheet(styles)(Button)


// src/components/button/styles.js
export default {
  button: { /* */ },
  block: { /* */ },
  active: { /* */ },
  disabled: { /* */ },
}

// src/components/button/button.js
import React, { PropTypes } from 'react';
import cn from 'classnames';

export const Button = ({
  classes,
  children,
  tag: Tag,
  block,
  active,
  disabled,
}) => {
  const isInput = Tag === 'input';
  const isLink = Tag === 'a';
  return (
    <Tag
      className={cn({
        [classes.button]: true,
        [classes.block]: block,
        [classes.active]: active,
        [classes.disabled]: disabled,
      })}
      disabled={ disabled ? true : null }
      aria-pressed={ (isLink && active) ? true : null }
      aria-disabled={ (isLink && disabled) ? true : null }
    >
      { !isInput ? children : null }
    </Tag>
  );
};


Button.propTypes = {
  classes: PropTypes.object.isRequired,
  /** Anything that can be rendered for Buttons and Text for tag="inputs" placed in `value` attribute */
  children: PropTypes.node,
  /** Block */
  block: PropTypes.bool,
  /** Active state */
  active: PropTypes.bool,
  /** Disabled state */
  disabled: PropTypes.bool,
  /** Tag */
  tag: PropTypes.string,
}

Button.defaultProps = {
  tag: 'button',
  block: false,
  active: false,
  disabled: false,
  onClick: ()=>{},
}

export default Button;

// src/components/button/button.test.js
import React from 'react';
import test from 'ava';
import { shallow } from 'enzyme';

import Button from './button';
import styles from './styles';

const reduceClasses = (prev, curr) => Object.assign({}, prev, { [curr]: curr })

const classes = Object.keys(styles).reduce(reduceClasses, {})

const child = "testChild";

test('Basic render', t => {
  const component = shallow(
    <Button sheet={{ classes }}>
      { child }
    </Button>
  );

  t.true(
    component.is('button'),
    "it should be a type `button`"
  );

  t.true(
    component.contains(child), 
    "it should contain correct children"
  );
});

test('Tags', t => {
  const component = (tag) => shallow(
    <Button tag={ tag } sheet={{ classes }}>{ child }</Button>
  );

  t.true(
    component("a").is('a'),
    "it should be a type `a`"
  );
  
  t.true(
    component("button").is('button'),
    "it should be a `button`"
  );

  t.true(
    component("input").is('input'),
    "it should be a `input`"
  );
});

test('Block', t => {
  const component = () => shallow(
    <Button block sheet={{ classes }}>
      { child }
    </Button>
  );

  t.true(
    component().hasClass(classes.block),
    "it should have the block class"
  );
});

test('Active', t => {
  const component = () => shallow(
    <Button active sheet={{ classes }}>{ child }</Button>
  );

  t.true(
    component().hasClass(classes.active),
    "it should have the active class"
  );
});

test('Disabled', t => {
  const component = () => shallow(
    <Button disabled sheet={{ classes }}>{ child }</Button>
  );

  t.true(
    component().hasClass(classes.disabled),
    "it should have the disabled class"
  );

 t.true(
    component().is('[disabled=true]'),
    "input should be disabled"
  );
});
```

**Comment by iamstarkov** [comment]
published as a gist https://gist.github.com/iamstarkov/93d7dca38c9f2db46c2f9e25754bb567

**Comment by kserjey** [comment]
@iamstarkov ok there, but what about dynamic styles? I wanted to write a function, that only rendered functional values with specific props.

**Comment by iamstarkov** [comment]
then write tests for styles, like in `styles.test.js`

**Comment by kof** [comment]
Why not to match the css from SheetsRegistry for that component, like in my [example here](https://github.com/cssinjs/react-jss/issues/93#issuecomment-312004965) ?

**Comment by iamstarkov** [comment]
perhaps, like this:

```js
// src/components/button/styles.js
export default {
  button: {
    backgroundColor: props => props.bg
  },
  block: { /* */ },
  active: { /* */ },
  disabled: { /* */ },
}

// src/components/button/styles.test.js
import React from 'react';
import test from 'ava';

import styles from './styles';

test('render root.backgroundColor with props.bg', t => {
  const props = {
    bg: 'red'
  }
  const actual = styles.root.backgroundColor(props);
  const expected = props.bg;

  t.is(actual, expected)
});
```

**Comment by iamstarkov** [comment]
@kof i dont know, for me if my tests can depend on less stuff, thats great

**Comment by kserjey** [comment]
@kof in @iamstarkov realization i don't need to do extra work. HOC makes it very difficult.

**Comment by iamstarkov** [comment]
@kserjey so, are my examples any good?

**Comment by kserjey** [comment]
@iamstarkov yep, i realy like it!

**Comment by kof** [comment]
@iamstarkov its integration tests vs unit tests. Snapshot testing is basically integration tests.

**Comment by iamstarkov** [comment]
@kof sure, but I would like to have integration tests on app level for features

**Comment by iamstarkov** [comment]
> Also we should support testing generated CSS without jest.

@kof see this https://github.com/avajs/ava#snapshot-testing

**Comment by kof** [comment]
Yes, this kind of snapshot testing api is exactly the point of this issue - making them easy to be used. It is just about DX.

**Comment by wzrdzl** [comment]
@kof I am working on a JSS SnapshotSerializer akin to https://github.com/styled-components/jest-styled-components/ and I have a question: is there a way to retrieve the generated sheets from somewhere without rendering a component with a `<JssProvider registry={myRegistry}>`? something like `import { defaultSheetsRegistry } from 'react-jss'`.
The reason I am asking is because it's very tedious to wrap your components in `<JssRegistry>` for every test.

**Comment by alex996** [comment]
@iamstarkov Your examples make sense, but they won't work if you are testing a styled component that has another styled component as part of its markup. The child component will get `classes` as `undefined`.

**Comment by kof** [comment]
@alex996 true, we need to solve this.

**Comment by pelotom** [comment]
Has there been any movement on this? Component snapshot testing with material UI has become basically unusable for us because of all the false positives of CSS class names changing. It's just a bunch of noise 99% of the time, and so people don't pay attention to it when it's a real breakage.

**Comment by kof** [comment]
I am happy to answer JSS related questions to anyone who would like to  work on this. @wzrdzl did you have any success?

**Comment by wzrdzl** [comment]
@pelotom I have managed to come up with a custom snapshot renderer that simply ignores the "dynamic" part of the JSS-generated class names. Unfortunately, I did not manage to implement the same functionality as https://github.com/styled-components/jest-styled-components has - including the styles into the snapshot. Anyways, I will extract the code from my work project, put it on Github and post a link to it in this thread today

**Comment by wzrdzl** [comment]
@pelotom You can find the implementation that works for our project here: https://github.com/cssinjs/jss-snapshot-serializer

**Comment by pelotom** [comment]
@wzrdzl thanks!
