### ISSUE TITLE
Class name is different in SSR and client render, causing React warning

### ISSUE THREAD

**Issue by jedwards1211** [cssinjs/react-jss#97]
Has anyone ever dealt with a warning like this?  (Note that on the client the class name is `root-0-0` and on the server it's `root-0-3`).  @kof this seems like a hairy issue because the random numbers JSS adds in are highly dependent upon rendering order...is there any way I can mitigate this?

```
warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ><div class="root-0-0 container-fluid" d
 (server) ><div class="root-0-3 container-fluid" d
```

**Comment by kof** [comment]
Is the number on the server growing in your case on each reload?

**Comment by jedwards1211** [comment]
Hmmm, the warning went away after seemingly unrelated changes :(  I don't think it was growing with each reload...

At some point I should try to make a test case with nondeterministic rendering.

This is a downside to automatic class name disambiguation that I didn't foresee, I'm bummed about it.  The only solution is to pass fixed (but unique) numbers to `injectSheet`/`jss` for it to append to the class names.  But I'm having trouble thinking of a clean way to automatically generate unique numbers in a non-deterministic way at compile time...

One could easily make a babel plugin to replace some magic constant with filename + count in file, but those would be very long strings to append to the class names.

**Comment by kof** [comment]
I was using hashes before and switched back to counters because hashes had some limitations. One issue we have right now will be fixed soon is [here](https://github.com/cssinjs/jss/pull/494)

**Comment by jedwards1211** [comment]
@kof you do understand that nondeterministic rendering order is a potential problem with counters though, right?

**Comment by kof** [comment]
>  do understand that nondeterministic rendering order is a potential problem with counters though, right?

No, s far as I know rendering order is  ensured by react.

**Comment by a-ignatov-parc** [comment]
I guess this issue is related to https://github.com/cssinjs/react-jss/pull/107
